Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term236 (x0 : nat) (x1 : nat) := Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1).
Definition term265 (x0 : nat) (x1 : nat) := ~ (x0 = x1).
Definition term293 (x0 : nat) (x1 : nat) := @eq Prop ((Peano.lt (Nat.modulo x0 x1) x1) \/ (x1 = (NUMERAL 0))).
Definition term57 (x0 : Prop) := imp ((True -> x0) /\ True).
Definition term241 (x0 : nat) (x1 : nat) (x2 : nat) := ~ ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))).
Definition term246 (x0 : nat) (x1 : nat) := (x1 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo x0 x1) x1).
Definition term290 := (~ False) -> False.
Definition term176 := (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) -> (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0))).
Definition term110 (x0 : nat) (x1 : nat) (x2 : nat) := (fun y0 : nat => (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add x1 (Nat.mul x0 y0)) y0) = (Nat.add x0 (Nat.div x1 y0))) x2.
Definition term197 (x0 : nat) (x1 : nat) (x2 : nat) := ((~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False) -> (~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False.
Definition term282 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (x0 = x1) /\ (x2 = x3).
Definition term278 (x0 : Prop) := ~ (~ x0).
Definition term297 (x0 : nat) := (fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y2 y0) y1) = (Nat.add (Nat.mul y2 y0) (Nat.add (Nat.mul (Nat.div y1 y0) y0) (Nat.modulo y1 y0)))) /\ (Peano.lt (Nat.modulo y1 y0) y0))) -> (forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (y3 = (Nat.add (Nat.mul (Nat.div y3 y4) y4) (Nat.modulo y3 y4))) /\ (Peano.lt (Nat.modulo y3 y4) y4)) -> False) x0.
Definition term108 (x0 : nat) := (fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) x0.
Definition term42 (x0 : nat) := (fun y0 : nat => forall y1 : nat, forall y2 : nat, (exists y3 : nat, (y0 = (Nat.add (Nat.mul y2 y1) y3)) /\ (Peano.lt y3 y1)) -> (Nat.div y0 y1) = y2) x0.
Definition term25 (x0 : nat) := (fun y0 : nat => forall y1 : nat, forall y2 : nat, forall y3 : nat, ((y0 = (Nat.add (Nat.mul y2 y1) y3)) /\ (Peano.lt y3 y1)) -> (Nat.div y0 y1) = y2) x0.
Definition term17 (x0 : nat) := (fun y0 : nat => forall y1 : nat, forall y2 : nat, (Nat.mul (Nat.add y0 y1) y2) = (Nat.add (Nat.mul y0 y2) (Nat.mul y1 y2))) x0.
Definition term14 (x0 : nat) := (fun y0 : nat => forall y1 : nat, forall y2 : nat, (Nat.add (Nat.add y0 y1) y2) = (Nat.add y0 (Nat.add y1 y2))) x0.
Definition term286 (x0 : nat) (x1 : nat) (x2 : nat) := ((Nat.mul x0 x2) = (Nat.mul x0 x2)) /\ (x1 = (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2))).
Definition term232 (x0 : nat) := forall y0 : nat, (y0 = (NUMERAL 0)) \/ ((x0 = (Nat.add (Nat.mul (Nat.div x0 y0) y0) (Nat.modulo x0 y0))) /\ (Peano.lt (Nat.modulo x0 y0) y0)).
Definition term249 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (~ (x1 = x3)) \/ ((Nat.add x0 x1) = (Nat.add x2 x3)).
Definition term167 (x0 : nat) (x1 : nat) := fun y0 : nat => (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul y0 x1)) y0) = (Nat.add (Nat.div x0 y0) x1).
Definition term148 (x0 : nat) (x1 : nat) := fun y0 : nat => (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 y0)) y0) = (Nat.add (Nat.div x0 y0) x1).
Definition term277 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (~ (~ (x0 = x1))) /\ (~ (~ (x2 = x3))).
Definition term189 (x0 : nat) (x1 : nat) (x2 : nat) := and ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))).
Definition term180 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.mul x0 x2) (Nat.mul (Nat.div x1 x2) x2).
Definition term124 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2)).
Definition term94 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add x1 (Nat.mul x0 x2)) x2) = (Nat.add x0 (Nat.div x1 x2)).
Definition term93 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2)).
Definition term204 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False.
Definition term41 := (forall y0 : nat, forall y1 : nat, forall y2 : nat, forall y3 : nat, ((y0 = (Nat.add (Nat.mul y2 y1) y3)) /\ (Peano.lt y3 y1)) -> (Nat.div y0 y1) = y2) -> forall y0 : nat, forall y1 : nat, forall y2 : nat, (exists y3 : nat, (y0 = (Nat.add (Nat.mul y2 y1) y3)) /\ (Peano.lt y3 y1)) -> (Nat.div y0 y1) = y2.
Definition term271 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := @eq Prop (((Nat.add x0 x2) = (Nat.add x1 x3)) \/ ((~ (x0 = x1)) \/ (~ (x2 = x3)))).
Definition term130 (a0 : Type') (x0 : Prop) := forall y0 : a0, x0.
Definition term237 (x0 : nat) := fun y0 : nat => ((y0 = (NUMERAL 0)) \/ (x0 = (Nat.add (Nat.mul (Nat.div x0 y0) y0) (Nat.modulo x0 y0)))) /\ ((y0 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo x0 y0) y0)).
Definition term259 (x0 : nat) (x1 : nat) := @eq Prop ((x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1))) \/ (x1 = (NUMERAL 0))).
Definition term37 (x0 : nat) (x1 : nat) (x2 : nat) := (exists y0 : nat, (x0 = (Nat.add (Nat.mul x2 x1) y0)) /\ (Peano.lt y0 x1)) -> (Nat.div x0 x1) = x2.
Definition term193 (x0 : Prop) := (~ x0) -> False.
Definition term289 (x0 : nat) (x1 : nat) (x2 : nat) := ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) -> False.
Definition term245 (x0 : nat) (x1 : nat) := (x1 = (NUMERAL 0)) \/ (x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1))).
Definition term173 := (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)).
Definition term238 (x0 : nat) := forall y0 : nat, ((y0 = (NUMERAL 0)) \/ (x0 = (Nat.add (Nat.mul (Nat.div x0 y0) y0) (Nat.modulo x0 y0)))) /\ ((y0 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo x0 y0) y0)).
Definition term283 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := imp (~ ((~ (x0 = x1)) \/ (~ (x2 = x3)))).
Definition term73 (x0 : Prop) (x1 : Prop) := ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) = x0) -> (x0 -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = x1) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) -> (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = (x0 -> x1).
Definition term62 (x0 : Prop) (x1 : Prop) := (((x0 -> x1) /\ x0) -> x0 /\ x1) -> ((x0 -> x1) /\ x0) -> x0 /\ x1.
Definition term263 (x0 : nat) (x1 : nat) := ~ (x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1))).
Definition term242 (x0 : nat) (x1 : nat) := ~ (Peano.lt (Nat.modulo x0 x1) x1).
Definition term91 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = ((Nat.div (Nat.add x1 (Nat.mul x0 x2)) x2) = (Nat.add x0 (Nat.div x1 x2))).
Definition term196 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False.
Definition term44 (x0 : nat) (x1 : nat) (x2 : nat) := (fun y0 : nat => (exists y1 : nat, (x0 = (Nat.add (Nat.mul y0 x1) y1)) /\ (Peano.lt y1 x1)) -> (Nat.div x0 x1) = y0) x2.
Definition term210 (x0 : nat) (x1 : nat) := forall y0 : nat, (~ (x1 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y0 x1) x0) = (Nat.add (Nat.mul y0 x1) (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)))) /\ (Peano.lt (Nat.modulo x0 x1) x1))) -> (forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (y1 = (Nat.add (Nat.mul (Nat.div y1 y2) y2) (Nat.modulo y1 y2))) /\ (Peano.lt (Nat.modulo y1 y2) y2)) -> False.
Definition term294 (x0 : nat) (x1 : nat) := (~ (x1 = (NUMERAL 0))) -> Peano.lt (Nat.modulo x0 x1) x1.
Definition term260 (x0 : Prop) (x1 : Prop) := (~ x0) -> x1.
Definition term281 (x0 : nat) (x1 : nat) := and (x0 = x1).
Definition term292 (x0 : nat) (x1 : nat) := @eq Prop ((x1 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo x0 x1) x1)).
Definition term106 (x0 : Prop) := ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) = (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2)))) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = x0) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) -> (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) -> x0).
Definition term63 := (((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) -> (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2)))) -> (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))).
Definition term201 := ~ (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)).
Definition term1 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.add x0 x1) x2.
Definition term224 (x0 : nat) (x1 : nat) (x2 : nat) := (~ ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2))))) \/ (~ (Peano.lt (Nat.modulo x1 x2) x2)).
Definition term226 (x0 : nat) (x1 : nat) := (x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1))) /\ (Peano.lt (Nat.modulo x0 x1) x1).
Definition term300 (x0 : nat) (x1 : nat) (x2 : nat) := exists y0 : nat, ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul (Nat.add x0 (Nat.div x1 x2)) x2) y0)) /\ (Peano.lt y0 x2).
Definition term35 (x0 : nat) (x1 : nat) (x2 : nat) := exists y0 : nat, (x0 = (Nat.add (Nat.mul x1 x2) y0)) /\ (Peano.lt y0 x2).
Definition term163 (x0 : nat) (x1 : nat) (x2 : nat) := @eq nat (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x2).
Definition term90 (x0 : nat) (x1 : nat) (x2 : nat) := @eq nat (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x2).
Definition term177 := (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) -> True.
Definition term254 (x0 : Prop) := (~ x0) -> x0.
Definition term244 (x0 : nat) (x1 : nat) := (fun y0 : nat => ((y0 = (NUMERAL 0)) \/ (x0 = (Nat.add (Nat.mul (Nat.div x0 y0) y0) (Nat.modulo x0 y0)))) /\ ((y0 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo x0 y0) y0))) x1.
Definition term284 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := imp ((x0 = x1) /\ (x2 = x3)).
Definition term231 (x0 : nat) := fun y0 : nat => (y0 = (NUMERAL 0)) \/ ((x0 = (Nat.add (Nat.mul (Nat.div x0 y0) y0) (Nat.modulo x0 y0))) /\ (Peano.lt (Nat.modulo x0 y0) y0)).
Definition term285 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := ((x0 = x2) /\ (x1 = x3)) -> (Nat.add x0 x1) = (Nat.add x2 x3).
Definition term2 (x0 : nat) (x1 : nat) := fun y0 : nat => (Nat.add x0 (Nat.add x1 y0)) = (Nat.add (Nat.add x0 x1) y0).
Definition term206 (x0 : nat) := imp (~ (x0 = (NUMERAL 0))).
Definition term61 (x0 : Prop) (x1 : Prop) := (((x0 -> x1) /\ x0) -> x0 /\ x1) -> x0 /\ x1.
Definition term275 (x0 : Prop) (x1 : Prop) := (~ x0) /\ (~ x1).
Definition term257 (x0 : nat) (x1 : nat) := (x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1))) \/ (x1 = (NUMERAL 0)).
Definition term33 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (x0 = (Nat.add (Nat.mul x1 x3) x2)) /\ (Peano.lt x2 x3).
Definition term70 (x0 : Prop) := (fun y0 : Prop => forall y1 : Prop, ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y4) y3) y4) = (Nat.add y2 (Nat.div y3 y4))) = y0) -> (y0 -> ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y4 y2) y3) y4) = (Nat.add y2 (Nat.div y3 y4))) /\ ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add y3 (Nat.mul y2 y4)) y4) = (Nat.add (Nat.div y3 y4) y2)) /\ (forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add y3 (Nat.mul y4 y2)) y4) = (Nat.add (Nat.div y3 y4) y2)))) = y1) -> ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y4) y3) y4) = (Nat.add y2 (Nat.div y3 y4))) -> (forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y4 y2) y3) y4) = (Nat.add y2 (Nat.div y3 y4))) /\ ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add y3 (Nat.mul y2 y4)) y4) = (Nat.add (Nat.div y3 y4) y2)) /\ (forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add y3 (Nat.mul y4 y2)) y4) = (Nat.add (Nat.div y3 y4) y2)))) = (y0 -> y1)) x0.
Definition term31 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (fun y0 : nat => ((x0 = (Nat.add (Nat.mul x2 x1) y0)) /\ (Peano.lt y0 x1)) -> (Nat.div x0 x1) = x2) x3.
Definition term4 (x0 : nat) (x1 : nat) := forall y0 : nat, (Nat.add x0 (Nat.add x1 y0)) = (Nat.add (Nat.add x0 x1) y0).
Definition term157 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := (fun y0 : Prop => forall y1 : Prop, ((~ (x1 = (NUMERAL 0))) = y0) -> (y0 -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = y1) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (y0 -> y1)) x3.
Definition term139 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := (fun y0 : Prop => forall y1 : Prop, ((~ (x1 = (NUMERAL 0))) = y0) -> (y0 -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = y1) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (y0 -> y1)) x3.
Definition term113 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := (fun y0 : Prop => forall y1 : Prop, ((~ (x2 = (NUMERAL 0))) = y0) -> (y0 -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = y1) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (y0 -> y1)) x3.
Definition term78 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := (fun y0 : Prop => forall y1 : Prop, ((~ (x2 = (NUMERAL 0))) = y0) -> (y0 -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = y1) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (y0 -> y1)) x3.
Definition term191 (x0 : nat) (x1 : nat) (x2 : nat) := ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul (Nat.add x0 (Nat.div x1 x2)) x2) (Nat.modulo x1 x2))) /\ (Peano.lt (Nat.modulo x1 x2) x2).
Definition term258 (x0 : nat) (x1 : nat) := @eq Prop ((x1 = (NUMERAL 0)) \/ (x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)))).
Definition term268 (x0 : Prop) (x1 : Prop) (x2 : Prop) := x0 \/ (x1 \/ x2).
Definition term298 (x0 : nat) (x1 : nat) := (fun y0 : nat => forall y1 : nat, (~ (x0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y1 x0) y0) = (Nat.add (Nat.mul y1 x0) (Nat.add (Nat.mul (Nat.div y0 x0) x0) (Nat.modulo y0 x0)))) /\ (Peano.lt (Nat.modulo y0 x0) x0))) -> (forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (y2 = (Nat.add (Nat.mul (Nat.div y2 y3) y3) (Nat.modulo y2 y3))) /\ (Peano.lt (Nat.modulo y2 y3) y3)) -> False) x1.
Definition term109 (x0 : nat) (x1 : nat) := (fun y0 : nat => forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add y0 (Nat.mul x0 y1)) y1) = (Nat.add x0 (Nat.div y0 y1))) x1.
Definition term43 (x0 : nat) (x1 : nat) := (fun y0 : nat => forall y1 : nat, (exists y2 : nat, (x0 = (Nat.add (Nat.mul y1 y0) y2)) /\ (Peano.lt y2 y0)) -> (Nat.div x0 y0) = y1) x1.
Definition term19 (x0 : nat) (x1 : nat) := (fun y0 : nat => forall y1 : nat, (Nat.mul (Nat.add x0 y0) y1) = (Nat.add (Nat.mul x0 y1) (Nat.mul y0 y1))) x1.
Definition term15 (x0 : nat) (x1 : nat) := (fun y0 : nat => forall y1 : nat, (Nat.add (Nat.add x0 y0) y1) = (Nat.add x0 (Nat.add y0 y1))) x1.
Definition term269 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := ((Nat.add x0 x2) = (Nat.add x1 x3)) \/ ((~ (x0 = x1)) \/ (~ (x2 = x3))).
Definition term75 (x0 : nat) := ~ (x0 = (NUMERAL 0)).
Definition term6 (x0 : nat) := fun y0 : nat => forall y1 : nat, (Nat.add x0 (Nat.add y0 y1)) = (Nat.add (Nat.add x0 y0) y1).
Definition term303 := (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))).
Definition term229 (x0 : nat) (x1 : nat) := (~ (~ (x1 = (NUMERAL 0)))) \/ ((x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1))) /\ (Peano.lt (Nat.modulo x0 x1) x1)).
Definition term264 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := ((Nat.add x0 x2) = (Nat.add x1 x3)) \/ (~ (x2 = x3)).
Definition term120 (x0 : nat) (x1 : nat) (x2 : nat) := @eq nat (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2).
Definition term89 (x0 : nat) (x1 : nat) (x2 : nat) := @eq nat (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2).
Definition term160 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) (x4 : Prop) := ((~ (x1 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = x4) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (x3 -> x4).
Definition term142 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) (x4 : Prop) := ((~ (x1 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = x4) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (x3 -> x4).
Definition term116 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) (x4 : Prop) := ((~ (x2 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = x4) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (x3 -> x4).
Definition term81 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) (x4 : Prop) := ((~ (x2 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = x4) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (x3 -> x4).
Definition term48 (x0 : Prop) (x1 : Prop) := (fun y0 : Prop => ((y0 -> x0) /\ y0) -> y0 /\ x0) x1.
Definition term287 (x0 : nat) (x1 : nat) (x2 : nat) := (((Nat.mul x0 x2) = (Nat.mul x0 x2)) /\ (x1 = (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) -> (Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2))).
Definition term186 (x0 : nat) (x1 : nat) := Nat.mul (Nat.div x0 x1) x1.
Definition term211 (x0 : nat) (x1 : nat) := forall y0 : nat, (~ (x1 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y0 x1) x0) = (Nat.add (Nat.mul y0 x1) (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)))) /\ (Peano.lt (Nat.modulo x0 x1) x1))) -> ~ (forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (y1 = (Nat.add (Nat.mul (Nat.div y1 y2) y2) (Nat.modulo y1 y2))) /\ (Peano.lt (Nat.modulo y1 y2) y2)).
Definition term66 (x0 : Prop) (x1 : Prop) (x2 : Prop) (x3 : Prop) := (x0 = x2) -> (x2 -> x1 = x3) -> (x0 -> x1) = (x2 -> x3).
Definition term288 (x0 : nat) (x1 : nat) (x2 : nat) := (~ ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2))))) -> (Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2))).
Definition term65 := (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0))).
Definition term200 := (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False.
Definition term54 (x0 : Prop) := (fun y0 : Prop => ((y0 -> x0) /\ y0) -> y0 /\ x0) False.
Definition term299 (x0 : nat) (x1 : nat) (x2 : nat) := (fun y0 : nat => (~ (x1 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y0 x1) x0) = (Nat.add (Nat.mul y0 x1) (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)))) /\ (Peano.lt (Nat.modulo x0 x1) x1))) -> (forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (y1 = (Nat.add (Nat.mul (Nat.div y1 y2) y2) (Nat.modulo y1 y2))) /\ (Peano.lt (Nat.modulo y1 y2) y2)) -> False) x2.
Definition term128 (x0 : nat) (x1 : nat) := forall y0 : nat, (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 x0) x1) y0) = (Nat.add x0 (Nat.div x1 y0)).
Definition term98 (x0 : nat) (x1 : nat) := forall y0 : nat, (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add x1 (Nat.mul x0 y0)) y0) = (Nat.add x0 (Nat.div x1 y0)).
Definition term97 (x0 : nat) (x1 : nat) := forall y0 : nat, (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 y0) x1) y0) = (Nat.add x0 (Nat.div x1 y0)).
Definition term272 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (~ ((~ (x0 = x2)) \/ (~ (x1 = x3)))) -> (Nat.add x0 x1) = (Nat.add x2 x3).
Definition term55 (x0 : Prop) := ((False -> x0) /\ False) -> False /\ x0.
Definition term203 (x0 : nat) (x1 : nat) (x2 : nat) := imp (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))).
Definition term121 (x0 : nat) (x1 : nat) (x2 : nat) := @eq nat (Nat.add x0 (Nat.div x1 x2)).
Definition term207 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> ~ (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)).
Definition term32 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := ((x1 = (Nat.add (Nat.mul x3 x2) x0)) /\ (Peano.lt x0 x2)) -> (Nat.div x1 x2) = x3.
Definition term174 := (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = True.
Definition term49 (x0 : Prop) := (fun y0 : Prop => ((y0 -> x0) /\ y0) -> y0 /\ x0) True.
Definition term227 (x0 : nat) := or (~ (~ (x0 = (NUMERAL 0)))).
Definition term221 (x0 : nat) := fun y0 : nat => (~ (y0 = (NUMERAL 0))) -> (x0 = (Nat.add (Nat.mul (Nat.div x0 y0) y0) (Nat.modulo x0 y0))) /\ (Peano.lt (Nat.modulo x0 y0) y0).
Definition term228 (x0 : nat) := or (x0 = (NUMERAL 0)).
Definition term53 (x0 : Prop) (x1 : Prop) := @eq Prop (((x0 -> x1) /\ x0) -> x0 /\ x1).
Definition term274 (x0 : Prop) (x1 : Prop) := ~ (x0 \/ x1).
Definition term30 (x0 : nat) (x1 : nat) (x2 : nat) := forall y0 : nat, ((x0 = (Nat.add (Nat.mul x2 x1) y0)) /\ (Peano.lt y0 x1)) -> (Nat.div x0 x1) = x2.
Definition term240 := forall y0 : nat, forall y1 : nat, ((y1 = (NUMERAL 0)) \/ (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1)))) /\ ((y1 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo y0 y1) y1)).
Definition term234 := forall y0 : nat, forall y1 : nat, (y1 = (NUMERAL 0)) \/ ((y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)).
Definition term219 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y2 y0) y1) = (Nat.add (Nat.mul y2 y0) (Nat.add (Nat.mul (Nat.div y1 y0) y0) (Nat.modulo y1 y0)))) /\ (Peano.lt (Nat.modulo y1 y0) y0))) -> ~ (forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (y3 = (Nat.add (Nat.mul (Nat.div y3 y4) y4) (Nat.modulo y3 y4))) /\ (Peano.lt (Nat.modulo y3 y4) y4)).
Definition term218 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y2 y0) y1) = (Nat.add (Nat.mul y2 y0) (Nat.add (Nat.mul (Nat.div y1 y0) y0) (Nat.modulo y1 y0)))) /\ (Peano.lt (Nat.modulo y1 y0) y0))) -> (forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (y3 = (Nat.add (Nat.mul (Nat.div y3 y4) y4) (Nat.modulo y3 y4))) /\ (Peano.lt (Nat.modulo y3 y4) y4)) -> False.
Definition term215 (x0 : nat) := forall y0 : nat, forall y1 : nat, (~ (x0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y1 x0) y0) = (Nat.add (Nat.mul y1 x0) (Nat.add (Nat.mul (Nat.div y0 x0) x0) (Nat.modulo y0 x0)))) /\ (Peano.lt (Nat.modulo y0 x0) x0))) -> ~ (forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (y2 = (Nat.add (Nat.mul (Nat.div y2 y3) y3) (Nat.modulo y2 y3))) /\ (Peano.lt (Nat.modulo y2 y3) y3)).
Definition term214 (x0 : nat) := forall y0 : nat, forall y1 : nat, (~ (x0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y1 x0) y0) = (Nat.add (Nat.mul y1 x0) (Nat.add (Nat.mul (Nat.div y0 x0) x0) (Nat.modulo y0 x0)))) /\ (Peano.lt (Nat.modulo y0 x0) x0))) -> (forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (y2 = (Nat.add (Nat.mul (Nat.div y2 y3) y3) (Nat.modulo y2 y3))) /\ (Peano.lt (Nat.modulo y2 y3) y3)) -> False.
Definition term202 := forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1).
Definition term172 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0).
Definition term170 (x0 : nat) := forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add y0 (Nat.mul y1 x0)) y1) = (Nat.add (Nat.div y0 y1) x0).
Definition term153 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0).
Definition term151 (x0 : nat) := forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add y0 (Nat.mul x0 y1)) y1) = (Nat.add (Nat.div y0 y1) x0).
Definition term135 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2)).
Definition term133 (x0 : nat) := forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y1 x0) y0) y1) = (Nat.add x0 (Nat.div y0 y1)).
Definition term105 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2)).
Definition term102 (x0 : nat) := forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add y0 (Nat.mul x0 y1)) y1) = (Nat.add x0 (Nat.div y0 y1)).
Definition term101 (x0 : nat) := forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 y1) y0) y1) = (Nat.add x0 (Nat.div y0 y1)).
Definition term64 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2)).
Definition term40 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (exists y3 : nat, (y0 = (Nat.add (Nat.mul y2 y1) y3)) /\ (Peano.lt y3 y1)) -> (Nat.div y0 y1) = y2.
Definition term39 (x0 : nat) := forall y0 : nat, forall y1 : nat, (exists y2 : nat, (x0 = (Nat.add (Nat.mul y1 y0) y2)) /\ (Peano.lt y2 y0)) -> (Nat.div x0 y0) = y1.
Definition term28 (x0 : nat) (x1 : nat) := forall y0 : nat, forall y1 : nat, ((x0 = (Nat.add (Nat.mul y0 x1) y1)) /\ (Peano.lt y1 x1)) -> (Nat.div x0 x1) = y0.
Definition term26 (x0 : nat) := forall y0 : nat, forall y1 : nat, forall y2 : nat, ((x0 = (Nat.add (Nat.mul y1 y0) y2)) /\ (Peano.lt y2 y0)) -> (Nat.div x0 y0) = y1.
Definition term24 := forall y0 : nat, forall y1 : nat, forall y2 : nat, forall y3 : nat, ((y0 = (Nat.add (Nat.mul y2 y1) y3)) /\ (Peano.lt y3 y1)) -> (Nat.div y0 y1) = y2.
Definition term18 (x0 : nat) := forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add x0 y0) y1) = (Nat.add (Nat.mul x0 y1) (Nat.mul y0 y1)).
Definition term13 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (Nat.add (Nat.add y0 y1) y2) = (Nat.add y0 (Nat.add y1 y2)).
Definition term12 := forall y0 : nat, forall y1 : nat, forall y2 : nat, (Nat.add y0 (Nat.add y1 y2)) = (Nat.add (Nat.add y0 y1) y2).
Definition term9 (x0 : nat) := forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add x0 y0) y1) = (Nat.add x0 (Nat.add y0 y1)).
Definition term8 (x0 : nat) := forall y0 : nat, forall y1 : nat, (Nat.add x0 (Nat.add y0 y1)) = (Nat.add (Nat.add x0 y0) y1).
Definition term261 (x0 : nat) (x1 : nat) := (~ (x1 = (NUMERAL 0))) -> x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)).
Definition term86 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.div (Nat.add (Nat.mul x0 x1) x2).
Definition term184 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.add (Nat.mul x0 x2) (Nat.mul (Nat.div x1 x2) x2)) (Nat.modulo x1 x2).
Definition term47 (x0 : Prop) := fun y0 : Prop => ((y0 -> x0) /\ y0) -> y0 /\ x0.
Definition term59 (x0 : Prop) := imp ((False -> x0) /\ False).
Definition term29 (x0 : nat) (x1 : nat) (x2 : nat) := (fun y0 : nat => forall y1 : nat, ((x0 = (Nat.add (Nat.mul y0 x1) y1)) /\ (Peano.lt y1 x1)) -> (Nat.div x0 x1) = y0) x2.
Definition term27 (x0 : nat) (x1 : nat) := (fun y0 : nat => forall y1 : nat, forall y2 : nat, ((x0 = (Nat.add (Nat.mul y1 y0) y2)) /\ (Peano.lt y2 y0)) -> (Nat.div x0 y0) = y1) x1.
Definition term161 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := ((~ (x2 = (NUMERAL 0))) = (~ (x2 = (NUMERAL 0)))) -> ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x2) = (Nat.add (Nat.div x0 x2) x1)) = x3) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x2) = (Nat.add (Nat.div x0 x2) x1)) = ((~ (x2 = (NUMERAL 0))) -> x3).
Definition term143 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := ((~ (x2 = (NUMERAL 0))) = (~ (x2 = (NUMERAL 0)))) -> ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x2) = (Nat.add (Nat.div x0 x2) x1)) = x3) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x2) = (Nat.add (Nat.div x0 x2) x1)) = ((~ (x2 = (NUMERAL 0))) -> x3).
Definition term117 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := ((~ (x2 = (NUMERAL 0))) = (~ (x2 = (NUMERAL 0)))) -> ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = x3) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = ((~ (x2 = (NUMERAL 0))) -> x3).
Definition term82 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := ((~ (x2 = (NUMERAL 0))) = (~ (x2 = (NUMERAL 0)))) -> ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = x3) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = ((~ (x2 = (NUMERAL 0))) -> x3).
Definition term270 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := @eq Prop ((~ (x0 = x2)) \/ ((~ (x1 = x3)) \/ ((Nat.add x0 x1) = (Nat.add x2 x3)))).
Definition term301 (x0 : nat) (x1 : nat) (x2 : nat) := fun y0 : nat => ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul (Nat.add x0 (Nat.div x1 x2)) x2) y0)) /\ (Peano.lt y0 x2).
Definition term122 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = True.
Definition term291 (x0 : nat) (x1 : nat) := (Peano.lt (Nat.modulo x0 x1) x1) \/ (x1 = (NUMERAL 0)).
Definition term187 (x0 : nat) (x1 : nat) (x2 : nat) := @eq nat (Nat.add (Nat.mul x0 x1) x2).
Definition term52 (x0 : Prop) (x1 : Prop) := ((x0 -> x1) /\ x0) -> x0 /\ x1.
Definition term21 (x0 : nat) (x1 : nat) (x2 : nat) := (fun y0 : nat => (Nat.mul (Nat.add x0 x1) y0) = (Nat.add (Nat.mul x0 y0) (Nat.mul x1 y0))) x2.
Definition term129 := forall y0 : nat, True.
Definition term220 (x0 : nat) (x1 : nat) := (~ (x1 = (NUMERAL 0))) -> (x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1))) /\ (Peano.lt (Nat.modulo x0 x1) x1).
Definition term247 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (x1 = x3) -> (Nat.add x0 x1) = (Nat.add x2 x3).
Definition term182 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.add (Nat.mul x0 x2) (Nat.mul (Nat.div x1 x2) x2)).
Definition term156 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.div (Nat.add x0 (Nat.mul x2 x1)) x2.
Definition term34 (x0 : nat) (x1 : nat) (x2 : nat) := (forall y0 : nat, forall y1 : nat, forall y2 : nat, forall y3 : nat, ((y0 = (Nat.add (Nat.mul y2 y1) y3)) /\ (Peano.lt y3 y1)) -> (Nat.div y0 y1) = y2) -> (Nat.div x0 x1) = x2.
Definition term58 (x0 : Prop) := (False -> x0) /\ False.
Definition term22 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.mul (Nat.add x0 x1) x2.
Definition term192 (x0 : nat) (x1 : nat) (x2 : nat) := ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2).
Definition term23 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.mul x0 x2) (Nat.mul x1 x2).
Definition term253 (x0 : nat) (x1 : nat) := ~ ((Nat.mul x0 x1) = (Nat.mul x0 x1)).
Definition term302 := ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) -> (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))).
Definition term127 := fun y0 : nat => True.
Definition term183 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.mul (Nat.add x0 (Nat.div x1 x2)) x2) (Nat.modulo x1 x2).
Definition term51 (x0 : Prop) (x1 : Prop) := @eq Prop ((fun y0 : Prop => ((y0 -> x0) /\ y0) -> y0 /\ x0) x1).
Definition term158 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := forall y0 : Prop, ((~ (x1 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = y0) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (x3 -> y0).
Definition term140 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := forall y0 : Prop, ((~ (x1 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = y0) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (x3 -> y0).
Definition term114 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := forall y0 : Prop, ((~ (x2 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = y0) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (x3 -> y0).
Definition term79 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := forall y0 : Prop, ((~ (x2 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = y0) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (x3 -> y0).
Definition term71 (x0 : Prop) := forall y0 : Prop, ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y1 y3) y2) y3) = (Nat.add y1 (Nat.div y2 y3))) = x0) -> (x0 -> ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y3 y1) y2) y3) = (Nat.add y1 (Nat.div y2 y3))) /\ ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add y2 (Nat.mul y1 y3)) y3) = (Nat.add (Nat.div y2 y3) y1)) /\ (forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add y2 (Nat.mul y3 y1)) y3) = (Nat.add (Nat.div y2 y3) y1)))) = y0) -> ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y1 y3) y2) y3) = (Nat.add y1 (Nat.div y2 y3))) -> (forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y3 y1) y2) y3) = (Nat.add y1 (Nat.div y2 y3))) /\ ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add y2 (Nat.mul y1 y3)) y3) = (Nat.add (Nat.div y2 y3) y1)) /\ (forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add y2 (Nat.mul y3 y1)) y3) = (Nat.add (Nat.div y2 y3) y1)))) = (x0 -> y0).
Definition term67 (x0 : Prop) (x1 : Prop) (x2 : Prop) := forall y0 : Prop, (x0 = x2) -> (x2 -> x1 = y0) -> (x0 -> x1) = (x2 -> y0).
Definition term36 (x0 : nat) (x1 : nat) (x2 : nat) := fun y0 : nat => (x0 = (Nat.add (Nat.mul x1 x2) y0)) /\ (Peano.lt y0 x2).
Definition term255 (x0 : nat) := (x0 = (NUMERAL 0)) -> ~ (x0 = (NUMERAL 0)).
Definition term178 (x0 : nat) (x1 : nat) (x2 : nat) := (exists y0 : nat, ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul (Nat.add x0 (Nat.div x1 x2)) x2) y0)) /\ (Peano.lt y0 x2)) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2)).
Definition term16 (x0 : nat) (x1 : nat) (x2 : nat) := (fun y0 : nat => (Nat.add (Nat.add x0 x1) y0) = (Nat.add x0 (Nat.add x1 y0))) x2.
Definition term199 (x0 : nat) (x1 : nat) (x2 : nat) := (((~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False) -> (~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False) -> ((~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False) -> (~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False.
Definition term46 (x0 : Prop) := (x0 = True) \/ (x0 = False).
Definition term155 (x0 : nat) (x1 : nat) (x2 : nat) := forall y0 : Prop, forall y1 : Prop, ((~ (x1 = (NUMERAL 0))) = y0) -> (y0 -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = y1) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (y0 -> y1).
Definition term137 (x0 : nat) (x1 : nat) (x2 : nat) := forall y0 : Prop, forall y1 : Prop, ((~ (x1 = (NUMERAL 0))) = y0) -> (y0 -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = y1) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (y0 -> y1).
Definition term111 (x0 : nat) (x1 : nat) (x2 : nat) := forall y0 : Prop, forall y1 : Prop, ((~ (x2 = (NUMERAL 0))) = y0) -> (y0 -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = y1) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (y0 -> y1).
Definition term74 (x0 : nat) (x1 : nat) (x2 : nat) := forall y0 : Prop, forall y1 : Prop, ((~ (x2 = (NUMERAL 0))) = y0) -> (y0 -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = y1) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (y0 -> y1).
Definition term69 := forall y0 : Prop, forall y1 : Prop, ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y4) y3) y4) = (Nat.add y2 (Nat.div y3 y4))) = y0) -> (y0 -> ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y4 y2) y3) y4) = (Nat.add y2 (Nat.div y3 y4))) /\ ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add y3 (Nat.mul y2 y4)) y4) = (Nat.add (Nat.div y3 y4) y2)) /\ (forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add y3 (Nat.mul y4 y2)) y4) = (Nat.add (Nat.div y3 y4) y2)))) = y1) -> ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y4) y3) y4) = (Nat.add y2 (Nat.div y3 y4))) -> (forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y4 y2) y3) y4) = (Nat.add y2 (Nat.div y3 y4))) /\ ((forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add y3 (Nat.mul y2 y4)) y4) = (Nat.add (Nat.div y3 y4) y2)) /\ (forall y2 : nat, forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (Nat.div (Nat.add y3 (Nat.mul y4 y2)) y4) = (Nat.add (Nat.div y3 y4) y2)))) = (y0 -> y1).
Definition term68 (x0 : Prop) (x1 : Prop) := forall y0 : Prop, forall y1 : Prop, (x0 = y0) -> (y0 -> x1 = y1) -> (x0 -> x1) = (y0 -> y1).
Definition term280 (x0 : nat) (x1 : nat) := and (~ (~ (x0 = x1))).
Definition term112 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.div (Nat.add (Nat.mul x2 x0) x1) x2.
Definition term76 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.div (Nat.add (Nat.mul x0 x2) x1) x2.
Definition term252 (x0 : nat) (x1 : nat) := (~ ((Nat.mul x0 x1) = (Nat.mul x0 x1))) -> (Nat.mul x0 x1) = (Nat.mul x0 x1).
Definition term0 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add x0 (Nat.add x1 x2).
Definition term185 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)).
Definition term138 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.div x0 x1) x2.
Definition term208 (x0 : nat) (x1 : nat) := fun y0 : nat => (~ (x1 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y0 x1) x0) = (Nat.add (Nat.mul y0 x1) (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)))) /\ (Peano.lt (Nat.modulo x0 x1) x1))) -> (forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (y1 = (Nat.add (Nat.mul (Nat.div y1 y2) y2) (Nat.modulo y1 y2))) /\ (Peano.lt (Nat.modulo y1 y2) y2)) -> False.
Definition term56 (x0 : Prop) := (True -> x0) /\ True.
Definition term159 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) (x4 : Prop) := (fun y0 : Prop => ((~ (x1 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = y0) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (x3 -> y0)) x4.
Definition term141 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) (x4 : Prop) := (fun y0 : Prop => ((~ (x1 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = y0) -> ((~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = (x3 -> y0)) x4.
Definition term115 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) (x4 : Prop) := (fun y0 : Prop => ((~ (x2 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = y0) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (x3 -> y0)) x4.
Definition term80 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) (x4 : Prop) := (fun y0 : Prop => ((~ (x2 = (NUMERAL 0))) = x3) -> (x3 -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = y0) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = (x3 -> y0)) x4.
Definition term38 (x0 : nat) (x1 : nat) := forall y0 : nat, (exists y1 : nat, (x0 = (Nat.add (Nat.mul y0 x1) y1)) /\ (Peano.lt y1 x1)) -> (Nat.div x0 x1) = y0.
Definition term166 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2).
Definition term147 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x1 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2).
Definition term154 := and (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)).
Definition term136 := and (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))).
Definition term162 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x2) = (Nat.add (Nat.div x0 x2) x1)) = x3) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x2) = (Nat.add (Nat.div x0 x2) x1)) = ((~ (x2 = (NUMERAL 0))) -> x3).
Definition term144 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x2) = (Nat.add (Nat.div x0 x2) x1)) = x3) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x2) = (Nat.add (Nat.div x0 x2) x1)) = ((~ (x2 = (NUMERAL 0))) -> x3).
Definition term118 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = x3) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = ((~ (x2 = (NUMERAL 0))) -> x3).
Definition term83 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : Prop) := ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = x3) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = ((~ (x2 = (NUMERAL 0))) -> x3).
Definition term267 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (~ (x0 = x1)) \/ (((Nat.add x0 x2) = (Nat.add x1 x3)) \/ (~ (x2 = x3))).
Definition term243 (x0 : nat) := (fun y0 : nat => forall y1 : nat, ((y1 = (NUMERAL 0)) \/ (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1)))) /\ ((y1 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo y0 y1) y1))) x0.
Definition term92 (x0 : nat) (x1 : nat) (x2 : nat) := ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = ((Nat.div (Nat.add x1 (Nat.mul x0 x2)) x2) = (Nat.add x0 (Nat.div x1 x2)))) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 x2) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add x1 (Nat.mul x0 x2)) x2) = (Nat.add x0 (Nat.div x1 x2))).
Definition term164 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x1 = (NUMERAL 0))) -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x1) = (Nat.add (Nat.div x0 x1) x2)) = True.
Definition term145 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (x1 = (NUMERAL 0))) -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x1) = (Nat.add (Nat.div x0 x1) x2)) = True.
Definition term60 (x0 : Prop) (x1 : Prop) := (x1 -> x0) /\ x1.
Definition term195 (x0 : nat) (x1 : nat) (x2 : nat) := ~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2)).
Definition term87 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.div (Nat.add x0 (Nat.mul x1 x2)).
Definition term209 (x0 : nat) (x1 : nat) := fun y0 : nat => (~ (x1 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y0 x1) x0) = (Nat.add (Nat.mul y0 x1) (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)))) /\ (Peano.lt (Nat.modulo x0 x1) x1))) -> ~ (forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (y1 = (Nat.add (Nat.mul (Nat.div y1 y2) y2) (Nat.modulo y1 y2))) /\ (Peano.lt (Nat.modulo y1 y2) y2)).
Definition term107 (x0 : Prop) := ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = x0) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) -> (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) -> x0).
Definition term20 (x0 : nat) (x1 : nat) := forall y0 : nat, (Nat.mul (Nat.add x0 x1) y0) = (Nat.add (Nat.mul x0 y0) (Nat.mul x1 y0)).
Definition term235 (x0 : nat) (x1 : nat) := ((x1 = (NUMERAL 0)) \/ (x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)))) /\ ((x1 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo x0 x1) x1)).
Definition term276 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := ~ ((~ (x0 = x1)) \/ (~ (x2 = x3))).
Definition term250 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (x0 = x2) -> (~ (x1 = x3)) \/ ((Nat.add x0 x1) = (Nat.add x2 x3)).
Definition term262 (x0 : nat) (x1 : nat) := (~ (x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)))) -> x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1)).
Definition term198 (x0 : nat) (x1 : nat) (x2 : nat) := (((~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False) -> (~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False) -> (~ (x2 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)) -> False.
Definition term165 (x0 : nat) (x1 : nat) (x2 : nat) := ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add x0 (Nat.mul x2 x1)) x2) = (Nat.add (Nat.div x0 x2) x1)) = True) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x2 x1)) x2) = (Nat.add (Nat.div x0 x2) x1)) = ((~ (x2 = (NUMERAL 0))) -> True).
Definition term146 (x0 : nat) (x1 : nat) (x2 : nat) := ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add x0 (Nat.mul x1 x2)) x2) = (Nat.add (Nat.div x0 x2) x1)) = True) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 x2)) x2) = (Nat.add (Nat.div x0 x2) x1)) = ((~ (x2 = (NUMERAL 0))) -> True).
Definition term123 (x0 : nat) (x1 : nat) (x2 : nat) := ((~ (x2 = (NUMERAL 0))) -> ((Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = True) -> ((~ (x2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x2 x0) x1) x2) = (Nat.add x0 (Nat.div x1 x2))) = ((~ (x2 = (NUMERAL 0))) -> True).
Definition term50 (x0 : Prop) := ((True -> x0) /\ True) -> True /\ x0.
Definition term125 (x0 : nat) := (~ (x0 = (NUMERAL 0))) -> True.
Definition term248 (x0 : Prop) (x1 : Prop) := (~ x0) \/ x1.
Definition term119 (x0 : nat) := (~ (x0 = (NUMERAL 0))) -> (x0 = (NUMERAL 0)) = False.
Definition term126 (x0 : nat) (x1 : nat) := fun y0 : nat => (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 x0) x1) y0) = (Nat.add x0 (Nat.div x1 y0)).
Definition term96 (x0 : nat) (x1 : nat) := fun y0 : nat => (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add x1 (Nat.mul x0 y0)) y0) = (Nat.add x0 (Nat.div x1 y0)).
Definition term95 (x0 : nat) (x1 : nat) := fun y0 : nat => (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 y0) x1) y0) = (Nat.add x0 (Nat.div x1 y0)).
Definition term190 (x0 : nat) (x1 : nat) := Peano.lt (Nat.modulo x0 x1) x1.
Definition term273 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (~ (x0 = x1)) \/ (~ (x2 = x3)).
Definition term205 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> ~ (forall y0 : nat, forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)).
Definition term175 := ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = True) -> ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) -> (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2))) /\ ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0)) /\ (forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0)))) = ((forall y0 : nat, forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2))) -> True).
Definition term131 (x0 : Prop) := forall y0 : nat, x0.
Definition term251 (x0 : nat) (x1 : nat) (x2 : nat) (x3 : nat) := (~ (x0 = x2)) \/ ((~ (x1 = x3)) \/ ((Nat.add x0 x1) = (Nat.add x2 x3))).
Definition term5 (x0 : nat) (x1 : nat) := forall y0 : nat, (Nat.add (Nat.add x0 x1) y0) = (Nat.add x0 (Nat.add x1 y0)).
Definition term181 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.mul (Nat.add x0 (Nat.div x1 x2)) x2).
Definition term194 (x0 : nat) (x1 : nat) (x2 : nat) := (~ (((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul x0 x2) (Nat.add (Nat.mul (Nat.div x1 x2) x2) (Nat.modulo x1 x2)))) /\ (Peano.lt (Nat.modulo x1 x2) x2))) -> False.
Definition term179 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.mul (Nat.add x0 (Nat.div x1 x2)) x2.
Definition term72 (x0 : Prop) (x1 : Prop) := (fun y0 : Prop => ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y1 y3) y2) y3) = (Nat.add y1 (Nat.div y2 y3))) = x0) -> (x0 -> ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y3 y1) y2) y3) = (Nat.add y1 (Nat.div y2 y3))) /\ ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add y2 (Nat.mul y1 y3)) y3) = (Nat.add (Nat.div y2 y3) y1)) /\ (forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add y2 (Nat.mul y3 y1)) y3) = (Nat.add (Nat.div y2 y3) y1)))) = y0) -> ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y1 y3) y2) y3) = (Nat.add y1 (Nat.div y2 y3))) -> (forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y3 y1) y2) y3) = (Nat.add y1 (Nat.div y2 y3))) /\ ((forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add y2 (Nat.mul y1 y3)) y3) = (Nat.add (Nat.div y2 y3) y1)) /\ (forall y1 : nat, forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (Nat.div (Nat.add y2 (Nat.mul y3 y1)) y3) = (Nat.add (Nat.div y2 y3) y1)))) = (x0 -> y0)) x1.
Definition term84 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.mul x0 x1) x2.
Definition term230 (x0 : nat) (x1 : nat) := (x1 = (NUMERAL 0)) \/ ((x0 = (Nat.add (Nat.mul (Nat.div x0 x1) x1) (Nat.modulo x0 x1))) /\ (Peano.lt (Nat.modulo x0 x1) x1)).
Definition term296 (x0 : nat) (x1 : nat) := (Peano.lt (Nat.modulo x0 x1) x1) -> False.
Definition term3 (x0 : nat) (x1 : nat) := fun y0 : nat => (Nat.add (Nat.add x0 x1) y0) = (Nat.add x0 (Nat.add x1 y0)).
Definition term188 (x0 : nat) (x1 : nat) (x2 : nat) := and ((Nat.add (Nat.mul x0 x2) x1) = (Nat.add (Nat.mul (Nat.add x0 (Nat.div x1 x2)) x2) (Nat.modulo x1 x2))).
Definition term225 (x0 : nat) := ~ (~ (x0 = (NUMERAL 0))).
Definition term279 (x0 : nat) (x1 : nat) := ~ (~ (x0 = x1)).
Definition term45 (x0 : Prop) := (fun y0 : Prop => (y0 = True) \/ (y0 = False)) x0.
Definition term222 (x0 : nat) := forall y0 : nat, (~ (y0 = (NUMERAL 0))) -> (x0 = (Nat.add (Nat.mul (Nat.div x0 y0) y0) (Nat.modulo x0 y0))) /\ (Peano.lt (Nat.modulo x0 y0) y0).
Definition term168 (x0 : nat) (x1 : nat) := forall y0 : nat, (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul y0 x1)) y0) = (Nat.add (Nat.div x0 y0) x1).
Definition term149 (x0 : nat) (x1 : nat) := forall y0 : nat, (~ (y0 = (NUMERAL 0))) -> (Nat.div (Nat.add x0 (Nat.mul x1 y0)) y0) = (Nat.add (Nat.div x0 y0) x1).
Definition term266 (x0 : nat) (x1 : nat) := or (~ (x0 = x1)).
Definition term88 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.div (Nat.add x0 (Nat.mul x1 x2)) x2.
Definition term77 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add x0 (Nat.div x1 x2).
Definition term239 := fun y0 : nat => forall y1 : nat, ((y1 = (NUMERAL 0)) \/ (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1)))) /\ ((y1 = (NUMERAL 0)) \/ (Peano.lt (Nat.modulo y0 y1) y1)).
Definition term233 := fun y0 : nat => forall y1 : nat, (y1 = (NUMERAL 0)) \/ ((y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1)).
Definition term223 := fun y0 : nat => forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (y0 = (Nat.add (Nat.mul (Nat.div y0 y1) y1) (Nat.modulo y0 y1))) /\ (Peano.lt (Nat.modulo y0 y1) y1).
Definition term213 (x0 : nat) := fun y0 : nat => forall y1 : nat, (~ (x0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y1 x0) y0) = (Nat.add (Nat.mul y1 x0) (Nat.add (Nat.mul (Nat.div y0 x0) x0) (Nat.modulo y0 x0)))) /\ (Peano.lt (Nat.modulo y0 x0) x0))) -> ~ (forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (y2 = (Nat.add (Nat.mul (Nat.div y2 y3) y3) (Nat.modulo y2 y3))) /\ (Peano.lt (Nat.modulo y2 y3) y3)).
Definition term212 (x0 : nat) := fun y0 : nat => forall y1 : nat, (~ (x0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y1 x0) y0) = (Nat.add (Nat.mul y1 x0) (Nat.add (Nat.mul (Nat.div y0 x0) x0) (Nat.modulo y0 x0)))) /\ (Peano.lt (Nat.modulo y0 x0) x0))) -> (forall y2 : nat, forall y3 : nat, (~ (y3 = (NUMERAL 0))) -> (y2 = (Nat.add (Nat.mul (Nat.div y2 y3) y3) (Nat.modulo y2 y3))) /\ (Peano.lt (Nat.modulo y2 y3) y3)) -> False.
Definition term169 (x0 : nat) := fun y0 : nat => forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add y0 (Nat.mul y1 x0)) y1) = (Nat.add (Nat.div y0 y1) x0).
Definition term150 (x0 : nat) := fun y0 : nat => forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add y0 (Nat.mul x0 y1)) y1) = (Nat.add (Nat.div y0 y1) x0).
Definition term132 (x0 : nat) := fun y0 : nat => forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y1 x0) y0) y1) = (Nat.add x0 (Nat.div y0 y1)).
Definition term100 (x0 : nat) := fun y0 : nat => forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add y0 (Nat.mul x0 y1)) y1) = (Nat.add x0 (Nat.div y0 y1)).
Definition term99 (x0 : nat) := fun y0 : nat => forall y1 : nat, (~ (y1 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul x0 y1) y0) y1) = (Nat.add x0 (Nat.div y0 y1)).
Definition term7 (x0 : nat) := fun y0 : nat => forall y1 : nat, (Nat.add (Nat.add x0 y0) y1) = (Nat.add x0 (Nat.add y0 y1)).
Definition term256 (x0 : Prop) := x0 -> ~ x0.
Definition term217 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y2 y0) y1) = (Nat.add (Nat.mul y2 y0) (Nat.add (Nat.mul (Nat.div y1 y0) y0) (Nat.modulo y1 y0)))) /\ (Peano.lt (Nat.modulo y1 y0) y0))) -> ~ (forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (y3 = (Nat.add (Nat.mul (Nat.div y3 y4) y4) (Nat.modulo y3 y4))) /\ (Peano.lt (Nat.modulo y3 y4) y4)).
Definition term216 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y0 = (NUMERAL 0))) -> (~ (((Nat.add (Nat.mul y2 y0) y1) = (Nat.add (Nat.mul y2 y0) (Nat.add (Nat.mul (Nat.div y1 y0) y0) (Nat.modulo y1 y0)))) /\ (Peano.lt (Nat.modulo y1 y0) y0))) -> (forall y3 : nat, forall y4 : nat, (~ (y4 = (NUMERAL 0))) -> (y3 = (Nat.add (Nat.mul (Nat.div y3 y4) y4) (Nat.modulo y3 y4))) /\ (Peano.lt (Nat.modulo y3 y4) y4)) -> False.
Definition term171 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y2 y0)) y2) = (Nat.add (Nat.div y1 y2) y0).
Definition term152 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add (Nat.div y1 y2) y0).
Definition term134 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y2 y0) y1) y2) = (Nat.add y0 (Nat.div y1 y2)).
Definition term104 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add y1 (Nat.mul y0 y2)) y2) = (Nat.add y0 (Nat.div y1 y2)).
Definition term103 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (~ (y2 = (NUMERAL 0))) -> (Nat.div (Nat.add (Nat.mul y0 y2) y1) y2) = (Nat.add y0 (Nat.div y1 y2)).
Definition term11 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (Nat.add (Nat.add y0 y1) y2) = (Nat.add y0 (Nat.add y1 y2)).
Definition term10 := fun y0 : nat => forall y1 : nat, forall y2 : nat, (Nat.add y0 (Nat.add y1 y2)) = (Nat.add (Nat.add y0 y1) y2).
Definition term295 (x0 : nat) (x1 : nat) := (~ (Peano.lt (Nat.modulo x0 x1) x1)) -> Peano.lt (Nat.modulo x0 x1) x1.
Definition term85 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add x0 (Nat.mul x1 x2).
