Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term198 := or (exists y0 : int, exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))).
Definition term106 := or (exists y0 : int, exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))).
Definition term2 (x0 : int) (x1 : int) := ~ ((int_le x0 x1) = (int_lt x0 (int_add x1 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term17 := fun y0 : int => forall y1 : int, (int_le y0 y1) = (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0))))).
Definition term277 := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term296 := real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term208 := exists y0 : int, (fun y1 : int => exists y2 : int, (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0)))) y0.
Definition term204 := exists y0 : int, (fun y1 : int => exists y2 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0.
Definition term108 := exists y0 : int, (fun y1 : int => exists y2 : int, (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))))) y0.
Definition term103 := exists y0 : int, (fun y1 : int => exists y2 : int, (real_le (real_of_int y1) (real_of_int y2)) /\ (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1))) y0.
Definition term6 (x0 : int -> Prop) := exists y0 : int, ~ (x0 y0).
Definition term241 := real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term129 (x0 : nat) := real_div (real_neg (real_of_num x0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term5 (x0 : int -> Prop) := ~ (all x0).
Definition term140 := Nat.pow (BIT1 0) (NUMERAL (BIT0 (BIT1 0))).
Definition term73 (x0 : int) (x1 : int) := (fun y0 : int => (real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) x1.
Definition term262 (x0 : int) := real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)).
Definition term166 (x0 : int) := real_add (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term114 (x0 : int) (x1 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1).
Definition term50 (x0 : int) (x1 : int) := real_le (real_of_int (int_add x0 (int_of_num (NUMERAL (BIT1 0))))) (real_of_int (int_add x1 (int_of_num (NUMERAL (BIT1 0))))).
Definition term173 (x0 : nat) (x1 : nat) := real_lt (real_of_num x0) (real_of_num x1).
Definition term112 (x0 : int) (x1 : int) := real_sub (real_of_int x0) (real_of_int x1).
Definition term122 (x0 : int) (x1 : int) := real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term272 := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term59 (x0 : int) := fun y0 : int => ((real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) \/ ((real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term152 (x0 : int) (x1 : int) := real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term181 := real_add (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term273 := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term128 (x0 : nat) := real_neg (real_of_num x0).
Definition term63 (x0 : Prop) := ~ (~ x0).
Definition term118 := real_of_num (NUMERAL 0).
Definition term68 (x0 : int -> Prop) (x1 : int -> Prop) := (exists y0 : int, x0 y0) \/ (exists y0 : int, x1 y0).
Definition term87 (x0 : int) := exists y0 : int, (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0))))).
Definition term301 := (~ (~ (exists y0 : int, exists y1 : int, ((real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ ((real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0))))))))) -> False.
Definition term271 := ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term179 := ((real_mul (real_add (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term275 := real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term183 := real_mul (real_add (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term120 (x0 : int) (x1 : int) := real_ge (real_sub (real_of_int x0) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL 0)).
Definition term116 (x0 : int) (x1 : int) := real_ge (real_sub (real_of_int x0) (real_of_int x1)).
Definition term115 (x0 : int) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0).
Definition term66 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := (exists y0 : a0, x0 y0) \/ (exists y0 : a0, x1 y0).
Definition term292 := real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term246 (x0 : int) (x1 : int) := (real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))).
Definition term215 := fun y0 : int => ((fun y1 : int => exists y2 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0) \/ ((fun y1 : int => exists y2 : int, (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0)))) y0).
Definition term99 := fun y0 : int => ((fun y1 : int => exists y2 : int, (real_le (real_of_int y1) (real_of_int y2)) /\ (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1))) y0) \/ ((fun y1 : int => exists y2 : int, (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term154 (x0 : int) (x1 : int) := and (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))).
Definition term18 (x0 : int) := (fun y0 : int => forall y1 : int, (int_le y0 y1) = (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0)))))) x0.
Definition term260 (x0 : int) (x1 : int) := real_add (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)).
Definition term134 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term52 (x0 : int) (x1 : int) := and (~ (int_le x0 x1)).
Definition term264 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term32 (x0 : int) := real_of_int (int_add x0 (int_of_num (NUMERAL (BIT1 0)))).
Definition term12 (x0 : int) := fun y0 : int => ~ ((fun y1 : int => (int_le x0 y1) = (int_lt x0 (int_add y1 (int_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term191 (x0 : int) (x1 : int) := real_ge (real_sub (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term150 (x0 : int) (x1 : int) := real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term182 (x0 : nat) := real_add (real_of_num x0) (real_neg (real_of_num x0)).
Definition term297 (x0 : nat) (x1 : nat) := real_le (real_of_num x0) (real_neg (real_of_num x1)).
Definition term45 (x0 : int) (x1 : int) := and (real_le (real_of_int x0) (real_of_int x1)).
Definition term269 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term268 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term177 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term172 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term124 (x0 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term189 := real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term56 (x0 : int) (x1 : int) := or ((int_le x0 x1) /\ (~ (int_lt x0 (int_add x1 (int_of_num (NUMERAL (BIT1 0))))))).
Definition term113 (x0 : int) (x1 : int) := real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)).
Definition term234 (x0 : int) := fun y0 : int => ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0)))).
Definition term261 (x0 : int) (x1 : int) := real_add (real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) (real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))) (real_of_int x1)).
Definition term162 (x0 : int) (x1 : int) := real_add (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term29 (x0 : int) (x1 : int) := real_le (real_of_int (int_add x0 (int_of_num (NUMERAL (BIT1 0))))) (real_of_int x1).
Definition term47 (x0 : int) (x1 : int) := (real_le (real_of_int x1) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)).
Definition term19 (x0 : int) := forall y0 : int, (int_le x0 y0) = (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0))))).
Definition term144 := real_neg (real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)))).
Definition term48 (x0 : int) (x1 : int) := ~ (int_le x0 x1).
Definition term254 (x0 : int) (x1 : int) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term286 (x0 : int) (x1 : int) := real_ge (real_add (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1))).
Definition term130 := real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term71 (x0 : int) := fun y0 : int => (real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)).
Definition term51 (x0 : int) (x1 : int) := real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0)))).
Definition term289 := real_le (real_of_num (NUMERAL 0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term58 (x0 : int) (x1 : int) := ((real_le (real_of_int x0) (real_of_int x1)) /\ (real_le (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) \/ ((real_le (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term20 (x0 : int) := ~ ((fun y0 : int => forall y1 : int, (int_le y0 y1) = (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0)))))) x0).
Definition term148 (x0 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)).
Definition term229 (x0 : int) (x1 : int) := or ((fun y0 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) x1).
Definition term74 (x0 : int) (x1 : int) := or ((fun y0 : int => (real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) x1).
Definition term175 := Peano.lt (NUMERAL 0) (NUMERAL (BIT1 0)).
Definition term235 (x0 : int) := exists y0 : int, ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0)))).
Definition term60 (x0 : int) := exists y0 : int, ((real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) \/ ((real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term14 (x0 : int) := exists y0 : int, ((int_le x0 y0) /\ (~ (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0))))))) \/ ((~ (int_le x0 y0)) /\ (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term33 (x0 : int) := real_add (real_of_int x0) (real_of_int (int_of_num (NUMERAL (BIT1 0)))).
Definition term75 (x0 : int) (x1 : int) := (fun y0 : int => (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))))) x1.
Definition term291 := real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term43 (x0 : int) (x1 : int) := real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1).
Definition term206 (x0 : int) := (fun y0 : int => exists y1 : int, (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))) x0.
Definition term202 (x0 : int) := (fun y0 : int => exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) x0.
Definition term97 (x0 : int) := (fun y0 : int => exists y1 : int, (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))) x0.
Definition term95 (x0 : int) := (fun y0 : int => exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) x0.
Definition term295 := real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term121 (x0 : int) (x1 : int) := real_sub (real_of_int x0) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0)))).
Definition term167 (x0 : int) := real_add (real_of_int x0) (real_add (real_of_num (NUMERAL (BIT1 0))) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term270 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term178 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term267 := real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term9 (x0 : int) := fun y0 : int => (int_le x0 y0) = (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0))))).
Definition term190 (x0 : int) := real_add (real_of_int x0) (real_of_num (NUMERAL 0)).
Definition term111 (x0 : int) (x1 : int) := real_ge (real_sub (real_of_int x0) (real_of_int x1)) (real_of_num (NUMERAL 0)).
Definition term290 := real_le (real_of_num (NUMERAL 0)).
Definition term53 (x0 : int) (x1 : int) := and (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)).
Definition term30 (x0 : int) (x1 : int) := real_of_int (int_add x0 x1).
Definition term298 (x0 : nat) (x1 : nat) := (x0 = (NUMERAL 0)) /\ (x1 = (NUMERAL 0)).
Definition term216 := fun y0 : int => (exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (exists y1 : int, (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))).
Definition term89 := fun y0 : int => (exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ (exists y1 : int, (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term239 := real_lt (real_of_num (NUMERAL 0)).
Definition term217 := exists y0 : int, (exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (exists y1 : int, (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))).
Definition term90 := exists y0 : int, (exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ (exists y1 : int, (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term39 (x0 : int) := real_add (real_of_int x0).
Definition term252 (x0 : int) (x1 : int) := (real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term300 := and ((NUMERAL 0) = (NUMERAL 0)).
Definition term165 (x0 : int) (x1 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_add (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term263 (x0 : int) := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0).
Definition term35 (x0 : nat) := real_of_int (int_of_num x0).
Definition term186 := real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term274 (x0 : nat) := real_add (real_neg (real_of_num x0)) (real_of_num x0).
Definition term141 := Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)).
Definition term224 (x0 : int) (x1 : int) := (fun y0 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0)))) x1.
Definition term220 (x0 : int) (x1 : int) := (fun y0 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) x1.
Definition term27 (x0 : int) (x1 : int) := int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x1.
Definition term31 (x0 : int) (x1 : int) := real_add (real_of_int x0) (real_of_int x1).
Definition term302 := ((~ (~ (exists y0 : int, exists y1 : int, ((real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ ((real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0))))))))) -> False) -> ~ (exists y0 : int, exists y1 : int, ((real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ ((real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0))))))).
Definition term265 := real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term199 := (exists y0 : int, exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (exists y0 : int, exists y1 : int, (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))).
Definition term110 := (exists y0 : int, exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ (exists y0 : int, exists y1 : int, (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term299 := ((NUMERAL 0) = (NUMERAL 0)) /\ ((NUMERAL (BIT1 0)) = (NUMERAL 0)).
Definition term145 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term218 (x0 : int) := (exists y0 : int, (fun y1 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0) \/ (exists y0 : int, (fun y1 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))) y0).
Definition term200 := (exists y0 : int, (fun y1 : int => exists y2 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0) \/ (exists y0 : int, (fun y1 : int => exists y2 : int, (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0)))) y0).
Definition term92 := (exists y0 : int, (fun y1 : int => exists y2 : int, (real_le (real_of_int y1) (real_of_int y2)) /\ (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1))) y0) \/ (exists y0 : int, (fun y1 : int => exists y2 : int, (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term70 (x0 : int) := (exists y0 : int, (fun y1 : int => (real_le (real_of_int x0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) y0) \/ (exists y0 : int, (fun y1 : int => (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term174 := real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term49 (x0 : int) (x1 : int) := int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) (int_add x1 (int_of_num (NUMERAL (BIT1 0)))).
Definition term283 (x0 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x0).
Definition term101 := @eq Prop (exists y0 : int, (exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ (exists y1 : int, (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0))))))).
Definition term100 := @eq Prop (exists y0 : int, ((fun y1 : int => exists y2 : int, (real_le (real_of_int y1) (real_of_int y2)) /\ (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1))) y0) \/ ((fun y1 : int => exists y2 : int, (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))))) y0)).
Definition term79 (x0 : int) := @eq Prop (exists y0 : int, ((real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) \/ ((real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0))))))).
Definition term78 (x0 : int) := @eq Prop (exists y0 : int, ((fun y1 : int => (real_le (real_of_int x0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) y0) \/ ((fun y1 : int => (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))) y0)).
Definition term230 (x0 : int) (x1 : int) := or ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))).
Definition term279 (x0 : int) := real_add (real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))).
Definition term214 (x0 : int) := (exists y0 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (exists y0 : int, (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0)))).
Definition term88 (x0 : int) := (exists y0 : int, (real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) \/ (exists y0 : int, (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term42 (x0 : int) := real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term82 (x0 : int) := exists y0 : int, (real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)).
Definition term259 (x0 : int) (x1 : int) := real_ge (real_add (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1))) (real_of_num (NUMERAL 0)).
Definition term142 (x0 : nat) (x1 : nat) := real_mul (real_neg (real_of_num x0)) (real_of_num x1).
Definition term160 (x0 : int) (x1 : int) := real_ge (real_sub (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL 0)).
Definition term7 (x0 : int) := ~ (forall y0 : int, (int_le x0 y0) = (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term281 (x0 : int) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_neg (real_of_num (NUMERAL (BIT1 0))))) (real_of_int x0).
Definition term257 (x0 : real) (x1 : real) := ((real_ge x0 (real_of_num (NUMERAL 0))) /\ (real_ge x1 (real_of_num (NUMERAL 0)))) -> real_ge (real_add x0 x1) (real_of_num (NUMERAL 0)).
Definition term247 (x0 : real) (x1 : real) := ((real_gt x0 (real_of_num (NUMERAL 0))) /\ (real_ge x1 (real_of_num (NUMERAL 0)))) -> real_ge (real_mul x0 x1) (real_of_num (NUMERAL 0)).
Definition term226 (x0 : int) := exists y0 : int, (fun y1 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))) y0.
Definition term222 (x0 : int) := exists y0 : int, (fun y1 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0.
Definition term86 (x0 : int) := exists y0 : int, (fun y1 : int => (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))) y0.
Definition term81 (x0 : int) := exists y0 : int, (fun y1 : int => (real_le (real_of_int x0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) y0.
Definition term146 := real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term1 := forall y0 : int, forall y1 : int, (int_le y0 y1) = (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0))))).
Definition term138 := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term287 := real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term249 (x0 : int) (x1 : int) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1))) (real_of_num (NUMERAL 0)).
Definition term151 (x0 : int) (x1 : int) := real_ge (real_sub (real_of_int x0) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term117 (x0 : int) (x1 : int) := real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)).
Definition term243 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term55 (x0 : int) (x1 : int) := (real_le (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term294 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term255 (x0 : int) (x1 : int) := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term28 (x0 : int) := int_add x0 (int_of_num (NUMERAL (BIT1 0))).
Definition term176 := S (Nat.add 0 0).
Definition term131 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term164 (x0 : int) (x1 : int) := real_add (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term13 (x0 : int) := fun y0 : int => ((int_le x0 y0) /\ (~ (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0))))))) \/ ((~ (int_le x0 y0)) /\ (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term0 := ~ (~ (forall y0 : int, forall y1 : int, (int_le y0 y1) = (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0))))))).
Definition term119 (x0 : int) (x1 : int) := real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0)).
Definition term125 := real_neg (real_of_num (NUMERAL (BIT1 0))).
Definition term133 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term233 (x0 : int) := fun y0 : int => ((fun y1 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0) \/ ((fun y1 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))) y0).
Definition term77 (x0 : int) := fun y0 : int => ((fun y1 : int => (real_le (real_of_int x0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) y0) \/ ((fun y1 : int => (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term155 (x0 : int) (x1 : int) := (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term303 := ~ (exists y0 : int, exists y1 : int, ((real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ ((real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0))))))).
Definition term184 := real_mul (real_of_num (NUMERAL 0)).
Definition term169 := real_add (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term41 (x0 : int) := real_le (real_of_int (int_add x0 (int_of_num (NUMERAL (BIT1 0))))).
Definition term26 (x0 : int) (x1 : int) := ~ (int_lt x0 (int_add x1 (int_of_num (NUMERAL (BIT1 0))))).
Definition term15 := ~ (forall y0 : int, forall y1 : int, (int_le y0 y1) = (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term136 (x0 : nat) (x1 : nat) := real_mul (real_of_num x0) (real_of_num x1).
Definition term188 := real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term11 (x0 : int) (x1 : int) := ~ ((fun y0 : int => (int_le x0 y0) = (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0)))))) x1).
Definition term213 (x0 : int) := ((fun y0 : int => exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) x0) \/ ((fun y0 : int => exists y1 : int, (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))) x0).
Definition term98 (x0 : int) := ((fun y0 : int => exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) x0) \/ ((fun y0 : int => exists y1 : int, (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))) x0).
Definition term127 := real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term54 (x0 : int) (x1 : int) := (~ (int_le x0 x1)) /\ (int_lt x0 (int_add x1 (int_of_num (NUMERAL (BIT1 0))))).
Definition term258 (x0 : int) (x1 : int) := ((real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0)))) -> real_ge (real_add (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1))) (real_of_num (NUMERAL 0)).
Definition term253 (x0 : int) (x1 : int) := ((real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) -> real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term248 (x0 : int) (x1 : int) := ((real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0)))) -> real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1))) (real_of_num (NUMERAL 0)).
Definition term256 (x0 : int) (x1 : int) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))).
Definition term143 (x0 : nat) (x1 : nat) := real_neg (real_of_num (Nat.mul x0 x1)).
Definition term251 (x0 : int) (x1 : int) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1))).
Definition term24 (x0 : int) (x1 : int) := real_le (real_of_int x0) (real_of_int x1).
Definition term44 (x0 : int) (x1 : int) := and (int_le x0 x1).
Definition term211 (x0 : int) := or ((fun y0 : int => exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) x0).
Definition term96 (x0 : int) := or ((fun y0 : int => exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) x0).
Definition term57 (x0 : int) (x1 : int) := or ((real_le (real_of_int x1) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1))).
Definition term67 (x0 : int -> Prop) (x1 : int -> Prop) := exists y0 : int, (x0 y0) \/ (x1 y0).
Definition term231 (x0 : int) (x1 : int) := ((fun y0 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) x1) \/ ((fun y0 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0)))) x1).
Definition term76 (x0 : int) (x1 : int) := ((fun y0 : int => (real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) x1) \/ ((fun y0 : int => (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))))) x1).
Definition term225 (x0 : int) := fun y0 : int => (fun y1 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))) y0.
Definition term221 (x0 : int) := fun y0 : int => (fun y1 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0.
Definition term85 (x0 : int) := fun y0 : int => (fun y1 : int => (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))) y0.
Definition term80 (x0 : int) := fun y0 : int => (fun y1 : int => (real_le (real_of_int x0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) y0.
Definition term139 := real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0))).
Definition term147 (x0 : real) := real_div x0 (real_of_num (NUMERAL (BIT1 0))).
Definition term187 (x0 : nat) := real_mul (real_of_num (NUMERAL 0)) (real_of_num x0).
Definition term37 := real_of_num (NUMERAL (BIT1 0)).
Definition term244 := real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term192 (x0 : int) (x1 : int) := and (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term10 (x0 : int) (x1 : int) := (fun y0 : int => (int_le x0 y0) = (int_lt x0 (int_add y0 (int_of_num (NUMERAL (BIT1 0)))))) x1.
Definition term212 (x0 : int) := or (exists y0 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))).
Definition term84 (x0 : int) := or (exists y0 : int, (real_le (real_of_int x0) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))).
Definition term285 := real_add (real_of_num (NUMERAL 0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term219 (x0 : int) := exists y0 : int, ((fun y1 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0) \/ ((fun y1 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))) y0).
Definition term201 := exists y0 : int, ((fun y1 : int => exists y2 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0) \/ ((fun y1 : int => exists y2 : int, (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0)))) y0).
Definition term91 := exists y0 : int, ((fun y1 : int => exists y2 : int, (real_le (real_of_int y1) (real_of_int y2)) /\ (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1))) y0) \/ ((fun y1 : int => exists y2 : int, (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term69 (x0 : int) := exists y0 : int, ((fun y1 : int => (real_le (real_of_int x0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) y0) \/ ((fun y1 : int => (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term168 := real_add (real_of_num (NUMERAL (BIT1 0))).
Definition term170 := real_add (real_of_num (NUMERAL (BIT1 0))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term149 (x0 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term293 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term242 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term163 (x0 : int) := real_add (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term3 (x0 : int) (x1 : int) := ((int_le x0 x1) /\ (~ (int_lt x0 (int_add x1 (int_of_num (NUMERAL (BIT1 0))))))) \/ ((~ (int_le x0 x1)) /\ (int_lt x0 (int_add x1 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term232 (x0 : int) (x1 : int) := ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0)))).
Definition term282 (x0 : int) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term36 := real_of_int (int_of_num (NUMERAL (BIT1 0))).
Definition term72 (x0 : int) := fun y0 : int => (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0))))).
Definition term223 (x0 : int) := or (exists y0 : int, (fun y1 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0).
Definition term205 := or (exists y0 : int, (fun y1 : int => exists y2 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0).
Definition term105 := or (exists y0 : int, (fun y1 : int => exists y2 : int, (real_le (real_of_int y1) (real_of_int y2)) /\ (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1))) y0).
Definition term83 (x0 : int) := or (exists y0 : int, (fun y1 : int => (real_le (real_of_int x0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) y0).
Definition term137 (x0 : nat) (x1 : nat) := real_of_num (Nat.mul x0 x1).
Definition term16 := exists y0 : int, ~ ((fun y1 : int => forall y2 : int, (int_le y1 y2) = (int_lt y1 (int_add y2 (int_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term8 (x0 : int) := exists y0 : int, ~ ((fun y1 : int => (int_le x0 y1) = (int_lt x0 (int_add y1 (int_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term237 := exists y0 : int, exists y1 : int, ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))).
Definition term197 := exists y0 : int, exists y1 : int, (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))).
Definition term159 := exists y0 : int, exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term109 := exists y0 : int, exists y1 : int, (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term104 := exists y0 : int, exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)).
Definition term62 := exists y0 : int, exists y1 : int, ((real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ ((real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term23 := exists y0 : int, exists y1 : int, ((int_le y0 y1) /\ (~ (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0))))))) \/ ((~ (int_le y0 y1)) /\ (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term236 := fun y0 : int => exists y1 : int, ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))).
Definition term196 := fun y0 : int => exists y1 : int, (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))).
Definition term158 := fun y0 : int => exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term94 := fun y0 : int => exists y1 : int, (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term93 := fun y0 : int => exists y1 : int, (real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)).
Definition term61 := fun y0 : int => exists y1 : int, ((real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ ((real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))).
Definition term22 := fun y0 : int => exists y1 : int, ((int_le y0 y1) /\ (~ (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0))))))) \/ ((~ (int_le y0 y1)) /\ (int_lt y0 (int_add y1 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term153 (x0 : int) (x1 : int) := real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)).
Definition term40 (x0 : int) := real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0))).
Definition term180 := real_add (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term193 (x0 : int) (x1 : int) := (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))).
Definition term195 (x0 : int) := exists y0 : int, (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))).
Definition term157 (x0 : int) := exists y0 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term161 (x0 : int) (x1 : int) := real_sub (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x1) (real_of_num (NUMERAL (BIT1 0)))).
Definition term278 (x0 : int) := real_mul (real_of_num (NUMERAL 0)) (real_of_int x0).
Definition term123 (x0 : int) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term207 := fun y0 : int => (fun y1 : int => exists y2 : int, (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0)))) y0.
Definition term203 := fun y0 : int => (fun y1 : int => exists y2 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0.
Definition term107 := fun y0 : int => (fun y1 : int => exists y2 : int, (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))))) y0.
Definition term102 := fun y0 : int => (fun y1 : int => exists y2 : int, (real_le (real_of_int y1) (real_of_int y2)) /\ (real_le (real_add (real_of_int y2) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1))) y0.
Definition term240 := real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term266 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term171 := real_add (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term126 (x0 : nat) := real_div (real_of_num x0) (real_of_num (NUMERAL (BIT1 0))).
Definition term64 := ~ (~ (exists y0 : int, exists y1 : int, ((real_le (real_of_int y0) (real_of_int y1)) /\ (real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0))) \/ ((real_le (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) /\ (real_le (real_add (real_of_int y0) (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int y1) (real_of_num (NUMERAL (BIT1 0)))))))).
Definition term288 := real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0)).
Definition term132 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term194 (x0 : int) := fun y0 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))).
Definition term156 (x0 : int) := fun y0 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term25 (x0 : int) (x1 : int) := ~ (int_lt x0 x1).
Definition term280 := real_add (real_of_num (NUMERAL 0)).
Definition term46 (x0 : int) (x1 : int) := (int_le x0 x1) /\ (~ (int_lt x0 (int_add x1 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term65 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := exists y0 : a0, (x0 y0) \/ (x1 y0).
Definition term276 := real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0))).
Definition term185 := real_mul (real_add (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0))).
Definition term34 := int_of_num (NUMERAL (BIT1 0)).
Definition term284 (x0 : int) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x0)).
Definition term250 (x0 : int) (x1 : int) := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)).
Definition term38 := NUMERAL (BIT1 0).
Definition term238 := real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0)).
Definition term135 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term21 := fun y0 : int => ~ ((fun y1 : int => forall y2 : int, (int_le y1 y2) = (int_lt y1 (int_add y2 (int_of_num (NUMERAL (BIT1 0)))))) y0).
Definition term245 := real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term4 (x0 : int) (x1 : int) := int_lt x0 (int_add x1 (int_of_num (NUMERAL (BIT1 0)))).
Definition term228 (x0 : int) := @eq Prop ((exists y0 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (exists y0 : int, (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y0)) (real_of_num (NUMERAL 0))))).
Definition term227 (x0 : int) := @eq Prop ((exists y0 : int, (fun y1 : int => (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0) \/ (exists y0 : int, (fun y1 : int => (real_ge (real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int y1)) (real_of_num (NUMERAL 0)))) y0)).
Definition term210 := @eq Prop ((exists y0 : int, exists y1 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (exists y0 : int, exists y1 : int, (real_ge (real_add (real_of_int y0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y0)) (real_of_int y1)) (real_of_num (NUMERAL 0))))).
Definition term209 := @eq Prop ((exists y0 : int, (fun y1 : int => exists y2 : int, (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) y0) \/ (exists y0 : int, (fun y1 : int => exists y2 : int, (real_ge (real_add (real_of_int y1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y2)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int y1)) (real_of_int y2)) (real_of_num (NUMERAL 0)))) y0)).
