Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term102 := fun y0 : int => forall y1 : int, ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ ((div y0 y1) = (int_of_num (NUMERAL 0)))) /\ ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ ((rem y0 y1) = y0)).
Definition term81 := fun y0 : int => forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))))).
Definition term80 := fun y0 : int => forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)).
Definition term34 := fun y0 : int => forall y1 : int, ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ ((y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))).
Definition term41 (x0 : int -> Prop) := exists y0 : int, ~ (x0 y0).
Definition term40 (x0 : int -> Prop) := ~ (all x0).
Definition term123 := (~ False) -> False.
Definition term4 := (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False.
Definition term57 (x0 : int) (x1 : int) := (fun y0 : int => (~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0))) x1.
Definition term14 (x0 : int) := @COND Prop (x0 = (int_of_num (NUMERAL 0))).
Definition term115 (x0 : Prop) := ~ (~ x0).
Definition term13 := int_of_num (NUMERAL 0).
Definition term122 (x0 : int) := ((rem x0 (int_of_num (NUMERAL 0))) = x0) -> False.
Definition term104 (x0 : int) := (fun y0 : int => forall y1 : int, ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ ((div y0 y1) = (int_of_num (NUMERAL 0)))) /\ ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ ((rem y0 y1) = y0))) x0.
Definition term84 (x0 : int) := (fun y0 : int => forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) x0.
Definition term82 (x0 : int) := (fun y0 : int => forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) x0.
Definition term32 (x0 : int) := forall y0 : int, ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0))) /\ ((y0 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0)))))).
Definition term0 (x0 : Prop) := (~ x0) -> False.
Definition term21 (x0 : int) (x1 : int) := ((x1 = (int_of_num (NUMERAL 0))) = False) -> (@COND Prop (x1 = (int_of_num (NUMERAL 0))) (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))))) = ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))))).
Definition term24 (x0 : int) (x1 : int) := ((x0 = (int_of_num (NUMERAL 0))) = True) -> (@COND Prop (x0 = (int_of_num (NUMERAL 0))) (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1)) ((int_le (int_of_num (NUMERAL 0)) (rem x1 x0)) /\ ((int_lt (rem x1 x0) (int_abs x0)) /\ (x1 = (int_add (int_mul (div x1 x0) x0) (rem x1 x0)))))) = (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1)).
Definition term101 (x0 : int) := forall y0 : int, ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ ((div x0 y0) = (int_of_num (NUMERAL 0)))) /\ ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ ((rem x0 y0) = x0)).
Definition term93 := and (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))).
Definition term110 (x0 : int) (x1 : int) := ((rem x0 x1) = x0) \/ (~ (x1 = (int_of_num (NUMERAL 0)))).
Definition term20 (x0 : int) (x1 : int) := @COND Prop False (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))))).
Definition term107 := (~ ((int_of_num (NUMERAL 0)) = (int_of_num (NUMERAL 0)))) -> (int_of_num (NUMERAL 0)) = (int_of_num (NUMERAL 0)).
Definition term44 (x0 : int) := ~ ((fun y0 : int => (rem y0 (int_of_num (NUMERAL 0))) = y0) x0).
Definition term79 := (forall y0 : int, (fun y1 : int => forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) \/ (((div y1 y2) = (int_of_num (NUMERAL 0))) /\ ((rem y1 y2) = y1))) y0) /\ (forall y0 : int, (fun y1 : int => forall y2 : int, (y2 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ ((int_lt (rem y1 y2) (int_abs y2)) /\ (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2)))))) y0).
Definition term54 (x0 : int) := (forall y0 : int, (fun y1 : int => (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y1) = x0))) y0) /\ (forall y0 : int, (fun y1 : int => (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y1)) /\ ((int_lt (rem x0 y1) (int_abs y1)) /\ (x0 = (int_add (int_mul (div x0 y1) y1) (rem x0 y1)))))) y0).
Definition term113 (x0 : Prop) (x1 : Prop) := (~ x0) -> x1.
Definition term105 (x0 : int) (x1 : int) := (fun y0 : int => ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ ((div x0 y0) = (int_of_num (NUMERAL 0)))) /\ ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ ((rem x0 y0) = x0))) x1.
Definition term119 (x0 : int) (x1 : int) := (x0 = (int_of_num (NUMERAL 0))) -> (rem x1 x0) = x1.
Definition term75 (x0 : int) := (forall y0 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0))) /\ (forall y0 : int, (y0 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0)))))).
Definition term100 (x0 : int) := fun y0 : int => ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ ((div x0 y0) = (int_of_num (NUMERAL 0)))) /\ ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ ((rem x0 y0) = x0)).
Definition term98 (x0 : int) (x1 : int) := ((~ (x0 = (int_of_num (NUMERAL 0)))) \/ ((div x1 x0) = (int_of_num (NUMERAL 0)))) /\ ((~ (x0 = (int_of_num (NUMERAL 0)))) \/ ((rem x1 x0) = x1)).
Definition term118 (x0 : int) := imp (x0 = (int_of_num (NUMERAL 0))).
Definition term109 (x0 : Prop) := (~ x0) -> x0.
Definition term108 := ~ ((int_of_num (NUMERAL 0)) = (int_of_num (NUMERAL 0))).
Definition term114 (x0 : int) (x1 : int) := (~ (~ (x0 = (int_of_num (NUMERAL 0))))) -> (rem x1 x0) = x1.
Definition term117 (x0 : int) := imp (~ (~ (x0 = (int_of_num (NUMERAL 0))))).
Definition term30 (x0 : int) := fun y0 : int => ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0))) /\ ((y0 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0)))))).
Definition term50 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := (forall y0 : a0, x0 y0) /\ (forall y0 : a0, x1 y0).
Definition term72 (x0 : int) := fun y0 : int => (fun y1 : int => (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y1)) /\ ((int_lt (rem x0 y1) (int_abs y1)) /\ (x0 = (int_add (int_mul (div x0 y1) y1) (rem x0 y1)))))) y0.
Definition term67 (x0 : int) := fun y0 : int => (fun y1 : int => (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y1) = x0))) y0.
Definition term61 (x0 : int) (x1 : int) := (fun y0 : int => (y0 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0)))))) x1.
Definition term69 (x0 : int) := forall y0 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0)).
Definition term97 := (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ (forall y0 : int, forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))).
Definition term83 (x0 : int) := and ((fun y0 : int => forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) x0).
Definition term92 := and (forall y0 : int, (fun y1 : int => forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) \/ (((div y1 y2) = (int_of_num (NUMERAL 0))) /\ ((rem y1 y2) = y1))) y0).
Definition term70 (x0 : int) := and (forall y0 : int, (fun y1 : int => (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y1) = x0))) y0).
Definition term88 := @eq Prop (forall y0 : int, (forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ (forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))))))).
Definition term87 := @eq Prop (forall y0 : int, ((fun y1 : int => forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) \/ (((div y1 y2) = (int_of_num (NUMERAL 0))) /\ ((rem y1 y2) = y1))) y0) /\ ((fun y1 : int => forall y2 : int, (y2 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ ((int_lt (rem y1 y2) (int_abs y2)) /\ (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2)))))) y0)).
Definition term66 (x0 : int) := @eq Prop (forall y0 : int, ((~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0))) /\ ((y0 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))))))).
Definition term65 (x0 : int) := @eq Prop (forall y0 : int, ((fun y1 : int => (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y1) = x0))) y0) /\ ((fun y1 : int => (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y1)) /\ ((int_lt (rem x0 y1) (int_abs y1)) /\ (x0 = (int_add (int_mul (div x0 y1) y1) (rem x0 y1)))))) y0)).
Definition term16 (x0 : int) (x1 : int) := @COND Prop (x0 = (int_of_num (NUMERAL 0))) (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1)).
Definition term112 (x0 : int) (x1 : int) := @eq Prop (((rem x0 x1) = x0) \/ (~ (x1 = (int_of_num (NUMERAL 0))))).
Definition term124 := (forall y0 : int, forall y1 : int, ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ ((y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))))))) -> False.
Definition term8 := (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False.
Definition term28 (x0 : int) (x1 : int) := ((~ (x1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0))) /\ ((x1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))))).
Definition term60 (x0 : int) (x1 : int) := and ((~ (x0 = (int_of_num (NUMERAL 0)))) \/ (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1))).
Definition term19 (x0 : int) (x1 : int) := @COND Prop (x1 = (int_of_num (NUMERAL 0))) (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))))).
Definition term38 := fun y0 : int => (rem y0 (int_of_num (NUMERAL 0))) = y0.
Definition term6 := (((~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False) -> (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False) -> (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False.
Definition term111 (x0 : int) (x1 : int) := @eq Prop ((~ (x0 = (int_of_num (NUMERAL 0)))) \/ ((rem x1 x0) = x1)).
Definition term78 := forall y0 : int, ((fun y1 : int => forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) \/ (((div y1 y2) = (int_of_num (NUMERAL 0))) /\ ((rem y1 y2) = y1))) y0) /\ ((fun y1 : int => forall y2 : int, (y2 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ ((int_lt (rem y1 y2) (int_abs y2)) /\ (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2)))))) y0).
Definition term53 (x0 : int) := forall y0 : int, ((fun y1 : int => (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y1) = x0))) y0) /\ ((fun y1 : int => (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y1)) /\ ((int_lt (rem x0 y1) (int_abs y1)) /\ (x0 = (int_add (int_mul (div x0 y1) y1) (rem x0 y1)))))) y0).
Definition term106 (x0 : int) (x1 : int) := (~ (x0 = (int_of_num (NUMERAL 0)))) \/ ((rem x1 x0) = x1).
Definition term77 := forall y0 : int, (forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ (forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))).
Definition term121 (x0 : int) := (~ ((rem x0 (int_of_num (NUMERAL 0))) = x0)) -> (rem x0 (int_of_num (NUMERAL 0))) = x0.
Definition term1 := forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0.
Definition term58 (x0 : int) (x1 : int) := (~ (x0 = (int_of_num (NUMERAL 0)))) \/ (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1)).
Definition term48 := exists y0 : int, ~ ((rem y0 (int_of_num (NUMERAL 0))) = y0).
Definition term103 := forall y0 : int, forall y1 : int, ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ ((div y0 y1) = (int_of_num (NUMERAL 0)))) /\ ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ ((rem y0 y1) = y0)).
Definition term96 := forall y0 : int, forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))))).
Definition term91 := forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)).
Definition term35 := forall y0 : int, forall y1 : int, ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ ((y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))).
Definition term10 := forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))))).
Definition term45 (x0 : int) := ~ ((rem x0 (int_of_num (NUMERAL 0))) = x0).
Definition term64 (x0 : int) := fun y0 : int => ((fun y1 : int => (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y1) = x0))) y0) /\ ((fun y1 : int => (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y1)) /\ ((int_lt (rem x0 y1) (int_abs y1)) /\ (x0 = (int_add (int_mul (div x0 y1) y1) (rem x0 y1)))))) y0).
Definition term29 (x0 : int) := fun y0 : int => @COND Prop (y0 = (int_of_num (NUMERAL 0))) (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))))).
Definition term2 := (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> False.
Definition term76 := fun y0 : int => (forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ (forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))).
Definition term74 (x0 : int) := forall y0 : int, (y0 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))))).
Definition term46 := fun y0 : int => ~ ((fun y1 : int => (rem y1 (int_of_num (NUMERAL 0))) = y1) y0).
Definition term23 (x0 : int) (x1 : int) := @COND Prop True (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))))).
Definition term95 := forall y0 : int, (fun y1 : int => forall y2 : int, (y2 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ ((int_lt (rem y1 y2) (int_abs y2)) /\ (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2)))))) y0.
Definition term90 := forall y0 : int, (fun y1 : int => forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) \/ (((div y1 y2) = (int_of_num (NUMERAL 0))) /\ ((rem y1 y2) = y1))) y0.
Definition term99 (x0 : int) := ~ (x0 = (int_of_num (NUMERAL 0))).
Definition term36 := ~ (forall y0 : int, forall y1 : int, ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ ((y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))))))).
Definition term9 := ~ (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))).
Definition term59 (x0 : int) (x1 : int) := and ((fun y0 : int => (~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0))) x1).
Definition term17 (x0 : int) (x1 : int) := @COND Prop False (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1)).
Definition term51 (x0 : int -> Prop) (x1 : int -> Prop) := forall y0 : int, (x0 y0) /\ (x1 y0).
Definition term47 := fun y0 : int => ~ ((rem y0 (int_of_num (NUMERAL 0))) = y0).
Definition term55 (x0 : int) := fun y0 : int => (~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0)).
Definition term22 (x0 : int) (x1 : int) := @COND Prop True (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1)).
Definition term26 (x0 : Prop) (x1 : Prop) (x2 : Prop) (x3 : Prop) := (((x2 = False) -> x0 = x3) /\ ((x2 = True) -> x0 = x1)) -> x0 = (((~ x2) \/ x1) /\ (x2 \/ x3)).
Definition term71 (x0 : int) := and (forall y0 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0))).
Definition term85 (x0 : int) := ((fun y0 : int => forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) x0) /\ ((fun y0 : int => forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) x0).
Definition term18 (x0 : int) (x1 : int) := (int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))).
Definition term15 (x0 : int) (x1 : int) := ((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1).
Definition term120 (x0 : int) := ((int_of_num (NUMERAL 0)) = (int_of_num (NUMERAL 0))) -> (rem x0 (int_of_num (NUMERAL 0))) = x0.
Definition term62 (x0 : int) (x1 : int) := (x1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))))).
Definition term52 (x0 : int -> Prop) (x1 : int -> Prop) := (forall y0 : int, x0 y0) /\ (forall y0 : int, x1 y0).
Definition term39 := (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> ~ (forall y0 : int, forall y1 : int, ((~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0))) /\ ((y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))))))).
Definition term12 := (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> ~ (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))).
Definition term116 (x0 : int) := ~ (~ (x0 = (int_of_num (NUMERAL 0)))).
Definition term86 := fun y0 : int => ((fun y1 : int => forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) \/ (((div y1 y2) = (int_of_num (NUMERAL 0))) /\ ((rem y1 y2) = y1))) y0) /\ ((fun y1 : int => forall y2 : int, (y2 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ ((int_lt (rem y1 y2) (int_abs y2)) /\ (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2)))))) y0).
Definition term37 (x0 : int) := rem x0 (int_of_num (NUMERAL 0)).
Definition term63 (x0 : int) (x1 : int) := ((fun y0 : int => (~ (y0 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0))) x1) /\ ((fun y0 : int => (y0 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0)))))) x1).
Definition term49 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := forall y0 : a0, (x0 y0) /\ (x1 y0).
Definition term42 := exists y0 : int, ~ ((fun y1 : int => (rem y1 (int_of_num (NUMERAL 0))) = y1) y0).
Definition term43 (x0 : int) := (fun y0 : int => (rem y0 (int_of_num (NUMERAL 0))) = y0) x0.
Definition term56 (x0 : int) := fun y0 : int => (y0 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))))).
Definition term5 := ((~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False) -> (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False.
Definition term3 := ~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0).
Definition term25 (x0 : int) (x1 : int) := (((x0 = (int_of_num (NUMERAL 0))) = False) -> (@COND Prop (x0 = (int_of_num (NUMERAL 0))) (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1)) ((int_le (int_of_num (NUMERAL 0)) (rem x1 x0)) /\ ((int_lt (rem x1 x0) (int_abs x0)) /\ (x1 = (int_add (int_mul (div x1 x0) x0) (rem x1 x0)))))) = ((int_le (int_of_num (NUMERAL 0)) (rem x1 x0)) /\ ((int_lt (rem x1 x0) (int_abs x0)) /\ (x1 = (int_add (int_mul (div x1 x0) x0) (rem x1 x0)))))) /\ (((x0 = (int_of_num (NUMERAL 0))) = True) -> (@COND Prop (x0 = (int_of_num (NUMERAL 0))) (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1)) ((int_le (int_of_num (NUMERAL 0)) (rem x1 x0)) /\ ((int_lt (rem x1 x0) (int_abs x0)) /\ (x1 = (int_add (int_mul (div x1 x0) x0) (rem x1 x0)))))) = (((div x1 x0) = (int_of_num (NUMERAL 0))) /\ ((rem x1 x0) = x1))).
Definition term7 := (((~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False) -> (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False) -> ((~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False) -> (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)) -> (forall y0 : int, forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))))) -> False.
Definition term73 (x0 : int) := forall y0 : int, (fun y1 : int => (y1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y1)) /\ ((int_lt (rem x0 y1) (int_abs y1)) /\ (x0 = (int_add (int_mul (div x0 y1) y1) (rem x0 y1)))))) y0.
Definition term68 (x0 : int) := forall y0 : int, (fun y1 : int => (~ (y1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y1) = x0))) y0.
Definition term27 (x0 : int) (x1 : int) := ((((x1 = (int_of_num (NUMERAL 0))) = False) -> (@COND Prop (x1 = (int_of_num (NUMERAL 0))) (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))))) = ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))))) /\ (((x1 = (int_of_num (NUMERAL 0))) = True) -> (@COND Prop (x1 = (int_of_num (NUMERAL 0))) (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))))) = (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0)))) -> (@COND Prop (x1 = (int_of_num (NUMERAL 0))) (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))))) = (((~ (x1 = (int_of_num (NUMERAL 0)))) \/ (((div x0 x1) = (int_of_num (NUMERAL 0))) /\ ((rem x0 x1) = x0))) /\ ((x1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ ((int_lt (rem x0 x1) (int_abs x1)) /\ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))))))).
Definition term94 := fun y0 : int => (fun y1 : int => forall y2 : int, (y2 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ ((int_lt (rem y1 y2) (int_abs y2)) /\ (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2)))))) y0.
Definition term89 := fun y0 : int => (fun y1 : int => forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) \/ (((div y1 y2) = (int_of_num (NUMERAL 0))) /\ ((rem y1 y2) = y1))) y0.
Definition term31 (x0 : int) := forall y0 : int, @COND Prop (y0 = (int_of_num (NUMERAL 0))) (((div x0 y0) = (int_of_num (NUMERAL 0))) /\ ((rem x0 y0) = x0)) ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ ((int_lt (rem x0 y0) (int_abs y0)) /\ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))))).
Definition term11 := imp (~ (forall y0 : int, (rem y0 (int_of_num (NUMERAL 0))) = y0)).
Definition term33 := fun y0 : int => forall y1 : int, @COND Prop (y1 = (int_of_num (NUMERAL 0))) (((div y0 y1) = (int_of_num (NUMERAL 0))) /\ ((rem y0 y1) = y0)) ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ ((int_lt (rem y0 y1) (int_abs y1)) /\ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))))).
