Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term132 (x0 : int) (x1 : int) := ~ ((int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL 0))) (int_mul x1 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term237 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL 0)) (int_mul (div x0 x1) x1).
Definition term216 (x0 : int) := int_mul x0 (int_of_num (NUMERAL 0)).
Definition term81 := fun y0 : int => forall y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) -> (((int_mul y1 (div y0 y1)) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y0 y1) y1) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))).
Definition term70 := fun y0 : int => forall y1 : int, (((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) /\ (((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0)).
Definition term6 := fun y0 : int => forall y1 : int, (int_divides y1 y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0))).
Definition term148 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))).
Definition term98 (x0 : int -> Prop) := exists y0 : int, ~ (x0 y0).
Definition term129 (x0 : int) (x1 : int) := (~ ((int_mul x0 (div x1 x0)) = x1)) /\ (~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0)))).
Definition term97 (x0 : int -> Prop) := ~ (all x0).
Definition term188 (x0 : int) (x1 : int) (x2 : int) := (fun y0 : int => forall y1 : int, ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y0)) = (int_add x1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y1)))) x2.
Definition term180 := (forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4)))) -> forall y0 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4))).
Definition term235 (x0 : int) (x1 : int) := (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))) /\ (~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0)))).
Definition term123 (x0 : int) (x1 : int) := ((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ ((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))).
Definition term181 (x0 : int) := (fun y0 : int => (~ (y0 = (int_of_num (NUMERAL 0)))) -> forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4)))) x0.
Definition term294 (x0 : int) (x1 : int) := (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))))) -> False.
Definition term254 (x0 : int) (x1 : int) := int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))).
Definition term104 (x0 : int) := fun y0 : int => ((int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0) /\ (((((int_mul y0 (div x0 y0)) = x0) /\ (~ ((rem x0 y0) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y0 (div x0 y0)) = x0)) /\ ((rem x0 y0) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div x0 y0) y0) = x0) /\ (~ ((rem x0 y0) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 y0) y0) = x0)) /\ ((rem x0 y0) = (int_of_num (NUMERAL 0)))))).
Definition term62 (x0 : int) := @eq Prop ((forall y0 : int, ((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0)) /\ (forall y0 : int, ((int_mul (div x0 y0) y0) = x0) = (int_divides y0 x0))).
Definition term61 (x0 : int) := @eq Prop ((forall y0 : int, (fun y1 : int => ((int_mul y1 (div x0 y1)) = x0) = (int_divides y1 x0)) y0) /\ (forall y0 : int, (fun y1 : int => ((int_mul (div x0 y1) y1) = x0) = (int_divides y1 x0)) y0)).
Definition term40 := @eq Prop ((forall y0 : int, forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) /\ (forall y0 : int, forall y1 : int, ((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0))).
Definition term39 := @eq Prop ((forall y0 : int, (fun y1 : int => forall y2 : int, ((int_mul y2 (div y1 y2)) = y1) = (int_divides y2 y1)) y0) /\ (forall y0 : int, (fun y1 : int => forall y2 : int, ((int_mul (div y1 y2) y2) = y1) = (int_divides y2 y1)) y0)).
Definition term264 (x0 : int) (x1 : int) := int_add (rem x0 x1) (int_of_num (NUMERAL 0)).
Definition term243 (x0 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)).
Definition term202 := int_add (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)).
Definition term277 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1))).
Definition term138 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL 0)) (rem x0 x1).
Definition term236 (x0 : int) (x1 : int) := ~ ((int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))).
Definition term105 (x0 : int) := exists y0 : int, ((int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0) /\ (((((int_mul y0 (div x0 y0)) = x0) /\ (~ ((rem x0 y0) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y0 (div x0 y0)) = x0)) /\ ((rem x0 y0) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div x0 y0) y0) = x0) /\ (~ ((rem x0 y0) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 y0) y0) = x0)) /\ ((rem x0 y0) = (int_of_num (NUMERAL 0)))))).
Definition term72 (x0 : int) (x1 : int) := @eq Prop ((int_mul x0 (div x1 x0)) = x1).
Definition term169 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := forall y0 : int, (~ (x3 = (int_of_num (NUMERAL 0)))) -> ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 y0))).
Definition term0 := int_of_num (NUMERAL 0).
Definition term186 (x0 : int) (x1 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y1)) = (int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2)))) x1.
Definition term164 (x0 : int) (x1 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, forall y3 : int, (~ (x0 = (int_of_num (NUMERAL 0)))) -> ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul x0 y2)) = (int_add y1 (int_mul x0 y3)))) x1.
Definition term225 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x0 x1)))).
Definition term240 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1).
Definition term241 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1)).
Definition term275 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term233 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term222 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x1 (div x0 x1)) (rem x0 x1)).
Definition term265 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))).
Definition term107 (x0 : int) := (fun y0 : int => forall y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) -> (((int_mul y1 (div y0 y1)) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y0 y1) y1) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0))))) x0.
Definition term33 (x0 : int) := (fun y0 : int => forall y1 : int, ((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0)) x0.
Definition term26 (x0 : int) := (fun y0 : int => forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) x0.
Definition term9 (x0 : int) := (fun y0 : int => forall y1 : int, (int_divides y1 y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))) x0.
Definition term171 (x0 : int) (x1 : int) (x2 : int) (x3 : int) (x4 : int) := (~ (x3 = (int_of_num (NUMERAL 0)))) -> ((x0 = x2) /\ (~ (x1 = x4))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 x4))).
Definition term149 (x0 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) x0).
Definition term141 (x0 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0).
Definition term286 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1))))).
Definition term230 (x0 : int) (x1 : int) := @eq int (int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1))).
Definition term142 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (rem x0 x1)).
Definition term184 (x0 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2)) = (int_add y1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y3)))) x0.
Definition term162 (x0 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4)))) x0.
Definition term191 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := ((x0 = x2) /\ (~ (x1 = x3))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) x1)) = (int_add x2 (int_mul (int_of_num (NUMERAL (BIT1 0))) x3))).
Definition term173 (x0 : int) (x1 : int) (x2 : int) (x3 : int) (x4 : int) := ((x0 = x2) /\ (~ (x1 = x4))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 x4))).
Definition term69 (x0 : int) := forall y0 : int, (((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0)) /\ (((int_mul (div x0 y0) y0) = x0) = (int_divides y0 x0)).
Definition term287 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1))))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))))).
Definition term271 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))))).
Definition term103 (x0 : int) := fun y0 : int => ~ ((fun y1 : int => ((int_add (int_mul (div x0 y1) y1) (rem x0 y1)) = x0) -> (((int_mul y1 (div x0 y1)) = x0) = ((rem x0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 y1) y1) = x0) = ((rem x0 y1) = (int_of_num (NUMERAL 0))))) y0).
Definition term32 := and (forall y0 : int, forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)).
Definition term267 (x0 : int) (x1 : int) := int_add x0 (int_mul x1 (div x0 x1)).
Definition term282 (x0 : int) (x1 : int) := (((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1))))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1)))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0)))) /\ (~ ((int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))) -> ~ ((int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1))))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1)))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term248 (x0 : int) (x1 : int) := (((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1)))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x0 x1) x1))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0)))) /\ (~ ((int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))) -> ~ ((int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x0 x1) x1))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term192 (x0 : int) (x1 : int) := (((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x1) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x1 x0)))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (rem x1 x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0)))))) /\ (~ ((int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL 0))) (int_mul x1 (int_of_num (NUMERAL (BIT1 0)))))))) -> ~ ((int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x1) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x1 x0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (rem x1 x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL 0))) (int_mul x1 (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term179 := forall y0 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4))).
Definition term154 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x0 x1))).
Definition term218 (x0 : int) (x1 : int) := int_add (int_mul (int_mul x1 (div x0 x1)) (int_of_num (NUMERAL (BIT1 0)))).
Definition term288 (x0 : int) (x1 : int) := @eq int (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1))))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))).
Definition term273 (x0 : int) (x1 : int) := @eq int (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))).
Definition term229 (x0 : int) (x1 : int) := @eq int (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x1) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x1 x0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0)))))).
Definition term48 (x0 : int) := (forall y0 : int, (fun y1 : int => ((int_mul y1 (div x0 y1)) = x0) = (int_divides y1 x0)) y0) /\ (forall y0 : int, (fun y1 : int => ((int_mul (div x0 y1) y1) = x0) = (int_divides y1 x0)) y0).
Definition term22 := (forall y0 : int, (fun y1 : int => forall y2 : int, ((int_mul y2 (div y1 y2)) = y1) = (int_divides y2 y1)) y0) /\ (forall y0 : int, (fun y1 : int => forall y2 : int, ((int_mul (div y1 y2) y2) = y1) = (int_divides y2 y1)) y0).
Definition term193 (x0 : int) (x1 : int) := int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0))).
Definition term44 (x0 : int) := (forall y0 : int, ((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0)) /\ (forall y0 : int, ((int_mul (div x0 y0) y0) = x0) = (int_divides y0 x0)).
Definition term91 (x0 : int) (x1 : int) := ((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term17 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := (fun y0 : a0 -> Prop => ((forall y1 : a0, x0 y1) /\ (forall y1 : a0, y0 y1)) = (forall y1 : a0, (x0 y1) /\ (y0 y1))) x1.
Definition term166 (x0 : int) (x1 : int) (x2 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, (~ (x1 = (int_of_num (NUMERAL 0)))) -> ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul x1 y1)) = (int_add y0 (int_mul x1 y2)))) x2.
Definition term281 (x0 : int) (x1 : int) := ((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1))))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1)))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0)))) /\ (~ ((int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))))))).
Definition term247 (x0 : int) (x1 : int) := ((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1)))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x0 x1) x1))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0)))) /\ (~ ((int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))))))).
Definition term156 (x0 : int) (x1 : int) := ((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x1) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x1 x0)))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (rem x1 x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0)))))) /\ (~ ((int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL 0))) (int_mul x1 (int_of_num (NUMERAL (BIT1 0))))))).
Definition term234 (x0 : int) (x1 : int) := ~ ((rem x0 x1) = (int_of_num (NUMERAL 0))).
Definition term205 (x0 : int) (x1 : int) := int_add (int_mul x1 (div x0 x1)) (rem x0 x1).
Definition term80 (x0 : int) := forall y0 : int, ((int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0) -> (((int_mul y0 (div x0 y0)) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 y0) y0) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0)))).
Definition term245 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1))).
Definition term92 (x0 : int) (x1 : int) := ~ ((((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 x1) x1) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term145 (x0 : int) := int_mul (int_of_num (NUMERAL 0)) x0.
Definition term228 (x0 : int) (x1 : int) := int_add (int_add x0 (rem x0 x1)) (int_mul x1 (div x0 x1)).
Definition term108 (x0 : int) := ~ ((fun y0 : int => forall y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) -> (((int_mul y1 (div y0 y1)) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y0 y1) y1) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0))))) x0).
Definition term217 (x0 : int) (x1 : int) := int_mul (int_mul x1 (div x0 x1)) (int_of_num (NUMERAL (BIT1 0))).
Definition term272 (x0 : int) (x1 : int) := int_add (int_add (int_mul x1 (div x0 x1)) x0) (rem x0 x1).
Definition term2 (x0 : int) := fun y0 : int => (int_divides y0 x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0))).
Definition term18 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := (forall y0 : a0, x0 y0) /\ (forall y0 : a0, x1 y0).
Definition term214 (x0 : int) (x1 : int) := int_add x0 (rem x0 x1).
Definition term270 (x0 : int) (x1 : int) := int_add (int_add (int_mul x0 (div x1 x0)) x1).
Definition term253 (x0 : int) (x1 : int) := int_mul (rem x0 x1) (int_of_num (NUMERAL 0)).
Definition term269 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1)))).
Definition term200 (x0 : int) := int_add (int_of_num (NUMERAL 0)) x0.
Definition term263 (x0 : int) (x1 : int) := int_add (rem x0 x1).
Definition term276 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1))).
Definition term151 (x0 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))).
Definition term143 (x0 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))).
Definition term90 (x0 : int) (x1 : int) := (~ (((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ (~ (((int_mul (div x0 x1) x1) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term206 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x1 (div x0 x1)) (rem x0 x1)).
Definition term170 (x0 : int) (x1 : int) (x2 : int) (x3 : int) (x4 : int) := (fun y0 : int => (~ (x3 = (int_of_num (NUMERAL 0)))) -> ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 y0)))) x4.
Definition term250 (x0 : int) (x1 : int) := int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))).
Definition term38 := (forall y0 : int, forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) /\ (forall y0 : int, forall y1 : int, ((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0)).
Definition term41 (x0 : int) := and ((fun y0 : int => forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) x0).
Definition term135 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1)).
Definition term56 (x0 : int) := and (forall y0 : int, (fun y1 : int => ((int_mul y1 (div x0 y1)) = x0) = (int_divides y1 x0)) y0).
Definition term31 := and (forall y0 : int, (fun y1 : int => forall y2 : int, ((int_mul y2 (div y1 y2)) = y1) = (int_divides y2 y1)) y0).
Definition term244 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x0 x1) x1))).
Definition term283 (x0 : int) (x1 : int) := ~ ((int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1))))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1)))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term251 (x0 : int) (x1 : int) := ~ ((int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul (div x0 x1) x1)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x0 x1) x1))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term195 (x0 : int) (x1 : int) := ~ ((int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x1) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x1 x0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (rem x1 x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL 0))) (int_mul x1 (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term262 (x0 : int) (x1 : int) := int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))).
Definition term134 := int_mul (int_of_num (NUMERAL (BIT1 0))).
Definition term168 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := (fun y0 : int => forall y1 : int, (~ (x2 = (int_of_num (NUMERAL 0)))) -> ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul x2 y0)) = (int_add x1 (int_mul x2 y1)))) x3.
Definition term112 (x0 : int) (x1 : int) := (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))).
Definition term152 (x0 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))).
Definition term190 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := (fun y0 : int => ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) x1)) = (int_add x2 (int_mul (int_of_num (NUMERAL (BIT1 0))) y0)))) x3.
Definition term51 (x0 : int) := fun y0 : int => ((int_mul (div x0 y0) y0) = x0) = (int_divides y0 x0).
Definition term50 (x0 : int) := fun y0 : int => ((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0).
Definition term266 (x0 : int) (x1 : int) := int_add (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1)).
Definition term211 (x0 : int) (x1 : int) := int_add (int_add (int_mul x0 (div x1 x0)) (rem x1 x0)) x1.
Definition term118 (x0 : int) (x1 : int) := (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term114 (x0 : int) (x1 : int) := (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term295 := (exists y0 : int, exists y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) /\ (((((int_mul y1 (div y0 y1)) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y1 (div y0 y1)) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div y0 y1) y1) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div y0 y1) y1) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))))) -> False.
Definition term117 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term113 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term144 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1)).
Definition term96 (x0 : int) (x1 : int) := ~ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) -> (((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 x1) x1) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term199 := int_add (int_of_num (NUMERAL 0)).
Definition term197 (x0 : int) (x1 : int) := int_mul (int_mul x1 (div x0 x1)) (int_of_num (NUMERAL 0)).
Definition term258 (x0 : int) (x1 : int) := int_add (int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1))).
Definition term147 := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0)).
Definition term296 (x0 : Prop) (x1 : Prop) := (x0 -> False) -> ((~ x1) = x0) -> x1.
Definition term66 (x0 : int) (x1 : int) := (((int_mul x0 (div x1 x0)) = x1) = (int_divides x0 x1)) /\ (((int_mul (div x1 x0) x0) = x1) = (int_divides x0 x1)).
Definition term207 (x0 : int) (x1 : int) := int_add (int_add (int_mul x1 (div x0 x1)) (rem x0 x1)).
Definition term34 (x0 : int) := forall y0 : int, ((int_mul (div x0 y0) y0) = x0) = (int_divides y0 x0).
Definition term27 (x0 : int) := forall y0 : int, ((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0).
Definition term274 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term124 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term238 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x0 x1) x1)).
Definition term280 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x0 (div x1 x0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) x1)).
Definition term49 (x0 : int) := forall y0 : int, ((fun y1 : int => ((int_mul y1 (div x0 y1)) = x0) = (int_divides y1 x0)) y0) /\ ((fun y1 : int => ((int_mul (div x0 y1) y1) = x0) = (int_divides y1 x0)) y0).
Definition term23 := forall y0 : int, ((fun y1 : int => forall y2 : int, ((int_mul y2 (div y1 y2)) = y1) = (int_divides y2 y1)) y0) /\ ((fun y1 : int => forall y2 : int, ((int_mul (div y1 y2) y2) = y1) = (int_divides y2 y1)) y0).
Definition term1 (x0 : int) := fun y0 : int => ((rem x0 y0) = (int_of_num (NUMERAL 0))) = (int_divides y0 x0).
Definition term93 (x0 : int) (x1 : int) := and ((int_add (int_mul (div x1 x0) x0) (rem x1 x0)) = x1).
Definition term198 (x0 : int) (x1 : int) := int_add (int_mul (int_mul x1 (div x0 x1)) (int_of_num (NUMERAL 0))).
Definition term255 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))))).
Definition term246 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x1 x0) x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) x1)).
Definition term99 (x0 : int) := ~ (forall y0 : int, ((int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0) -> (((int_mul y0 (div x0 y0)) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 y0) y0) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0))))).
Definition term219 (x0 : int) (x1 : int) := int_add (int_mul x1 (div x0 x1)) (int_of_num (NUMERAL 0)).
Definition term160 := ~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0))).
Definition term122 (x0 : int) (x1 : int) := or ((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))).
Definition term213 (x0 : int) (x1 : int) := int_add (rem x1 x0) x1.
Definition term47 := forall y0 : int, (forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) /\ (forall y1 : int, ((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0)).
Definition term16 (a0 : Type') (x0 : a0 -> Prop) := forall y0 : a0 -> Prop, ((forall y1 : a0, x0 y1) /\ (forall y1 : a0, y0 y1)) = (forall y1 : a0, (x0 y1) /\ (y0 y1)).
Definition term278 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1)))).
Definition term189 (x0 : int) (x1 : int) (x2 : int) := forall y0 : int, ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) x1)) = (int_add x2 (int_mul (int_of_num (NUMERAL (BIT1 0))) y0))).
Definition term174 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := forall y0 : int, ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 y0))).
Definition term150 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x0 x1)).
Definition term292 (x0 : int) (x1 : int) := ((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))))) = False) -> ~ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))))).
Definition term187 (x0 : int) (x1 : int) := forall y0 : int, forall y1 : int, ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y0)) = (int_add x1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y1))).
Definition term185 (x0 : int) := forall y0 : int, forall y1 : int, forall y2 : int, ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y1)) = (int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2))).
Definition term183 := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2)) = (int_add y1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y3))).
Definition term177 (x0 : int) := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul x0 y2)) = (int_add y1 (int_mul x0 y3))).
Definition term176 (x0 : int) (x1 : int) := forall y0 : int, forall y1 : int, forall y2 : int, ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul x1 y1)) = (int_add y0 (int_mul x1 y2))).
Definition term175 (x0 : int) (x1 : int) (x2 : int) := forall y0 : int, forall y1 : int, ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul x2 y0)) = (int_add x1 (int_mul x2 y1))).
Definition term167 (x0 : int) (x1 : int) (x2 : int) := forall y0 : int, forall y1 : int, (~ (x2 = (int_of_num (NUMERAL 0)))) -> ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul x2 y0)) = (int_add x1 (int_mul x2 y1))).
Definition term165 (x0 : int) (x1 : int) := forall y0 : int, forall y1 : int, forall y2 : int, (~ (x1 = (int_of_num (NUMERAL 0)))) -> ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul x1 y1)) = (int_add y0 (int_mul x1 y2))).
Definition term163 (x0 : int) := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, (~ (x0 = (int_of_num (NUMERAL 0)))) -> ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul x0 y2)) = (int_add y1 (int_mul x0 y3))).
Definition term161 := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4))).
Definition term82 := forall y0 : int, forall y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) -> (((int_mul y1 (div y0 y1)) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y0 y1) y1) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))).
Definition term71 := forall y0 : int, forall y1 : int, (((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) /\ (((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0)).
Definition term37 := forall y0 : int, forall y1 : int, ((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0).
Definition term30 := forall y0 : int, forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0).
Definition term8 := forall y0 : int, forall y1 : int, (int_divides y1 y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0))).
Definition term7 := forall y0 : int, forall y1 : int, ((rem y0 y1) = (int_of_num (NUMERAL 0))) = (int_divides y1 y0).
Definition term115 (x0 : int) (x1 : int) := ((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term15 (a0 : Type') (x0 : a0 -> Prop) := (fun y0 : a0 -> Prop => forall y1 : a0 -> Prop, ((forall y2 : a0, y0 y2) /\ (forall y2 : a0, y1 y2)) = (forall y2 : a0, (y0 y2) /\ (y1 y2))) x0.
Definition term125 (x0 : int) (x1 : int) := ~ ((int_mul (div x1 x0) x0) = x1).
Definition term285 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1)))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))).
Definition term259 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x0 x1) x1))) (int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))).
Definition term67 (x0 : int) := fun y0 : int => ((fun y1 : int => ((int_mul y1 (div x0 y1)) = x0) = (int_divides y1 x0)) y0) /\ ((fun y1 : int => ((int_mul (div x0 y1) y1) = x0) = (int_divides y1 x0)) y0).
Definition term158 := S (Nat.add 0 0).
Definition term279 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0)) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1)))).
Definition term284 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (int_mul x0 (div x1 x0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) x1))).
Definition term257 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (int_mul (div x1 x0) x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) x1))).
Definition term95 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))).
Definition term101 (x0 : int) (x1 : int) := (fun y0 : int => ((int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0) -> (((int_mul y0 (div x0 y0)) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 y0) y0) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0))))) x1.
Definition term119 (x0 : int) (x1 : int) := ((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term46 := fun y0 : int => (forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) /\ (forall y1 : int, ((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0)).
Definition term293 (x0 : int) (x1 : int) := ~ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))))).
Definition term224 (x0 : int) := int_add x0 (int_of_num (NUMERAL 0)).
Definition term242 (x0 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) x0) (int_mul (int_of_num (NUMERAL (BIT1 0))) x0).
Definition term239 (x0 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x0) (int_mul (int_of_num (NUMERAL 0)) x0).
Definition term25 := fun y0 : int => forall y1 : int, ((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0).
Definition term24 := fun y0 : int => forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0).
Definition term5 := fun y0 : int => forall y1 : int, ((rem y0 y1) = (int_of_num (NUMERAL 0))) = (int_divides y1 y0).
Definition term194 (x0 : int) (x1 : int) := int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL 0))) (int_mul x1 (int_of_num (NUMERAL (BIT1 0)))).
Definition term13 (x0 : int) (x1 : int) := (fun y0 : int => (int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0) x1.
Definition term79 (x0 : int) := fun y0 : int => ((int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0) -> (((int_mul y0 (div x0 y0)) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 y0) y0) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0)))).
Definition term130 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := (~ (x0 = x1)) /\ (~ (x2 = x3)).
Definition term291 (x0 : int) (x1 : int) := (~ (((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ ((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))))) -> (((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ ((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))))) = False.
Definition term232 (x0 : int) (x1 : int) := (~ ((int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1))) = (int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1))))) -> ((int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1))) = (int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1)))) = False.
Definition term249 (x0 : int) (x1 : int) := int_add (int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))).
Definition term36 := forall y0 : int, (fun y1 : int => forall y2 : int, ((int_mul (div y1 y2) y2) = y1) = (int_divides y2 y1)) y0.
Definition term29 := forall y0 : int, (fun y1 : int => forall y2 : int, ((int_mul y2 (div y1 y2)) = y1) = (int_divides y2 y1)) y0.
Definition term172 (x0 : int) := ~ (x0 = (int_of_num (NUMERAL 0))).
Definition term136 (x0 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) x0.
Definition term121 (x0 : int) (x1 : int) := or (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))).
Definition term153 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) (int_mul (int_of_num (NUMERAL 0)) (rem x0 x1))).
Definition term11 (x0 : int) := (fun y0 : int => forall y1 : int, (int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) x0.
Definition term178 (x0 : int) := (~ (x0 = (int_of_num (NUMERAL 0)))) -> forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul x0 y2)) = (int_add y1 (int_mul x0 y3))).
Definition term10 (x0 : int) (x1 : int) := (fun y0 : int => (int_divides y0 x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0)))) x1.
Definition term83 := ~ (forall y0 : int, forall y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) -> (((int_mul y1 (div y0 y1)) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y0 y1) y1) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0))))).
Definition term88 (x0 : int) (x1 : int) := or (~ (((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term4 (x0 : int) := forall y0 : int, (int_divides y0 x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0))).
Definition term58 (x0 : int) (x1 : int) := int_mul (div x0 x1) x1.
Definition term63 (x0 : int) (x1 : int) := and ((fun y0 : int => ((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0)) x1).
Definition term102 (x0 : int) (x1 : int) := ~ ((fun y0 : int => ((int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0) -> (((int_mul y0 (div x0 y0)) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 y0) y0) = x0) = ((rem x0 y0) = (int_of_num (NUMERAL 0))))) x1).
Definition term21 (x0 : int -> Prop) (x1 : int -> Prop) := forall y0 : int, (x0 y0) /\ (x1 y0).
Definition term223 (x0 : int) (x1 : int) := int_add (int_of_num (NUMERAL 0)) (rem x0 x1).
Definition term289 (x0 : int) (x1 : int) := (((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ ((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))))) -> False.
Definition term12 (x0 : int) := forall y0 : int, (int_add (int_mul (div x0 y0) y0) (rem x0 y0)) = x0.
Definition term196 (x0 : int) := int_mul x0 (int_of_num (NUMERAL (BIT1 0))).
Definition term127 (x0 : int) (x1 : int) := @eq int (int_mul x1 (div x0 x1)).
Definition term42 (x0 : int) := and (forall y0 : int, ((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0)).
Definition term43 (x0 : int) := ((fun y0 : int => forall y1 : int, ((int_mul y1 (div y0 y1)) = y0) = (int_divides y1 y0)) x0) /\ ((fun y0 : int => forall y1 : int, ((int_mul (div y0 y1) y1) = y0) = (int_divides y1 y0)) x0).
Definition term73 (x0 : int) (x1 : int) := and (((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term120 (x0 : int) (x1 : int) := (~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))).
Definition term116 (x0 : int) (x1 : int) := (~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))).
Definition term64 (x0 : int) (x1 : int) := and (((int_mul x0 (div x1 x0)) = x1) = (int_divides x0 x1)).
Definition term140 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x0 x1) x1) (rem x0 x1))).
Definition term231 (x0 : int) (x1 : int) := ~ ((int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1))) = (int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1)))).
Definition term78 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) -> (((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 x1) x1) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term215 (x0 : int) (x1 : int) := int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1)).
Definition term57 (x0 : int) (x1 : int) := (fun y0 : int => ((int_mul (div x0 y0) y0) = x0) = (int_divides y0 x0)) x1.
Definition term52 (x0 : int) (x1 : int) := (fun y0 : int => ((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0)) x1.
Definition term20 (x0 : int -> Prop) (x1 : int -> Prop) := (forall y0 : int, x0 y0) /\ (forall y0 : int, x1 y0).
Definition term252 := int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))).
Definition term131 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := ~ ((int_add (int_mul x0 x3) (int_mul x2 x1)) = (int_add (int_mul x0 x1) (int_mul x2 x3))).
Definition term86 (x0 : int) (x1 : int) := ~ (((int_mul (div x0 x1) x1) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term84 (x0 : int) (x1 : int) := ~ (((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term261 (x0 : int) (x1 : int) := int_mul (rem x0 x1) (int_of_num (NUMERAL (BIT1 0))).
Definition term260 (x0 : int) (x1 : int) := int_add (int_add (int_mul x1 (div x0 x1)) (int_add x0 (rem x0 x1))) (int_of_num (NUMERAL 0)).
Definition term53 (x0 : int) (x1 : int) := int_mul x1 (div x0 x1).
Definition term299 := ((~ (forall y0 : int, forall y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) -> (((int_mul y1 (div y0 y1)) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y0 y1) y1) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))))) = (exists y0 : int, exists y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) /\ (((((int_mul y1 (div y0 y1)) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y1 (div y0 y1)) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div y0 y1) y1) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div y0 y1) y1) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0)))))))) -> forall y0 : int, forall y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) -> (((int_mul y1 (div y0 y1)) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y0 y1) y1) = y0) = ((rem y0 y1) = (int_of_num (NUMERAL 0)))).
Definition term155 (x0 : int) (x1 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (rem x1 x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0)))).
Definition term45 := fun y0 : int => ((fun y1 : int => forall y2 : int, ((int_mul y2 (div y1 y2)) = y1) = (int_divides y2 y1)) y0) /\ ((fun y1 : int => forall y2 : int, ((int_mul (div y1 y2) y2) = y1) = (int_divides y2 y1)) y0).
Definition term297 (x0 : Prop) := ((exists y0 : int, exists y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) /\ (((((int_mul y1 (div y0 y1)) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y1 (div y0 y1)) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div y0 y1) y1) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div y0 y1) y1) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))))) -> False) -> ((~ x0) = (exists y0 : int, exists y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) /\ (((((int_mul y1 (div y0 y1)) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y1 (div y0 y1)) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div y0 y1) y1) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div y0 y1) y1) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0)))))))) -> x0.
Definition term75 (x0 : int) (x1 : int) := (((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 x1) x1) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term89 (x0 : int) (x1 : int) := or ((((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))).
Definition term65 (x0 : int) (x1 : int) := ((fun y0 : int => ((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0)) x1) /\ ((fun y0 : int => ((int_mul (div x0 y0) y0) = x0) = (int_divides y0 x0)) x1).
Definition term77 (x0 : int) (x1 : int) := ((int_add (int_mul (div x1 x0) x0) (rem x1 x0)) = x1) -> (((int_mul x0 (div x1 x0)) = x1) = (int_divides x0 x1)) /\ (((int_mul (div x1 x0) x0) = x1) = (int_divides x0 x1)).
Definition term3 (x0 : int) := forall y0 : int, ((rem x0 y0) = (int_of_num (NUMERAL 0))) = (int_divides y0 x0).
Definition term19 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := forall y0 : a0, (x0 y0) /\ (x1 y0).
Definition term146 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x0 x1).
Definition term14 (x0 : int) (x1 : int) := int_add (int_mul (div x0 x1) x1) (rem x0 x1).
Definition term208 (x0 : int) (x1 : int) := int_add (int_add (int_mul x1 (div x0 x1)) (rem x0 x1)) (int_of_num (NUMERAL 0)).
Definition term106 := exists y0 : int, ~ ((fun y1 : int => forall y2 : int, ((int_add (int_mul (div y1 y2) y2) (rem y1 y2)) = y1) -> (((int_mul y2 (div y1 y2)) = y1) = ((rem y1 y2) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y1 y2) y2) = y1) = ((rem y1 y2) = (int_of_num (NUMERAL 0))))) y0).
Definition term100 (x0 : int) := exists y0 : int, ~ ((fun y1 : int => ((int_add (int_mul (div x0 y1) y1) (rem x0 y1)) = x0) -> (((int_mul y1 (div x0 y1)) = x0) = ((rem x0 y1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 y1) y1) = x0) = ((rem x0 y1) = (int_of_num (NUMERAL 0))))) y0).
Definition term139 := int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)).
Definition term111 := exists y0 : int, exists y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) /\ (((((int_mul y1 (div y0 y1)) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y1 (div y0 y1)) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div y0 y1) y1) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div y0 y1) y1) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0)))))).
Definition term110 := fun y0 : int => exists y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) /\ (((((int_mul y1 (div y0 y1)) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y1 (div y0 y1)) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div y0 y1) y1) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div y0 y1) y1) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0)))))).
Definition term203 (x0 : int) (x1 : int) := int_add (int_mul (div x0 x1) x1).
Definition term182 := (~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0)))) -> forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2)) = (int_add y1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y3))).
Definition term68 (x0 : int) := fun y0 : int => (((int_mul y0 (div x0 y0)) = x0) = (int_divides y0 x0)) /\ (((int_mul (div x0 y0) y0) = x0) = (int_divides y0 x0)).
Definition term209 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (rem x1 x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))))).
Definition term94 (x0 : int) (x1 : int) := ((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (~ ((((int_mul x1 (div x0 x1)) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div x0 x1) x1) = x0) = ((rem x0 x1) = (int_of_num (NUMERAL 0)))))).
Definition term137 := int_mul (int_of_num (NUMERAL 0)).
Definition term59 (x0 : int) := fun y0 : int => (fun y1 : int => ((int_mul (div x0 y1) y1) = x0) = (int_divides y1 x0)) y0.
Definition term54 (x0 : int) := fun y0 : int => (fun y1 : int => ((int_mul y1 (div x0 y1)) = x0) = (int_divides y1 x0)) y0.
Definition term227 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) x1) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_add (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (rem x1 x0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0))))).
Definition term210 (x0 : int) (x1 : int) := int_add (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (div x1 x0) x0) (rem x1 x0))) (int_mul (int_of_num (NUMERAL 0)) (rem x1 x0))) (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL 0))) (int_mul x1 (int_of_num (NUMERAL (BIT1 0)))))).
Definition term221 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x1 (div x0 x1)).
Definition term220 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 (int_of_num (NUMERAL 0)))).
Definition term201 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_mul x0 (div x1 x0)) (int_of_num (NUMERAL 0))) (int_mul x1 (int_of_num (NUMERAL (BIT1 0))))).
Definition term290 (x0 : int) (x1 : int) := ~ (((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ ((((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ (((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0)))))) \/ (((int_add (int_mul (div x0 x1) x1) (rem x0 x1)) = x0) /\ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0))))))).
Definition term74 (x0 : int) (x1 : int) := @eq Prop ((int_mul (div x1 x0) x0) = x1).
Definition term76 (x0 : int) (x1 : int) := imp ((int_add (int_mul (div x1 x0) x0) (rem x1 x0)) = x1).
Definition term256 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL 0)) (int_mul x1 (div x0 x1)).
Definition term298 (x0 : Prop) := ((~ x0) = (exists y0 : int, exists y1 : int, ((int_add (int_mul (div y0 y1) y1) (rem y0 y1)) = y0) /\ (((((int_mul y1 (div y0 y1)) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul y1 (div y0 y1)) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((((int_mul (div y0 y1) y1) = y0) /\ (~ ((rem y0 y1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div y0 y1) y1) = y0)) /\ ((rem y0 y1) = (int_of_num (NUMERAL 0)))))))) -> x0.
Definition term87 (x0 : int) (x1 : int) := (((int_mul (div x0 x1) x1) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul (div x0 x1) x1) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term85 (x0 : int) (x1 : int) := (((int_mul x1 (div x0 x1)) = x0) /\ (~ ((rem x0 x1) = (int_of_num (NUMERAL 0))))) \/ ((~ ((int_mul x1 (div x0 x1)) = x0)) /\ ((rem x0 x1) = (int_of_num (NUMERAL 0)))).
Definition term128 (x0 : int) (x1 : int) := ~ ((int_mul x0 (div x1 x0)) = x1).
Definition term60 (x0 : int) := forall y0 : int, (fun y1 : int => ((int_mul (div x0 y1) y1) = x0) = (int_divides y1 x0)) y0.
Definition term55 (x0 : int) := forall y0 : int, (fun y1 : int => ((int_mul y1 (div x0 y1)) = x0) = (int_divides y1 x0)) y0.
Definition term159 := (((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0))) = False) -> ~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0))).
Definition term133 := int_of_num (NUMERAL (BIT1 0)).
Definition term204 (x0 : int) (x1 : int) := int_add (int_mul x1 (div x0 x1)).
Definition term226 (x0 : int) (x1 : int) := int_add (int_add x0 (rem x0 x1)).
Definition term35 := fun y0 : int => (fun y1 : int => forall y2 : int, ((int_mul (div y1 y2) y2) = y1) = (int_divides y2 y1)) y0.
Definition term28 := fun y0 : int => (fun y1 : int => forall y2 : int, ((int_mul y2 (div y1 y2)) = y1) = (int_divides y2 y1)) y0.
Definition term212 (x0 : int) (x1 : int) := int_add (int_mul x0 (div x1 x0)) (int_add (rem x1 x0) x1).
Definition term157 := NUMERAL (BIT1 0).
Definition term126 (x0 : int) (x1 : int) := @eq int (int_mul (div x0 x1) x1).
Definition term109 := fun y0 : int => ~ ((fun y1 : int => forall y2 : int, ((int_add (int_mul (div y1 y2) y2) (rem y1 y2)) = y1) -> (((int_mul y2 (div y1 y2)) = y1) = ((rem y1 y2) = (int_of_num (NUMERAL 0)))) /\ (((int_mul (div y1 y2) y2) = y1) = ((rem y1 y2) = (int_of_num (NUMERAL 0))))) y0).
Definition term268 (x0 : int) (x1 : int) := int_add (int_mul x0 (div x1 x0)) x1.
