Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term143 (x0 : int) (x1 : int) := int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1).
Definition term273 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))).
Definition term23 (x0 : int) (x1 : int) := and ((int_le (int_of_num (NUMERAL 0)) x1) -> (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) x1).
Definition term77 (x0 : int) := int_sub (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0).
Definition term106 (x0 : int) (x1 : int) := fun y0 : int => (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul y0 x0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x1)) = (int_of_num (NUMERAL 0)).
Definition term84 (x0 : int) (x1 : int) := fun y0 : int => (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x1)) = (int_of_num (NUMERAL 0)).
Definition term233 (x0 : int) := fun y0 : int => forall y1 : int, ((int_add (int_mul y0 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0)).
Definition term111 (x0 : int) := fun y0 : int => forall y1 : int, ((int_add (int_mul y0 x0) y1) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) y1) = (int_of_num (NUMERAL 0)).
Definition term250 (x0 : int) (x1 : int) := (fun y0 : int => forall y1 : int, ((int_add (int_mul y0 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) x1.
Definition term130 (x0 : int) (x1 : int) := (fun y0 : int => forall y1 : int, ((int_add (int_mul y0 x0) y1) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) y1) = (int_of_num (NUMERAL 0))) x1.
Definition term30 (x0 : int) (x1 : int) := @eq Prop (int_divides x0 (int_neg x1)).
Definition term120 (x0 : int -> Prop) := exists y0 : int, ~ (x0 y0).
Definition term35 (x0 : int) (x1 : int) := int_sub (int_mul x0 x1).
Definition term119 (x0 : int -> Prop) := ~ (all x0).
Definition term279 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term46 := Nat.pow (BIT1 0) (NUMERAL (BIT0 (BIT1 0))).
Definition term194 (x0 : int) (x1 : int) (x2 : int) := (fun y0 : int => forall y1 : int, ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y0)) = (int_add x1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y1)))) x2.
Definition term186 := (forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4)))) -> forall y0 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4))).
Definition term235 := fun y0 : int => forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)).
Definition term113 := fun y0 : int => forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)).
Definition term280 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0)).
Definition term264 (x0 : int) (x1 : int) (x2 : int) := (~ ((int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0)))) /\ (~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0)))).
Definition term150 (x0 : int) (x1 : int) (x2 : int) := (~ ((int_add (int_mul x0 x1) x2) = (int_of_num (NUMERAL 0)))) /\ (~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0)))).
Definition term154 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2).
Definition term187 (x0 : int) := (fun y0 : int => (~ (y0 = (int_of_num (NUMERAL 0)))) -> forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4)))) x0.
Definition term100 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0)).
Definition term146 (x0 : int) (x1 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_mul x0 x1).
Definition term20 (x0 : int) := imp (int_le (int_of_num (NUMERAL 0)) x0).
Definition term206 := int_add (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)).
Definition term28 (x0 : int) (x1 : int) := exists y0 : int, x0 = (int_mul x1 y0).
Definition term16 (x0 : int) := imp (~ (int_le (int_of_num (NUMERAL 0)) x0)).
Definition term44 := int_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0))).
Definition term105 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_sub (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))).
Definition term22 (x0 : int) (x1 : int) := (int_le (int_of_num (NUMERAL 0)) x1) -> (int_divides x0 x1) = (int_divides x0 x1).
Definition term71 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_sub (int_mul x0 x1) x2).
Definition term102 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_of_num (NUMERAL 0))).
Definition term265 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))).
Definition term153 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))).
Definition term33 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_mul x0 x1) (int_neg x2).
Definition term148 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2).
Definition term63 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) x2).
Definition term29 (x0 : int) (x1 : int) := exists y0 : int, (int_neg x0) = (int_mul x1 y0).
Definition term175 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := forall y0 : int, (~ (x3 = (int_of_num (NUMERAL 0)))) -> ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 y0))).
Definition term32 := int_of_num (NUMERAL 0).
Definition term98 (x0 : int) (x1 : int) := fun y0 : int => (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul y0 x0)) x1) = (int_of_num (NUMERAL 0)).
Definition term65 (x0 : int) (x1 : int) := fun y0 : int => (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 y0)) x1) = (int_of_num (NUMERAL 0)).
Definition term192 (x0 : int) (x1 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y1)) = (int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2)))) x1.
Definition term170 (x0 : int) (x1 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, forall y3 : int, (~ (x0 = (int_of_num (NUMERAL 0)))) -> ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul x0 y2)) = (int_add y1 (int_mul x0 y3)))) x1.
Definition term27 (x0 : int) (x1 : int) := @eq Prop ((int_divides x0 (@COND int (int_le (int_of_num (NUMERAL 0)) x1) x1 (int_neg x1))) = (int_divides x0 x1)).
Definition term118 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2.
Definition term116 (x0 : int) (x1 : int) (x2 : int) := ~ (((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0))).
Definition term61 (x0 : int) (x1 : int) := int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1).
Definition term38 (x0 : int) := int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0).
Definition term213 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))).
Definition term285 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))).
Definition term214 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))).
Definition term67 (x0 : int) (x1 : int) (x2 : int) := ((int_mul x2 x0) = (int_neg x1)) -> exists y0 : int, x1 = (int_mul x2 y0).
Definition term177 (x0 : int) (x1 : int) (x2 : int) (x3 : int) (x4 : int) := (~ (x3 = (int_of_num (NUMERAL 0)))) -> ((x0 = x2) /\ (~ (x1 = x4))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 x4))).
Definition term147 (x0 : int) (x1 : int) := int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)).
Definition term256 (x0 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) x0.
Definition term190 (x0 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2)) = (int_add y1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y3)))) x0.
Definition term168 (x0 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4)))) x0.
Definition term136 (x0 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0))) x0.
Definition term197 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := ((x0 = x2) /\ (~ (x1 = x3))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) x1)) = (int_add x2 (int_mul (int_of_num (NUMERAL (BIT1 0))) x3))).
Definition term179 (x0 : int) (x1 : int) (x2 : int) (x3 : int) (x4 : int) := ((x0 = x2) /\ (~ (x1 = x4))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 x4))).
Definition term287 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))))).
Definition term245 (x0 : int) (x1 : int) := fun y0 : int => ~ ((fun y1 : int => ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) y0).
Definition term125 (x0 : int) (x1 : int) := fun y0 : int => ~ ((fun y1 : int => ((int_add (int_mul x1 x0) y1) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y1) = (int_of_num (NUMERAL 0))) y0).
Definition term160 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2)).
Definition term25 (x0 : int) (x1 : int) := ((int_le (int_of_num (NUMERAL 0)) x1) -> (int_divides x0 x1) = (int_divides x0 x1)) /\ ((~ (int_le (int_of_num (NUMERAL 0)) x1)) -> (int_divides x0 (int_neg x1)) = (int_divides x0 x1)).
Definition term272 (x0 : int) (x1 : int) (x2 : int) := (((int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)))) = (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))))) /\ (~ ((int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))) -> ~ ((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term198 (x0 : int) (x1 : int) (x2 : int) := (((int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2))) = (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2)) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))))) /\ (~ ((int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))) -> ~ ((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2)) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term185 := forall y0 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4))).
Definition term144 (x0 : int) (x1 : int) := int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)).
Definition term19 (x0 : int) (x1 : int) := (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) x1.
Definition term55 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_add (int_mul x0 x1) x2).
Definition term289 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))).
Definition term218 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))).
Definition term259 := fun y0 : int => exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)))).
Definition term139 := fun y0 : int => exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)))).
Definition term301 (x0 : int) (x1 : int) := (exists y0 : int, (int_neg x0) = (int_mul x1 y0)) -> exists y0 : int, x0 = (int_mul x1 y0).
Definition term300 (x0 : int) (x1 : int) := (exists y0 : int, x0 = (int_mul x1 y0)) -> exists y0 : int, (int_neg x0) = (int_mul x1 y0).
Definition term72 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term172 (x0 : int) (x1 : int) (x2 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, (~ (x1 = (int_of_num (NUMERAL 0)))) -> ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul x1 y1)) = (int_add y0 (int_mul x1 y2)))) x2.
Definition term271 (x0 : int) (x1 : int) (x2 : int) := ((int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)))) = (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))))) /\ (~ ((int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))))))).
Definition term163 (x0 : int) (x1 : int) (x2 : int) := ((int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2))) = (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2)) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))))) /\ (~ ((int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) = (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))))))).
Definition term96 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) x2) (int_of_num (NUMERAL 0)).
Definition term257 (x0 : int) := ~ ((fun y0 : int => forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) x0).
Definition term137 (x0 : int) := ~ ((fun y0 : int => forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0))) x0).
Definition term303 (x0 : int) := ~ (int_le (int_of_num (NUMERAL 0)) x0).
Definition term41 (x0 : nat) (x1 : nat) := int_mul (int_neg (int_of_num x0)) (int_neg (int_of_num x1)).
Definition term304 (x0 : int) := forall y0 : int, (int_divides x0 (int_abs y0)) = (int_divides x0 y0).
Definition term274 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))).
Definition term108 (x0 : int) (x1 : int) (x2 : int) := ((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0)).
Definition term103 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term282 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))).
Definition term211 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2)) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))).
Definition term266 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term92 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) x2) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_of_num (NUMERAL 0))).
Definition term238 (x0 : int) (x1 : int) (x2 : int) := ~ (((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))).
Definition term269 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))).
Definition term73 (x0 : int) (x1 : int) (x2 : int) := imp ((int_mul x0 x1) = x2).
Definition term176 (x0 : int) (x1 : int) (x2 : int) (x3 : int) (x4 : int) := (fun y0 : int => (~ (x3 = (int_of_num (NUMERAL 0)))) -> ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 y0)))) x4.
Definition term59 (x0 : int) (x1 : int) (x2 : int) := int_add x0 (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 x2)).
Definition term200 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))).
Definition term69 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_mul x0 x1) x2.
Definition term243 (x0 : int) (x1 : int) (x2 : int) := (fun y0 : int => ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) x2.
Definition term7 (x0 : int) (x1 : Prop) (x2 : int -> Prop) (x3 : int) := (x1 -> x2 x0) /\ ((~ x1) -> x2 x3).
Definition term2 (x0 : int) (x1 : int) := int_divides x0 (int_abs x1).
Definition term293 (x0 : int) (x1 : int) (x2 : int) := ~ (((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))))).
Definition term222 (x0 : int) (x1 : int) (x2 : int) := ~ (((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0))))).
Definition term10 (x0 : int) (x1 : int) := fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1).
Definition term161 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2)).
Definition term275 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term201 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))))) = (int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2)) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0)))))))).
Definition term36 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2).
Definition term50 := int_mul (int_of_num (NUMERAL (BIT1 0))).
Definition term12 (x0 : int) (x1 : int) := ((int_le (int_of_num (NUMERAL 0)) x1) -> (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) x1) /\ ((~ (int_le (int_of_num (NUMERAL 0)) x1)) -> (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) (int_neg x1)).
Definition term302 (x0 : int) (x1 : int) := ((exists y0 : int, (int_neg x0) = (int_mul x1 y0)) -> exists y0 : int, x0 = (int_mul x1 y0)) /\ ((exists y0 : int, x0 = (int_mul x1 y0)) -> exists y0 : int, (int_neg x0) = (int_mul x1 y0)).
Definition term174 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := (fun y0 : int => forall y1 : int, (~ (x2 = (int_of_num (NUMERAL 0)))) -> ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul x2 y0)) = (int_add x1 (int_mul x2 y1)))) x3.
Definition term123 (x0 : int) (x1 : int) (x2 : int) := (fun y0 : int => ((int_add (int_mul x1 x0) y0) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y0) = (int_of_num (NUMERAL 0))) x2.
Definition term196 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := (fun y0 : int => ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) x1)) = (int_add x2 (int_mul (int_of_num (NUMERAL (BIT1 0))) y0)))) x3.
Definition term76 (x0 : int) := int_sub (int_neg x0).
Definition term47 := Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)).
Definition term1 (x0 : int) := @COND int (int_le (int_of_num (NUMERAL 0)) x0) x0 (int_neg x0).
Definition term296 := (exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))))) -> False.
Definition term225 := (exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0))))) -> False.
Definition term40 := int_neg (int_of_num (NUMERAL (BIT1 0))).
Definition term246 (x0 : int) (x1 : int) := fun y0 : int => ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0)))).
Definition term107 (x0 : int) (x1 : int) := exists y0 : int, (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul y0 x0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x1)) = (int_of_num (NUMERAL 0)).
Definition term85 (x0 : int) (x1 : int) := exists y0 : int, (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x1)) = (int_of_num (NUMERAL 0)).
Definition term3 (x0 : int) (x1 : int) := int_divides x0 (@COND int (int_le (int_of_num (NUMERAL 0)) x1) x1 (int_neg x1)).
Definition term75 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_neg x0) (int_mul x1 x2).
Definition term277 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))).
Definition term205 := int_add (int_of_num (NUMERAL 0)).
Definition term155 := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0)).
Definition term231 (x0 : int) (x1 : int) := fun y0 : int => ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0)).
Definition term215 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2))).
Definition term37 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term226 (x0 : Prop) (x1 : Prop) := (x0 -> False) -> ((~ x1) = x0) -> x1.
Definition term49 := int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_neg (int_of_num (NUMERAL (BIT1 0))))).
Definition term81 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_sub (int_neg x0) (int_mul x1 x2)).
Definition term162 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2)) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))).
Definition term31 (x0 : int) (x1 : int) := @eq Prop (exists y0 : int, (int_neg x0) = (int_mul x1 y0)).
Definition term97 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_sub (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) x2) (int_of_num (NUMERAL 0))).
Definition term42 (x0 : nat) (x1 : nat) := int_of_num (Nat.mul x0 x1).
Definition term270 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))).
Definition term288 (x0 : int) (x1 : int) (x2 : int) := int_add (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term278 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))))).
Definition term207 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))))).
Definition term15 (x0 : int) (x1 : int) := int_divides x0 (int_neg x1).
Definition term241 (x0 : int) (x1 : int) := ~ (forall y0 : int, ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))).
Definition term121 (x0 : int) (x1 : int) := ~ (forall y0 : int, ((int_add (int_mul x1 x0) y0) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y0) = (int_of_num (NUMERAL 0))).
Definition term21 (x0 : int) (x1 : int) := (int_le (int_of_num (NUMERAL 0)) x1) -> (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) x1.
Definition term210 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) x2)) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))).
Definition term166 := ~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0))).
Definition term203 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0)).
Definition term290 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))).
Definition term212 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0))).
Definition term195 (x0 : int) (x1 : int) (x2 : int) := forall y0 : int, ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) x1)) = (int_add x2 (int_mul (int_of_num (NUMERAL (BIT1 0))) y0))).
Definition term180 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := forall y0 : int, ((x0 = x2) /\ (~ (x1 = y0))) -> ~ ((int_add x0 (int_mul x3 x1)) = (int_add x2 (int_mul x3 y0))).
Definition term0 (x0 : int) := (fun y0 : int => (int_abs y0) = (@COND int (int_le (int_of_num (NUMERAL 0)) y0) y0 (int_neg y0))) x0.
Definition term305 := forall y0 : int, forall y1 : int, (int_divides y0 (int_abs y1)) = (int_divides y0 y1).
Definition term236 := forall y0 : int, forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)).
Definition term234 (x0 : int) := forall y0 : int, forall y1 : int, ((int_add (int_mul y0 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0)).
Definition term193 (x0 : int) (x1 : int) := forall y0 : int, forall y1 : int, ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y0)) = (int_add x1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y1))).
Definition term191 (x0 : int) := forall y0 : int, forall y1 : int, forall y2 : int, ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y1)) = (int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2))).
Definition term189 := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2)) = (int_add y1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y3))).
Definition term183 (x0 : int) := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul x0 y2)) = (int_add y1 (int_mul x0 y3))).
Definition term182 (x0 : int) (x1 : int) := forall y0 : int, forall y1 : int, forall y2 : int, ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul x1 y1)) = (int_add y0 (int_mul x1 y2))).
Definition term181 (x0 : int) (x1 : int) (x2 : int) := forall y0 : int, forall y1 : int, ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul x2 y0)) = (int_add x1 (int_mul x2 y1))).
Definition term173 (x0 : int) (x1 : int) (x2 : int) := forall y0 : int, forall y1 : int, (~ (x2 = (int_of_num (NUMERAL 0)))) -> ((x0 = x1) /\ (~ (y0 = y1))) -> ~ ((int_add x0 (int_mul x2 y0)) = (int_add x1 (int_mul x2 y1))).
Definition term171 (x0 : int) (x1 : int) := forall y0 : int, forall y1 : int, forall y2 : int, (~ (x1 = (int_of_num (NUMERAL 0)))) -> ((x0 = y0) /\ (~ (y1 = y2))) -> ~ ((int_add x0 (int_mul x1 y1)) = (int_add y0 (int_mul x1 y2))).
Definition term169 (x0 : int) := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, (~ (x0 = (int_of_num (NUMERAL 0)))) -> ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul x0 y2)) = (int_add y1 (int_mul x0 y3))).
Definition term167 := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, forall y4 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> ((y1 = y2) /\ (~ (y3 = y4))) -> ~ ((int_add y1 (int_mul y0 y3)) = (int_add y2 (int_mul y0 y4))).
Definition term114 := forall y0 : int, forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)).
Definition term112 (x0 : int) := forall y0 : int, forall y1 : int, ((int_add (int_mul y0 x0) y1) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) y1) = (int_of_num (NUMERAL 0)).
Definition term109 (x0 : int) (x1 : int) := fun y0 : int => ((int_add (int_mul x1 x0) y0) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y0) = (int_of_num (NUMERAL 0)).
Definition term9 (x0 : int) (x1 : Prop) (x2 : int) (x3 : int) (x4 : int) := (x1 -> (fun y0 : int => (int_divides x2 y0) = (int_divides x2 x3)) x0) /\ ((~ x1) -> (fun y0 : int => (int_divides x2 y0) = (int_divides x2 x3)) x4).
Definition term263 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))).
Definition term261 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))).
Definition term216 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2))) (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))))).
Definition term164 := S (Nat.add 0 0).
Definition term5 (x0 : int) (x1 : int) := @eq Prop (int_divides x0 (@COND int (int_le (int_of_num (NUMERAL 0)) x1) x1 (int_neg x1))).
Definition term204 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0))).
Definition term54 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_sub (int_mul x0 x1) (int_neg x2)).
Definition term149 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_mul x0 x1) x2) = (int_of_num (NUMERAL 0))).
Definition term141 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0))).
Definition term64 (x0 : int) (x1 : int) := fun y0 : int => x0 = (int_mul x1 y0).
Definition term90 (x0 : int) (x1 : int) := int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)).
Definition term157 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2).
Definition term251 (x0 : int) (x1 : int) := ~ ((fun y0 : int => forall y1 : int, ((int_add (int_mul y0 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) x1).
Definition term131 (x0 : int) (x1 : int) := ~ ((fun y0 : int => forall y1 : int, ((int_add (int_mul y0 x0) y1) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) y1) = (int_of_num (NUMERAL 0))) x1).
Definition term219 (x0 : int) (x1 : int) (x2 : int) := ~ ((int_add (int_mul x0 x1) x2) = (int_add (int_mul x0 x1) x2)).
Definition term87 (x0 : int) (x1 : int) (x2 : int) := ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) -> exists y0 : int, (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0)).
Definition term101 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term151 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := (~ (x0 = x1)) /\ (~ (x2 = x3)).
Definition term291 (x0 : int) (x1 : int) (x2 : int) := (~ ((int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)))) -> ((int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))) = False.
Definition term244 (x0 : int) (x1 : int) (x2 : int) := ~ ((fun y0 : int => ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) x2).
Definition term124 (x0 : int) (x1 : int) (x2 : int) := ~ ((fun y0 : int => ((int_add (int_mul x1 x0) y0) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y0) = (int_of_num (NUMERAL 0))) x2).
Definition term199 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0))).
Definition term230 (x0 : int) (x1 : int) (x2 : int) := ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0)).
Definition term178 (x0 : int) := ~ (x0 = (int_of_num (NUMERAL 0))).
Definition term51 (x0 : int) := int_mul (int_of_num (NUMERAL (BIT1 0))) x0.
Definition term239 (x0 : int) (x1 : int) (x2 : int) := ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0)))).
Definition term247 (x0 : int) (x1 : int) := exists y0 : int, ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0)))).
Definition term127 (x0 : int) (x1 : int) := exists y0 : int, ((int_add (int_mul x1 x0) y0) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y0) = (int_of_num (NUMERAL 0)))).
Definition term184 (x0 : int) := (~ (x0 = (int_of_num (NUMERAL 0)))) -> forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul x0 y2)) = (int_add y1 (int_mul x0 y3))).
Definition term248 (x0 : int) := ~ (forall y0 : int, forall y1 : int, ((int_add (int_mul y0 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))).
Definition term237 := ~ (forall y0 : int, forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))).
Definition term128 (x0 : int) := ~ (forall y0 : int, forall y1 : int, ((int_add (int_mul y0 x0) y1) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) y1) = (int_of_num (NUMERAL 0))).
Definition term115 := ~ (forall y0 : int, forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0))).
Definition term57 (x0 : int) (x1 : int) (x2 : int) := imp ((int_add (int_mul x0 x1) x2) = (int_of_num (NUMERAL 0))).
Definition term34 (x0 : int) := int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0.
Definition term68 (x0 : int) (x1 : int) (x2 : int) := ((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) -> exists y0 : int, (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 y0)) x2) = (int_of_num (NUMERAL 0)).
Definition term240 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2).
Definition term53 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul x0 x1) x2.
Definition term17 (x0 : int) (x1 : int) := (~ (int_le (int_of_num (NUMERAL 0)) x1)) -> (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) (int_neg x1).
Definition term89 := int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))).
Definition term159 := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))).
Definition term43 := int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_neg (int_of_num (NUMERAL (BIT1 0)))).
Definition term78 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) (int_mul x1 x2).
Definition term60 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) x2.
Definition term94 := int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_of_num (NUMERAL 0)).
Definition term80 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2).
Definition term58 (x0 : int) (x1 : int) (x2 : int) := int_sub x0 (int_mul x1 x2).
Definition term39 (x0 : int) := int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_neg (int_of_num (NUMERAL (BIT1 0))))) x0.
Definition term208 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul x0 x1) x2).
Definition term62 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_sub x0 (int_mul x1 x2)).
Definition term202 := int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL (BIT1 0))).
Definition term268 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))).
Definition term152 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := ~ ((int_add (int_mul x0 x3) (int_mul x2 x1)) = (int_add (int_mul x0 x1) (int_mul x2 x3))).
Definition term79 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x1 x2)).
Definition term52 (x0 : int) (x1 : int) := int_add (int_mul x0 x1).
Definition term299 := ((~ (forall y0 : int, forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)))) = (exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)))))) -> forall y0 : int, forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)).
Definition term229 := ((~ (forall y0 : int, forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)))) = (exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)))))) -> forall y0 : int, forall y1 : int, forall y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)).
Definition term292 (x0 : int) (x1 : int) (x2 : int) := (((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))))) -> False.
Definition term221 (x0 : int) (x1 : int) (x2 : int) := (((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0))))) -> False.
Definition term142 (x0 : int) (x1 : int) := int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1.
Definition term297 (x0 : Prop) := ((exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))))) -> False) -> ((~ x0) = (exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)))))) -> x0.
Definition term227 (x0 : Prop) := ((exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0))))) -> False) -> ((~ x0) = (exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)))))) -> x0.
Definition term95 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) x2).
Definition term8 (x0 : int) (x1 : int) (x2 : Prop) (x3 : int) (x4 : int) := (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) (@COND int x2 x3 x4).
Definition term217 (x0 : int) (x1 : int) (x2 : int) := int_add (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) x2).
Definition term262 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term82 (x0 : int) (x1 : int) (x2 : int) := @eq int (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term209 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul x0 x1) x2) (int_of_num (NUMERAL 0)).
Definition term91 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) x2).
Definition term295 (x0 : int) (x1 : int) (x2 : int) := ((((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))))) = False) -> ~ (((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))))).
Definition term224 (x0 : int) (x1 : int) (x2 : int) := ((((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0))))) = False) -> ~ (((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0))))).
Definition term255 := exists y0 : int, ~ ((fun y1 : int => forall y2 : int, forall y3 : int, ((int_add (int_mul y2 y1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y3)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1) y2)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y3)) = (int_of_num (NUMERAL 0))) y0).
Definition term249 (x0 : int) := exists y0 : int, ~ ((fun y1 : int => forall y2 : int, ((int_add (int_mul y1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) y0).
Definition term242 (x0 : int) (x1 : int) := exists y0 : int, ~ ((fun y1 : int => ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) y0).
Definition term135 := exists y0 : int, ~ ((fun y1 : int => forall y2 : int, forall y3 : int, ((int_add (int_mul y2 y1) y3) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1) y2)) y3) = (int_of_num (NUMERAL 0))) y0).
Definition term129 (x0 : int) := exists y0 : int, ~ ((fun y1 : int => forall y2 : int, ((int_add (int_mul y1 x0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y1)) y2) = (int_of_num (NUMERAL 0))) y0).
Definition term122 (x0 : int) (x1 : int) := exists y0 : int, ~ ((fun y1 : int => ((int_add (int_mul x1 x0) y1) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y1) = (int_of_num (NUMERAL 0))) y0).
Definition term158 := int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)).
Definition term281 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2))) (int_mul (int_of_num (NUMERAL 0)) (int_of_num (NUMERAL 0)))).
Definition term126 (x0 : int) (x1 : int) := fun y0 : int => ((int_add (int_mul x1 x0) y0) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y0) = (int_of_num (NUMERAL 0)))).
Definition term260 := exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)))).
Definition term254 (x0 : int) := exists y0 : int, exists y1 : int, ((int_add (int_mul y0 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0)))).
Definition term140 := exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)))).
Definition term134 (x0 : int) := exists y0 : int, exists y1 : int, ((int_add (int_mul y0 x0) y1) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) y1) = (int_of_num (NUMERAL 0)))).
Definition term14 (x0 : int) (x1 : int) := (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) (int_neg x1).
Definition term13 (x0 : int) := int_le (int_of_num (NUMERAL 0)) x0.
Definition term188 := (~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0)))) -> forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = y1) /\ (~ (y2 = y3))) -> ~ ((int_add y0 (int_mul (int_of_num (NUMERAL (BIT1 0))) y2)) = (int_add y1 (int_mul (int_of_num (NUMERAL (BIT1 0))) y3))).
Definition term145 (x0 : int) (x1 : int) := int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_neg (int_of_num (NUMERAL (BIT1 0))))) (int_mul x0 x1).
Definition term56 (x0 : int) (x1 : int) (x2 : int) := imp ((int_mul x0 x1) = (int_neg x2)).
Definition term74 (x0 : int) (x1 : int) (x2 : int) := imp ((int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))).
Definition term156 := int_mul (int_of_num (NUMERAL 0)).
Definition term117 (x0 : int) (x1 : int) (x2 : int) := ((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0)))).
Definition term99 (x0 : int) (x1 : int) := exists y0 : int, (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul y0 x0)) x1) = (int_of_num (NUMERAL 0)).
Definition term66 (x0 : int) (x1 : int) := exists y0 : int, (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 y0)) x1) = (int_of_num (NUMERAL 0)).
Definition term18 (x0 : int) (x1 : int) := (~ (int_le (int_of_num (NUMERAL 0)) x1)) -> (int_divides x0 (int_neg x1)) = (int_divides x0 x1).
Definition term284 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0)))).
Definition term283 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL (BIT1 0))).
Definition term232 (x0 : int) (x1 : int) := forall y0 : int, ((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0)) = (int_of_num (NUMERAL 0)).
Definition term110 (x0 : int) (x1 : int) := forall y0 : int, ((int_add (int_mul x1 x0) y0) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) y0) = (int_of_num (NUMERAL 0)).
Definition term11 (x0 : int) (x1 : int) := (fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) (@COND int (int_le (int_of_num (NUMERAL 0)) x1) x1 (int_neg x1)).
Definition term253 (x0 : int) := fun y0 : int => exists y1 : int, ((int_add (int_mul y0 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1)) = (int_of_num (NUMERAL 0)))).
Definition term133 (x0 : int) := fun y0 : int => exists y1 : int, ((int_add (int_mul y0 x0) y1) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y0)) y1) = (int_of_num (NUMERAL 0)))).
Definition term104 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0)).
Definition term24 (x0 : int) (x1 : int) := and ((int_le (int_of_num (NUMERAL 0)) x1) -> (int_divides x0 x1) = (int_divides x0 x1)).
Definition term294 (x0 : int) (x1 : int) (x2 : int) := (~ (((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0)))))) -> (((int_add (int_mul x1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) = (int_of_num (NUMERAL 0))))) = False.
Definition term223 (x0 : int) (x1 : int) (x2 : int) := (~ (((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0)))))) -> (((int_add (int_mul x1 x0) x2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) x1)) x2) = (int_of_num (NUMERAL 0))))) = False.
Definition term267 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term6 (x0 : int -> Prop) (x1 : Prop) (x2 : int) (x3 : int) := x0 (@COND int x1 x2 x3).
Definition term70 (x0 : int) (x1 : int) (x2 : int) := int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2).
Definition term298 (x0 : Prop) := ((~ x0) = (exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0)))))) -> x0.
Definition term228 (x0 : Prop) := ((~ x0) = (exists y0 : int, exists y1 : int, exists y2 : int, ((int_add (int_mul y1 y0) y2) = (int_of_num (NUMERAL 0))) /\ (~ ((int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y0) y1)) y2) = (int_of_num (NUMERAL 0)))))) -> x0.
Definition term165 := (((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0))) = False) -> ~ ((int_of_num (NUMERAL (BIT1 0))) = (int_of_num (NUMERAL 0))).
Definition term48 := int_of_num (NUMERAL (BIT1 0)).
Definition term220 (x0 : int) (x1 : int) (x2 : int) := (~ ((int_add (int_mul x0 x1) x2) = (int_add (int_mul x0 x1) x2))) -> ((int_add (int_mul x0 x1) x2) = (int_add (int_mul x0 x1) x2)) = False.
Definition term286 (x0 : int) (x1 : int) (x2 : int) := int_add (int_add (int_mul (int_of_num (NUMERAL (BIT1 0))) (int_of_num (NUMERAL 0))) (int_mul (int_of_num (NUMERAL 0)) (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)))).
Definition term45 := NUMERAL (BIT1 0).
Definition term83 (x0 : int) (x1 : int) := fun y0 : int => (int_neg x0) = (int_mul x1 y0).
Definition term26 (x0 : int) (x1 : int) := @eq Prop ((fun y0 : int => (int_divides x0 y0) = (int_divides x0 x1)) (@COND int (int_le (int_of_num (NUMERAL 0)) x1) x1 (int_neg x1))).
Definition term276 (x0 : int) (x1 : int) (x2 : int) := int_mul (int_add (int_mul x0 x1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x2)) (int_of_num (NUMERAL 0)).
Definition term93 (x0 : nat) := int_mul (int_neg (int_of_num x0)) (int_of_num (NUMERAL 0)).
Definition term4 (x0 : int) (x1 : int) := @eq Prop (int_divides x0 (int_abs x1)).
Definition term86 (x0 : int) (x1 : int) (x2 : int) := ((int_mul x2 x0) = x1) -> exists y0 : int, (int_neg x1) = (int_mul x2 y0).
Definition term258 := fun y0 : int => ~ ((fun y1 : int => forall y2 : int, forall y3 : int, ((int_add (int_mul y2 y1) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y3)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1) y2)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y3)) = (int_of_num (NUMERAL 0))) y0).
Definition term252 (x0 : int) := fun y0 : int => ~ ((fun y1 : int => forall y2 : int, ((int_add (int_mul y1 x0) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y1)) (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y2)) = (int_of_num (NUMERAL 0))) y0).
Definition term138 := fun y0 : int => ~ ((fun y1 : int => forall y2 : int, forall y3 : int, ((int_add (int_mul y2 y1) y3) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) y1) y2)) y3) = (int_of_num (NUMERAL 0))) y0).
Definition term132 (x0 : int) := fun y0 : int => ~ ((fun y1 : int => forall y2 : int, ((int_add (int_mul y1 x0) y2) = (int_of_num (NUMERAL 0))) -> (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) x0) y1)) y2) = (int_of_num (NUMERAL 0))) y0).
Definition term88 (x0 : int) (x1 : int) (x2 : int) := int_sub (int_add (int_mul (int_neg (int_of_num (NUMERAL (BIT1 0)))) (int_mul x0 x1)) x2) (int_of_num (NUMERAL 0)).
