Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term113 (x0 : int) (x1 : int) := (~ (int_lt (rem x0 x1) (int_abs x1))) -> int_lt (rem x0 x1) (int_abs x1).
Definition term92 := fun y0 : int => forall y1 : int, ((y1 = (int_of_num (NUMERAL 0))) \/ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))) /\ (((y1 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem y0 y1))) /\ ((y1 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem y0 y1) (int_abs y1)))).
Definition term82 := fun y0 : int => forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))).
Definition term70 := fun y0 : int => forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1))).
Definition term64 := fun y0 : int => forall y1 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y0)) /\ (int_lt (rem y1 y0) (int_abs y0)))) -> ~ (forall y2 : int, forall y3 : int, (~ (y3 = (int_of_num (NUMERAL 0)))) -> (y2 = (int_add (int_mul (div y2 y3) y3) (rem y2 y3))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y2 y3)) /\ (int_lt (rem y2 y3) (int_abs y3)))).
Definition term63 := fun y0 : int => forall y1 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y0)) /\ (int_lt (rem y1 y0) (int_abs y0)))) -> (forall y2 : int, forall y3 : int, (~ (y3 = (int_of_num (NUMERAL 0)))) -> (y2 = (int_add (int_mul (div y2 y3) y3) (rem y2 y3))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y2 y3)) /\ (int_lt (rem y2 y3) (int_abs y3)))) -> False.
Definition term24 (x0 : int) (x1 : int) := (fun y0 : int => forall y1 : int, (exists y2 : int, (x0 = (int_add (int_mul y2 y0) y1)) /\ ((int_le (int_of_num (NUMERAL 0)) y1) /\ (int_lt y1 (int_abs y0)))) -> (rem x0 y0) = y1) x1.
Definition term109 := (~ False) -> False.
Definition term14 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := (x0 = (int_add (int_mul x1 x3) x2)) /\ ((int_le (int_of_num (NUMERAL 0)) x2) /\ (int_lt x2 (int_abs x3))).
Definition term69 (x0 : int) := forall y0 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ (int_lt (rem x0 y0) (int_abs y0))).
Definition term10 (x0 : int) (x1 : int) (x2 : int) := (fun y0 : int => forall y1 : int, ((x0 = (int_add (int_mul y0 x1) y1)) /\ ((int_le (int_of_num (NUMERAL 0)) y1) /\ (int_lt y1 (int_abs x1)))) -> (rem x0 x1) = y1) x2.
Definition term27 (x0 : int) := (x0 = (int_of_num (NUMERAL 0))) \/ (~ (x0 = (int_of_num (NUMERAL 0)))).
Definition term12 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := (fun y0 : int => ((x1 = (int_add (int_mul x0 x2) y0)) /\ ((int_le (int_of_num (NUMERAL 0)) y0) /\ (int_lt y0 (int_abs x2)))) -> (rem x1 x2) = y0) x3.
Definition term48 (x0 : int) (x1 : int) := ((~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False) -> (~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False.
Definition term54 (x0 : int) (x1 : int) := imp (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))).
Definition term40 (x0 : int) (x1 : int) := and ((rem x0 x1) = (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (rem x0 x1))).
Definition term117 (x0 : int) (x1 : int) := exists y0 : int, ((rem x0 x1) = (int_add (int_mul y0 x1) (rem x0 x1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1))).
Definition term16 (x0 : int) (x1 : int) (x2 : int) := exists y0 : int, (x0 = (int_add (int_mul y0 x2) x1)) /\ ((int_le (int_of_num (NUMERAL 0)) x1) /\ (int_lt x1 (int_abs x2))).
Definition term62 (x0 : int) := forall y0 : int, (~ (x0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y0 x0)) /\ (int_lt (rem y0 x0) (int_abs x0)))) -> ~ (forall y1 : int, forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) -> (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ (int_lt (rem y1 y2) (int_abs y2)))).
Definition term4 := int_of_num (NUMERAL 0).
Definition term8 (x0 : int) (x1 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, ((x0 = (int_add (int_mul y1 y0) y2)) /\ ((int_le (int_of_num (NUMERAL 0)) y2) /\ (int_lt y2 (int_abs y0)))) -> (rem x0 y0) = y2) x1.
Definition term47 (x0 : int) (x1 : int) := (~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False.
Definition term115 (x0 : int) := (fun y0 : int => forall y1 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y0)) /\ (int_lt (rem y1 y0) (int_abs y0)))) -> (forall y2 : int, forall y3 : int, (~ (y3 = (int_of_num (NUMERAL 0)))) -> (y2 = (int_add (int_mul (div y2 y3) y3) (rem y2 y3))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y2 y3)) /\ (int_lt (rem y2 y3) (int_abs y3)))) -> False) x0.
Definition term96 (x0 : int) := (fun y0 : int => forall y1 : int, ((y1 = (int_of_num (NUMERAL 0))) \/ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))) /\ (((y1 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem y0 y1))) /\ ((y1 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem y0 y1) (int_abs y1))))) x0.
Definition term91 (x0 : int) := forall y0 : int, ((y0 = (int_of_num (NUMERAL 0))) \/ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0)))) /\ (((y0 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem x0 y0))) /\ ((y0 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem x0 y0) (int_abs y0)))).
Definition term106 (x0 : int) (x1 : int) := (~ (int_le (int_of_num (NUMERAL 0)) (rem x0 x1))) -> int_le (int_of_num (NUMERAL 0)) (rem x0 x1).
Definition term102 (x0 : int) (x1 : int) := (int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) \/ (x1 = (int_of_num (NUMERAL 0))).
Definition term44 (x0 : Prop) := (~ x0) -> False.
Definition term35 (x0 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) x0).
Definition term58 (x0 : int) (x1 : int) := (~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> ~ (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))).
Definition term32 (x0 : int) (x1 : int) := rem (rem x0 x1) x1.
Definition term105 (x0 : int) (x1 : int) := (~ (x1 = (int_of_num (NUMERAL 0)))) -> int_le (int_of_num (NUMERAL 0)) (rem x0 x1).
Definition term23 (x0 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, (exists y3 : int, (y0 = (int_add (int_mul y3 y1) y2)) /\ ((int_le (int_of_num (NUMERAL 0)) y2) /\ (int_lt y2 (int_abs y1)))) -> (rem y0 y1) = y2) x0.
Definition term6 (x0 : int) := (fun y0 : int => forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = (int_add (int_mul y2 y1) y3)) /\ ((int_le (int_of_num (NUMERAL 0)) y3) /\ (int_lt y3 (int_abs y1)))) -> (rem y0 y1) = y3) x0.
Definition term45 (x0 : int) (x1 : int) := (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> False.
Definition term2 (x0 : int) := (fun y0 : int => (int_mul (int_of_num (NUMERAL 0)) y0) = (int_of_num (NUMERAL 0))) x0.
Definition term78 (x0 : int) (x1 : int) := (~ (~ (x1 = (int_of_num (NUMERAL 0))))) \/ ((x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))).
Definition term95 (x0 : int) (x1 : int) := ~ (int_lt (rem x0 x1) (int_abs x1)).
Definition term72 (x0 : int) (x1 : int) := int_le (int_of_num (NUMERAL 0)) (rem x0 x1).
Definition term104 (x0 : Prop) (x1 : Prop) := (~ x0) -> x1.
Definition term34 (x0 : int) (x1 : int) := (exists y0 : int, ((rem x0 x1) = (int_add (int_mul y0 x1) (rem x0 x1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (rem (rem x0 x1) x1) = (rem x0 x1).
Definition term43 (x0 : int) (x1 : int) := True /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1))).
Definition term107 (x0 : Prop) := (~ x0) -> x0.
Definition term3 (x0 : int) := int_mul (int_of_num (NUMERAL 0)) x0.
Definition term0 (x0 : int) := (fun y0 : int => (int_add (int_of_num (NUMERAL 0)) y0) = y0) x0.
Definition term97 (x0 : int) (x1 : int) := (fun y0 : int => ((y0 = (int_of_num (NUMERAL 0))) \/ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0)))) /\ (((y0 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem x0 y0))) /\ ((y0 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem x0 y0) (int_abs y0))))) x1.
Definition term87 (x0 : int) (x1 : int) := ((x1 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem x0 x1))) /\ ((x1 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem x0 x1) (int_abs x1))).
Definition term110 (x0 : int) (x1 : int) := (int_lt (rem x0 x1) (int_abs x1)) \/ (x1 = (int_of_num (NUMERAL 0))).
Definition term67 (x0 : int) (x1 : int) := (~ (x1 = (int_of_num (NUMERAL 0)))) -> (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1))).
Definition term1 (x0 : int) := int_add (int_of_num (NUMERAL 0)) x0.
Definition term18 (x0 : int) (x1 : int) (x2 : int) := (exists y0 : int, (x0 = (int_add (int_mul y0 x1) x2)) /\ ((int_le (int_of_num (NUMERAL 0)) x2) /\ (int_lt x2 (int_abs x1)))) -> (rem x0 x1) = x2.
Definition term116 (x0 : int) (x1 : int) := (fun y0 : int => (~ (x0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y0 x0)) /\ (int_lt (rem y0 x0) (int_abs x0)))) -> (forall y1 : int, forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) -> (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ (int_lt (rem y1 y2) (int_abs y2)))) -> False) x1.
Definition term55 (x0 : int) (x1 : int) := (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False.
Definition term51 := (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False.
Definition term61 (x0 : int) := forall y0 : int, (~ (x0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y0 x0)) /\ (int_lt (rem y0 x0) (int_abs x0)))) -> (forall y1 : int, forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) -> (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ (int_lt (rem y1 y2) (int_abs y2)))) -> False.
Definition term75 (x0 : int) (x1 : int) := (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1))).
Definition term36 := int_add (int_of_num (NUMERAL 0)).
Definition term118 (x0 : int) (x1 : int) := fun y0 : int => ((rem x0 x1) = (int_add (int_mul y0 x1) (rem x0 x1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1))).
Definition term99 (x0 : int) (x1 : int) := (x1 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem x0 x1) (int_abs x1)).
Definition term120 := forall y0 : int, forall y1 : int, (rem (rem y0 y1) y1) = (rem y0 y1).
Definition term93 := forall y0 : int, forall y1 : int, ((y1 = (int_of_num (NUMERAL 0))) \/ (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1)))) /\ (((y1 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem y0 y1))) /\ ((y1 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem y0 y1) (int_abs y1)))).
Definition term83 := forall y0 : int, forall y1 : int, (y1 = (int_of_num (NUMERAL 0))) \/ ((y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))).
Definition term66 := forall y0 : int, forall y1 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y0)) /\ (int_lt (rem y1 y0) (int_abs y0)))) -> ~ (forall y2 : int, forall y3 : int, (~ (y3 = (int_of_num (NUMERAL 0)))) -> (y2 = (int_add (int_mul (div y2 y3) y3) (rem y2 y3))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y2 y3)) /\ (int_lt (rem y2 y3) (int_abs y3)))).
Definition term65 := forall y0 : int, forall y1 : int, (~ (y0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y0)) /\ (int_lt (rem y1 y0) (int_abs y0)))) -> (forall y2 : int, forall y3 : int, (~ (y3 = (int_of_num (NUMERAL 0)))) -> (y2 = (int_add (int_mul (div y2 y3) y3) (rem y2 y3))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y2 y3)) /\ (int_lt (rem y2 y3) (int_abs y3)))) -> False.
Definition term53 := forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1))).
Definition term21 := forall y0 : int, forall y1 : int, forall y2 : int, (exists y3 : int, (y0 = (int_add (int_mul y3 y1) y2)) /\ ((int_le (int_of_num (NUMERAL 0)) y2) /\ (int_lt y2 (int_abs y1)))) -> (rem y0 y1) = y2.
Definition term20 (x0 : int) := forall y0 : int, forall y1 : int, (exists y2 : int, (x0 = (int_add (int_mul y2 y0) y1)) /\ ((int_le (int_of_num (NUMERAL 0)) y1) /\ (int_lt y1 (int_abs y0)))) -> (rem x0 y0) = y1.
Definition term9 (x0 : int) (x1 : int) := forall y0 : int, forall y1 : int, ((x0 = (int_add (int_mul y0 x1) y1)) /\ ((int_le (int_of_num (NUMERAL 0)) y1) /\ (int_lt y1 (int_abs x1)))) -> (rem x0 x1) = y1.
Definition term7 (x0 : int) := forall y0 : int, forall y1 : int, forall y2 : int, ((x0 = (int_add (int_mul y1 y0) y2)) /\ ((int_le (int_of_num (NUMERAL 0)) y2) /\ (int_lt y2 (int_abs y0)))) -> (rem x0 y0) = y2.
Definition term5 := forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = (int_add (int_mul y2 y1) y3)) /\ ((int_le (int_of_num (NUMERAL 0)) y3) /\ (int_lt y3 (int_abs y1)))) -> (rem y0 y1) = y3.
Definition term79 (x0 : int) (x1 : int) := (x1 = (int_of_num (NUMERAL 0))) \/ ((x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))).
Definition term94 (x0 : int) (x1 : int) := ~ (int_le (int_of_num (NUMERAL 0)) (rem x0 x1)).
Definition term19 (x0 : int) (x1 : int) := forall y0 : int, (exists y1 : int, (x0 = (int_add (int_mul y1 x1) y0)) /\ ((int_le (int_of_num (NUMERAL 0)) y0) /\ (int_lt y0 (int_abs x1)))) -> (rem x0 x1) = y0.
Definition term111 (x0 : int) (x1 : int) := @eq Prop ((x1 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem x0 x1) (int_abs x1))).
Definition term81 (x0 : int) := forall y0 : int, (y0 = (int_of_num (NUMERAL 0))) \/ ((x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ (int_lt (rem x0 y0) (int_abs y0)))).
Definition term15 (x0 : int) (x1 : int) (x2 : int) := (forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = (int_add (int_mul y2 y1) y3)) /\ ((int_le (int_of_num (NUMERAL 0)) y3) /\ (int_lt y3 (int_abs y1)))) -> (rem y0 y1) = y3) -> (rem x0 x1) = x2.
Definition term25 (x0 : int) (x1 : int) (x2 : int) := (fun y0 : int => (exists y1 : int, (x0 = (int_add (int_mul y1 x1) y0)) /\ ((int_le (int_of_num (NUMERAL 0)) y0) /\ (int_lt y0 (int_abs x1)))) -> (rem x0 x1) = y0) x2.
Definition term100 (x0 : int) := (x0 = (int_of_num (NUMERAL 0))) -> ~ (x0 = (int_of_num (NUMERAL 0))).
Definition term114 (x0 : int) (x1 : int) := (int_lt (rem x0 x1) (int_abs x1)) -> False.
Definition term86 (x0 : int) (x1 : int) := (x1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1))).
Definition term50 (x0 : int) (x1 : int) := (((~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False) -> (~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False) -> ((~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False) -> (~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False.
Definition term33 (x0 : int) (x1 : int) := @eq int (rem (rem x0 x1) x1).
Definition term28 (x0 : int) := ~ (x0 = (int_of_num (NUMERAL 0))).
Definition term22 := (forall y0 : int, forall y1 : int, forall y2 : int, forall y3 : int, ((y0 = (int_add (int_mul y2 y1) y3)) /\ ((int_le (int_of_num (NUMERAL 0)) y3) /\ (int_lt y3 (int_abs y1)))) -> (rem y0 y1) = y3) -> forall y0 : int, forall y1 : int, forall y2 : int, (exists y3 : int, (y0 = (int_add (int_mul y3 y1) y2)) /\ ((int_le (int_of_num (NUMERAL 0)) y2) /\ (int_lt y2 (int_abs y1)))) -> (rem y0 y1) = y2.
Definition term39 (x0 : int) (x1 : int) := @eq int (rem x0 x1).
Definition term52 := ~ (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))).
Definition term13 (x0 : int) (x1 : int) (x2 : int) (x3 : int) := ((x1 = (int_add (int_mul x0 x2) x3)) /\ ((int_le (int_of_num (NUMERAL 0)) x3) /\ (int_lt x3 (int_abs x2)))) -> (rem x1 x2) = x3.
Definition term98 (x0 : int) (x1 : int) := (x1 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem x0 x1)).
Definition term88 (x0 : int) (x1 : int) := and ((x1 = (int_of_num (NUMERAL 0))) \/ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))).
Definition term38 (x0 : int) (x1 : int) := int_add (int_of_num (NUMERAL 0)) (rem x0 x1).
Definition term89 (x0 : int) (x1 : int) := ((x1 = (int_of_num (NUMERAL 0))) \/ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))) /\ (((x1 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem x0 x1))) /\ ((x1 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem x0 x1) (int_abs x1)))).
Definition term60 (x0 : int) := fun y0 : int => (~ (x0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y0 x0)) /\ (int_lt (rem y0 x0) (int_abs x0)))) -> ~ (forall y1 : int, forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) -> (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ (int_lt (rem y1 y2) (int_abs y2)))).
Definition term56 (x0 : int) (x1 : int) := (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> ~ (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))).
Definition term57 (x0 : int) := imp (~ (x0 = (int_of_num (NUMERAL 0)))).
Definition term37 (x0 : int) (x1 : int) := int_add (int_mul (int_of_num (NUMERAL 0)) x1) (rem x0 x1).
Definition term112 (x0 : int) (x1 : int) := (~ (x1 = (int_of_num (NUMERAL 0)))) -> int_lt (rem x0 x1) (int_abs x1).
Definition term90 (x0 : int) := fun y0 : int => ((y0 = (int_of_num (NUMERAL 0))) \/ (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0)))) /\ (((y0 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem x0 y0))) /\ ((y0 = (int_of_num (NUMERAL 0))) \/ (int_lt (rem x0 y0) (int_abs y0)))).
Definition term59 (x0 : int) := fun y0 : int => (~ (x0 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem y0 x0)) /\ (int_lt (rem y0 x0) (int_abs x0)))) -> (forall y1 : int, forall y2 : int, (~ (y2 = (int_of_num (NUMERAL 0)))) -> (y1 = (int_add (int_mul (div y1 y2) y2) (rem y1 y2))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y1 y2)) /\ (int_lt (rem y1 y2) (int_abs y2)))) -> False.
Definition term108 (x0 : int) (x1 : int) := (int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) -> False.
Definition term74 (x0 : int) := ~ (~ (x0 = (int_of_num (NUMERAL 0)))).
Definition term49 (x0 : int) (x1 : int) := (((~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False) -> (~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False) -> (~ (x1 = (int_of_num (NUMERAL 0)))) -> (~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))) -> (forall y0 : int, forall y1 : int, (~ (y1 = (int_of_num (NUMERAL 0)))) -> (y0 = (int_add (int_mul (div y0 y1) y1) (rem y0 y1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem y0 y1)) /\ (int_lt (rem y0 y1) (int_abs y1)))) -> False.
Definition term31 (x0 : int) (x1 : int) := rem (rem x0 x1).
Definition term11 (x0 : int) (x1 : int) (x2 : int) := forall y0 : int, ((x1 = (int_add (int_mul x0 x2) y0)) /\ ((int_le (int_of_num (NUMERAL 0)) y0) /\ (int_lt y0 (int_abs x2)))) -> (rem x1 x2) = y0.
Definition term71 (x0 : int) (x1 : int) := (~ (int_le (int_of_num (NUMERAL 0)) (rem x0 x1))) \/ (~ (int_lt (rem x0 x1) (int_abs x1))).
Definition term68 (x0 : int) := fun y0 : int => (~ (y0 = (int_of_num (NUMERAL 0)))) -> (x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ (int_lt (rem x0 y0) (int_abs y0))).
Definition term30 (x0 : int) := rem x0 (int_of_num (NUMERAL 0)).
Definition term41 (x0 : int) (x1 : int) := (int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)).
Definition term85 (x0 : int) (x1 : int) := int_add (int_mul (div x0 x1) x1) (rem x0 x1).
Definition term84 (x0 : int) (x1 : int) := ((x1 = (int_of_num (NUMERAL 0))) \/ (x0 = (int_add (int_mul (div x0 x1) x1) (rem x0 x1)))) /\ ((x1 = (int_of_num (NUMERAL 0))) \/ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1)))).
Definition term26 (x0 : int) := (fun y0 : Prop => y0 \/ (~ y0)) (x0 = (int_of_num (NUMERAL 0))).
Definition term29 (x0 : int) := (fun y0 : int => (rem y0 (int_of_num (NUMERAL 0))) = y0) x0.
Definition term80 (x0 : int) := fun y0 : int => (y0 = (int_of_num (NUMERAL 0))) \/ ((x0 = (int_add (int_mul (div x0 y0) y0) (rem x0 y0))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 y0)) /\ (int_lt (rem x0 y0) (int_abs y0)))).
Definition term119 (x0 : int) := forall y0 : int, (rem (rem x0 y0) y0) = (rem x0 y0).
Definition term73 (x0 : int) (x1 : int) := int_lt (rem x0 x1) (int_abs x1).
Definition term77 (x0 : int) := or (x0 = (int_of_num (NUMERAL 0))).
Definition term76 (x0 : int) := or (~ (~ (x0 = (int_of_num (NUMERAL 0))))).
Definition term103 (x0 : int) (x1 : int) := @eq Prop ((x1 = (int_of_num (NUMERAL 0))) \/ (int_le (int_of_num (NUMERAL 0)) (rem x0 x1))).
Definition term46 (x0 : int) (x1 : int) := ~ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1))).
Definition term17 (x0 : int) (x1 : int) (x2 : int) := fun y0 : int => (x0 = (int_add (int_mul y0 x2) x1)) /\ ((int_le (int_of_num (NUMERAL 0)) x1) /\ (int_lt x1 (int_abs x2))).
Definition term42 (x0 : int) (x1 : int) := ((rem x0 x1) = (int_add (int_mul (int_of_num (NUMERAL 0)) x1) (rem x0 x1))) /\ ((int_le (int_of_num (NUMERAL 0)) (rem x0 x1)) /\ (int_lt (rem x0 x1) (int_abs x1))).
Definition term101 (x0 : Prop) := x0 -> ~ x0.
