Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term61 (x0 : real) (x1 : real) := real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1).
Definition term25 (x0 : real) := fun y0 : real => ((~ (x0 = y0)) /\ ((~ (real_lt x0 y0)) /\ (~ (real_lt y0 x0)))) \/ ((x0 = y0) /\ ((real_lt x0 y0) \/ (real_lt y0 x0))).
Definition term182 := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term17 (x0 : real -> Prop) := ~ (all x0).
Definition term51 := Nat.pow (BIT1 0) (NUMERAL (BIT0 (BIT1 0))).
Definition term8 (x0 : real) (x1 : real) := and (~ (x0 = x1)).
Definition term142 := (exists y0 : real, exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ (exists y0 : real, exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))).
Definition term63 (x0 : real) (x1 : real) := real_gt (real_neg (real_sub x0 x1)) (real_of_num (NUMERAL 0)).
Definition term62 := real_of_num (NUMERAL 0).
Definition term151 (x0 : real) := fun y0 : real => (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) \/ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))))) \/ ((((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) \/ (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))))).
Definition term91 (x0 : real) (x1 : real) := or (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))))).
Definition term160 (x0 : real) (x1 : real) := (real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))).
Definition term84 (x0 : real) (x1 : real) := @eq real (real_sub x0 x1).
Definition term200 (x0 : real) (x1 : real) := real_gt (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)) (real_of_num (NUMERAL 0)).
Definition term196 (x0 : real) (x1 : real) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0)).
Definition term98 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := (exists y0 : a0, x0 y0) \/ (exists y0 : a0, x1 y0).
Definition term155 (x0 : real) (x1 : real) := (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))).
Definition term163 (x0 : real) (x1 : real) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)) (real_of_num (NUMERAL 0)).
Definition term218 (x0 : real) (x1 : real) := (fun y0 : real => (real_mul y0 (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) = (real_of_num (NUMERAL 0))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term177 (x0 : real) (x1 : real) := real_add (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0)) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1) x1).
Definition term19 (x0 : real) := ~ (forall y0 : real, (~ (x0 = y0)) = ((real_lt x0 y0) \/ (real_lt y0 x0))).
Definition term107 (x0 : real) (x1 : real) := (fun y0 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))))) x1.
Definition term176 (x0 : real) (x1 : real) := real_add (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1).
Definition term189 (x0 : real) (x1 : real) := real_gt (real_add (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)).
Definition term128 (x0 : real) := or ((fun y0 : real => exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) x0).
Definition term1 (x0 : real) (x1 : real) := ~ ((real_lt x1 x0) \/ (real_lt x0 x1)).
Definition term149 (x0 : real) (x1 : real) := or (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))))) \/ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))))).
Definition term68 (x0 : real) (x1 : real) := real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)).
Definition term23 (x0 : real) (x1 : real) := ~ ((fun y0 : real => (~ (x0 = y0)) = ((real_lt x0 y0) \/ (real_lt y0 x0))) x1).
Definition term59 (x0 : real) (x1 : real) := @eq real (real_neg (real_sub x0 x1)).
Definition term22 (x0 : real) (x1 : real) := (fun y0 : real => (~ (x0 = y0)) = ((real_lt x0 y0) \/ (real_lt y0 x0))) x1.
Definition term86 (x0 : real) (x1 : real) := or (real_lt x0 x1).
Definition term78 (x0 : real) (x1 : real) := real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)).
Definition term81 (x0 : real) (x1 : real) := (real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))).
Definition term58 (x0 : real) (x1 : real) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1.
Definition term169 (x0 : real) (x1 : real) := real_gt (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0)).
Definition term71 (x0 : real) (x1 : real) := (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))).
Definition term148 (x0 : real) (x1 : real) := ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))))) \/ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))))).
Definition term92 (x0 : real) (x1 : real) := (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))))) \/ (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))))).
Definition term9 (x0 : real) (x1 : real) := (~ (x1 = x0)) /\ (~ ((real_lt x1 x0) \/ (real_lt x0 x1))).
Definition term158 := Peano.lt (NUMERAL 0) (NUMERAL (BIT1 0)).
Definition term118 (x0 : real) := exists y0 : real, (fun y1 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) y0.
Definition term113 (x0 : real) := exists y0 : real, (fun y1 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))))) y0.
Definition term225 := forall y0 : real, forall y1 : real, (~ (y0 = y1)) = ((real_lt y0 y1) \/ (real_lt y1 y0)).
Definition term44 (x0 : real) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0).
Definition term207 (x0 : real) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x0).
Definition term154 := exists y0 : real, exists y1 : real, (((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))))) \/ ((((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) \/ (((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))).
Definition term141 := exists y0 : real, exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0)))).
Definition term136 := exists y0 : real, exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))).
Definition term96 := exists y0 : real, exists y1 : real, (((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ (((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))).
Definition term35 := exists y0 : real, exists y1 : real, ((~ (y0 = y1)) /\ ((~ (real_lt y0 y1)) /\ (~ (real_lt y1 y0)))) \/ ((y0 = y1) /\ ((real_lt y0 y1) \/ (real_lt y1 y0))).
Definition term48 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term137 := or (exists y0 : real, (fun y1 : real => exists y2 : real, ((real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))))) y0).
Definition term115 (x0 : real) := or (exists y0 : real, (fun y1 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))))) y0).
Definition term170 (x0 : real) (x1 : real) := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term21 (x0 : real) := fun y0 : real => (~ (x0 = y0)) = ((real_lt x0 y0) \/ (real_lt y0 x0)).
Definition term14 (x0 : real) (x1 : real) := ((~ (x1 = x0)) /\ ((~ (real_lt x1 x0)) /\ (~ (real_lt x0 x1)))) \/ ((x1 = x0) /\ ((real_lt x1 x0) \/ (real_lt x0 x1))).
Definition term60 (x0 : real) (x1 : real) := real_gt (real_neg (real_sub x0 x1)).
Definition term204 (x0 : real) (x1 : real) := real_gt (real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0)).
Definition term213 (x0 : real) (x1 : real) := (fun y0 : real => (real_mul y0 (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) = (real_of_num (NUMERAL 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term28 := exists y0 : real, ~ ((fun y1 : real => forall y2 : real, (~ (y1 = y2)) = ((real_lt y1 y2) \/ (real_lt y2 y1))) y0).
Definition term20 (x0 : real) := exists y0 : real, ~ ((fun y1 : real => (~ (x0 = y1)) = ((real_lt x0 y1) \/ (real_lt y1 x0))) y0).
Definition term129 (x0 : real) := (fun y0 : real => exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) x0.
Definition term127 (x0 : real) := (fun y0 : real => exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) x0.
Definition term66 (x0 : real) (x1 : real) := real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term77 (x0 : real) (x1 : real) := real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1).
Definition term89 (x0 : real) (x1 : real) := and ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))).
Definition term69 (x0 : real) (x1 : real) := or (real_gt (real_sub x0 x1) (real_of_num (NUMERAL 0))).
Definition term33 := fun y0 : real => ~ ((fun y1 : real => forall y2 : real, (~ (y1 = y2)) = ((real_lt y1 y2) \/ (real_lt y2 y1))) y0).
Definition term90 (x0 : real) (x1 : real) := ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)))).
Definition term209 (x0 : real) (x1 : real) := ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))).
Definition term31 (x0 : real) := forall y0 : real, (~ (x0 = y0)) = ((real_lt x0 y0) \/ (real_lt y0 x0)).
Definition term29 := fun y0 : real => forall y1 : real, (~ (y0 = y1)) = ((real_lt y0 y1) \/ (real_lt y1 y0)).
Definition term76 (x0 : real) (x1 : real) := real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)).
Definition term130 (x0 : real) := ((fun y0 : real => exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) x0) \/ ((fun y0 : real => exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) x0).
Definition term180 (x0 : nat) := real_add (real_neg (real_of_num x0)) (real_of_num x0).
Definition term52 := Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)).
Definition term82 (x0 : real) (x1 : real) := and ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))).
Definition term15 (x0 : real) (x1 : real) := ~ ((~ (x1 = x0)) = ((real_lt x1 x0) \/ (real_lt x0 x1))).
Definition term16 (x0 : real) (x1 : real) := ~ (x0 = x1).
Definition term99 (x0 : real -> Prop) (x1 : real -> Prop) := exists y0 : real, (x0 y0) \/ (x1 y0).
Definition term120 (x0 : real) := (exists y0 : real, ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) \/ (exists y0 : real, ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))))).
Definition term27 := ~ (forall y0 : real, forall y1 : real, (~ (y0 = y1)) = ((real_lt y0 y1) \/ (real_lt y1 y0))).
Definition term192 := Peano.lt (NUMERAL 0) (NUMERAL 0).
Definition term72 (x0 : real) (x1 : real) := ~ (real_lt x0 x1).
Definition term211 (x0 : real) (x1 : real) := ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) -> forall y0 : real, (real_mul y0 (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) = (real_of_num (NUMERAL 0)).
Definition term139 := fun y0 : real => (fun y1 : real => exists y2 : real, ((real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))))) y0.
Definition term134 := fun y0 : real => (fun y1 : real => exists y2 : real, ((real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))))) y0.
Definition term194 (x0 : real) (x1 : real) := (real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term100 (x0 : real -> Prop) (x1 : real -> Prop) := (exists y0 : real, x0 y0) \/ (exists y0 : real, x1 y0).
Definition term191 := real_gt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0)).
Definition term12 (x0 : real) (x1 : real) := or ((~ (x1 = x0)) /\ ((~ (real_lt x1 x0)) /\ (~ (real_lt x0 x1)))).
Definition term56 (x0 : real) := real_mul (real_of_num (NUMERAL (BIT1 0))) x0.
Definition term185 (x0 : real) := real_add (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0)).
Definition term32 (x0 : real) := ~ ((fun y0 : real => forall y1 : real, (~ (y0 = y1)) = ((real_lt y0 y1) \/ (real_lt y1 y0))) x0).
Definition term153 := fun y0 : real => exists y1 : real, (((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))))) \/ ((((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) \/ (((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))).
Definition term126 := fun y0 : real => exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0)))).
Definition term125 := fun y0 : real => exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))).
Definition term95 := fun y0 : real => exists y1 : real, (((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ (((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))).
Definition term34 := fun y0 : real => exists y1 : real, ((~ (y0 = y1)) /\ ((~ (real_lt y0 y1)) /\ (~ (real_lt y1 y0)))) \/ ((y0 = y1) /\ ((real_lt y0 y1) \/ (real_lt y1 y0))).
Definition term217 (x0 : real) (x1 : real) := ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term187 (x0 : real) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x0.
Definition term54 := real_mul (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term161 (x0 : real) (x1 : real) := ((real_gt x0 (real_of_num (NUMERAL 0))) /\ (real_ge x1 (real_of_num (NUMERAL 0)))) -> real_ge (real_mul x0 x1) (real_of_num (NUMERAL 0)).
Definition term133 := @eq Prop (exists y0 : real, (exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ (exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0)))))).
Definition term132 := @eq Prop (exists y0 : real, ((fun y1 : real => exists y2 : real, ((real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))))) y0) \/ ((fun y1 : real => exists y2 : real, ((real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))))) y0)).
Definition term111 (x0 : real) := @eq Prop (exists y0 : real, (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) \/ (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0)))))).
Definition term110 (x0 : real) := @eq Prop (exists y0 : real, ((fun y1 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))))) y0) \/ ((fun y1 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) y0)).
Definition term175 (x0 : real) (x1 : real) := real_gt (real_add (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)) (real_of_num (NUMERAL 0)).
Definition term166 (x0 : real) (x1 : real) := (real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term18 (x0 : real -> Prop) := exists y0 : real, ~ (x0 y0).
Definition term147 (x0 : real) (x1 : real) := (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) \/ (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)))).
Definition term103 (x0 : real) := fun y0 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))).
Definition term30 (x0 : real) := (fun y0 : real => forall y1 : real, (~ (y0 = y1)) = ((real_lt y0 y1) \/ (real_lt y1 y0))) x0.
Definition term156 (x0 : nat) (x1 : nat) := real_gt (real_of_num x0) (real_of_num x1).
Definition term36 (x0 : real) (x1 : real) := (real_gt (real_sub x0 x1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_neg (real_sub x0 x1)) (real_of_num (NUMERAL 0))).
Definition term75 (x0 : real) (x1 : real) := real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term159 := S (Nat.add 0 0).
Definition term219 (x0 : real) (x1 : real) := @eq real (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))).
Definition term13 (x0 : real) (x1 : real) := ((~ (x1 = x0)) /\ (~ ((real_lt x1 x0) \/ (real_lt x0 x1)))) \/ ((~ (~ (x1 = x0))) /\ ((real_lt x1 x0) \/ (real_lt x0 x1))).
Definition term179 (x0 : real) := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) x0.
Definition term85 (x0 : real) (x1 : real) := @eq real (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term197 (x0 : real) (x1 : real) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))).
Definition term42 := real_neg (real_of_num (NUMERAL (BIT1 0))).
Definition term223 := (~ (forall y0 : real, forall y1 : real, (~ (y0 = y1)) = ((real_lt y0 y1) \/ (real_lt y1 y0)))) -> False.
Definition term202 (x0 : real) (x1 : real) := (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term79 (x0 : real) (x1 : real) := and (~ (real_lt x0 x1)).
Definition term165 (x0 : real) (x1 : real) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)).
Definition term206 (x0 : real) (x1 : real) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x0) (real_add x1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term87 (x0 : real) (x1 : real) := or (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))).
Definition term74 (x0 : real) (x1 : real) := real_ge (real_sub x0 x1).
Definition term201 (x0 : real) (x1 : real) := real_gt (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)).
Definition term93 (x0 : real) := fun y0 : real => (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) \/ (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))))).
Definition term164 (x0 : real) (x1 : real) := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1).
Definition term183 := real_mul (real_of_num (NUMERAL 0)).
Definition term43 (x0 : real) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0.
Definition term4 (x0 : real) (x1 : real) := and (~ (~ (x0 = x1))).
Definition term88 (x0 : real) (x1 : real) := (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term55 := real_mul (real_of_num (NUMERAL (BIT1 0))).
Definition term109 (x0 : real) := fun y0 : real => ((fun y1 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))))) y0) \/ ((fun y1 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) y0).
Definition term123 := exists y0 : real, ((fun y1 : real => exists y2 : real, ((real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))))) y0) \/ ((fun y1 : real => exists y2 : real, ((real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))))) y0).
Definition term101 (x0 : real) := exists y0 : real, ((fun y1 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))))) y0) \/ ((fun y1 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) y0).
Definition term119 (x0 : real) := exists y0 : real, ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0)))).
Definition term114 (x0 : real) := exists y0 : real, ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))).
Definition term195 (x0 : real) (x1 : real) := ((real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)))) -> real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0)).
Definition term224 := ((~ (forall y0 : real, forall y1 : real, (~ (y0 = y1)) = ((real_lt y0 y1) \/ (real_lt y1 y0)))) -> False) -> forall y0 : real, forall y1 : real, (~ (y0 = y1)) = ((real_lt y0 y1) \/ (real_lt y1 y0)).
Definition term67 (x0 : real) (x1 : real) := real_gt (real_sub x0 x1) (real_of_num (NUMERAL 0)).
Definition term70 (x0 : real) (x1 : real) := or (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term2 (x0 : real) (x1 : real) := (~ (real_lt x1 x0)) /\ (~ (real_lt x0 x1)).
Definition term171 (x0 : real) (x1 : real) := real_gt (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))).
Definition term46 (x0 : nat) (x1 : nat) := real_mul (real_neg (real_of_num x0)) (real_neg (real_of_num x1)).
Definition term83 (x0 : real) (x1 : real) := ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))).
Definition term10 (x0 : real) (x1 : real) := (~ (x1 = x0)) /\ ((~ (real_lt x1 x0)) /\ (~ (real_lt x0 x1))).
Definition term106 (x0 : real) (x1 : real) := or ((fun y0 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) x1).
Definition term49 := real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0))).
Definition term214 (x0 : real) (x1 : real) := @eq real (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))).
Definition term6 (x0 : real) (x1 : real) := (~ (~ (x1 = x0))) /\ ((real_lt x1 x0) \/ (real_lt x0 x1)).
Definition term53 := real_of_num (NUMERAL (BIT1 0)).
Definition term57 (x0 : real) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0).
Definition term117 (x0 : real) := fun y0 : real => (fun y1 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) y0.
Definition term112 (x0 : real) := fun y0 : real => (fun y1 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))))) y0.
Definition term108 (x0 : real) (x1 : real) := ((fun y0 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) x1) \/ ((fun y0 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))))) x1).
Definition term5 (x0 : real) (x1 : real) := and (x0 = x1).
Definition term184 (x0 : real) := real_mul (real_of_num (NUMERAL 0)) x0.
Definition term45 (x0 : real) := real_mul (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))) x0.
Definition term212 (x0 : real) (x1 : real) := forall y0 : real, (real_mul y0 (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) = (real_of_num (NUMERAL 0)).
Definition term24 (x0 : real) := fun y0 : real => ~ ((fun y1 : real => (~ (x0 = y1)) = ((real_lt x0 y1) \/ (real_lt y1 x0))) y0).
Definition term193 (x0 : real) (x1 : real) := (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))).
Definition term221 (x0 : real) (x1 : real) := ((real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term152 (x0 : real) := exists y0 : real, (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) \/ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))))) \/ ((((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) \/ (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))))).
Definition term94 (x0 : real) := exists y0 : real, (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) \/ (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))))).
Definition term26 (x0 : real) := exists y0 : real, ((~ (x0 = y0)) /\ ((~ (real_lt x0 y0)) /\ (~ (real_lt y0 x0)))) \/ ((x0 = y0) /\ ((real_lt x0 y0) \/ (real_lt y0 x0))).
Definition term80 (x0 : real) (x1 : real) := and (real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term3 (x0 : real) (x1 : real) := (real_lt x1 x0) \/ (real_lt x0 x1).
Definition term38 (x0 : real) (x1 : real) := real_neg (real_sub x0 x1).
Definition term162 (x0 : real) (x1 : real) := ((real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) -> real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)) (real_of_num (NUMERAL 0)).
Definition term47 (x0 : nat) (x1 : nat) := real_of_num (Nat.mul x0 x1).
Definition term7 (x0 : real) (x1 : real) := (x1 = x0) /\ ((real_lt x1 x0) \/ (real_lt x0 x1)).
Definition term11 (x0 : real) (x1 : real) := or ((~ (x1 = x0)) /\ (~ ((real_lt x1 x0) \/ (real_lt x0 x1)))).
Definition term188 := real_add (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0)).
Definition term210 (x0 : real) := (x0 = (real_of_num (NUMERAL 0))) -> forall y0 : real, (real_mul y0 x0) = (real_of_num (NUMERAL 0)).
Definition term104 (x0 : real) := fun y0 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0)))).
Definition term208 (x0 : real) (x1 : real) := real_gt (real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))).
Definition term40 (x0 : real) (x1 : real) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term37 (x0 : real) (x1 : real) := real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1).
Definition term0 (x0 : real) (x1 : real) := ~ (~ (x0 = x1)).
Definition term181 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term122 := exists y0 : real, (exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ (exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))).
Definition term222 (x0 : real) (x1 : real) := (((real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)))) -> real_gt (real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0)).
Definition term203 (x0 : real) (x1 : real) := ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)))) -> real_gt (real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0)).
Definition term168 (x0 : real) (x1 : real) := ((real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)))) -> real_gt (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0)).
Definition term131 := fun y0 : real => ((fun y1 : real => exists y2 : real, ((real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))))) y0) \/ ((fun y1 : real => exists y2 : real, ((real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))))) y0).
Definition term150 (x0 : real) (x1 : real) := (((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))))) \/ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))))) \/ ((((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) \/ (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))))).
Definition term220 (x0 : real) (x1 : real) := @eq real (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1).
Definition term65 (x0 : real) (x1 : real) := real_gt (real_sub x0 x1).
Definition term186 := real_add (real_of_num (NUMERAL 0)).
Definition term116 (x0 : real) := or (exists y0 : real, ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))).
Definition term205 (x0 : real) (x1 : real) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term138 := or (exists y0 : real, exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))).
Definition term97 (a0 : Type') (x0 : a0 -> Prop) (x1 : a0 -> Prop) := exists y0 : a0, (x0 y0) \/ (x1 y0).
Definition term216 (x0 : real) (x1 : real) := (((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) = (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) -> real_gt (real_add (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)) (real_of_num (NUMERAL 0)).
Definition term199 (x0 : real) (x1 : real) := ((real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) -> real_gt (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)) (real_of_num (NUMERAL 0)).
Definition term174 (x0 : real) (x1 : real) := ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)))) -> real_gt (real_add (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1)) (real_of_num (NUMERAL 0)).
Definition term64 (x0 : real) (x1 : real) := real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0)).
Definition term121 := fun y0 : real => (exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ (exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))).
Definition term41 (x0 : real) (x1 : real) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term105 (x0 : real) (x1 : real) := (fun y0 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) x1.
Definition term50 := NUMERAL (BIT1 0).
Definition term124 := (exists y0 : real, (fun y1 : real => exists y2 : real, ((real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))))) y0) \/ (exists y0 : real, (fun y1 : real => exists y2 : real, ((real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))))) y0).
Definition term102 (x0 : real) := (exists y0 : real, (fun y1 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))))) y0) \/ (exists y0 : real, (fun y1 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) y0).
Definition term39 (x0 : real) (x1 : real) := real_neg (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term215 (x0 : real) (x1 : real) := ((x0 = (real_of_num (NUMERAL 0))) /\ (real_gt x1 (real_of_num (NUMERAL 0)))) -> real_gt (real_add x0 x1) (real_of_num (NUMERAL 0)).
Definition term173 (x0 : real) (x1 : real) := ((real_gt x0 (real_of_num (NUMERAL 0))) /\ (real_ge x1 (real_of_num (NUMERAL 0)))) -> real_gt (real_add x0 x1) (real_of_num (NUMERAL 0)).
Definition term167 (x0 : real) (x1 : real) := ((real_gt x0 (real_of_num (NUMERAL 0))) /\ (real_gt x1 (real_of_num (NUMERAL 0)))) -> real_gt (real_mul x0 x1) (real_of_num (NUMERAL 0)).
Definition term178 (x0 : real) := real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0).
Definition term157 := real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0)).
Definition term172 (x0 : real) (x1 : real) := (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))).
Definition term140 := exists y0 : real, (fun y1 : real => exists y2 : real, ((real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))))) y0.
Definition term135 := exists y0 : real, (fun y1 : real => exists y2 : real, ((real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))))) y0.
Definition term198 (x0 : real) (x1 : real) := (real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) x1) (real_of_num (NUMERAL 0))).
Definition term73 (x0 : real) (x1 : real) := real_ge (real_sub x0 x1) (real_of_num (NUMERAL 0)).
Definition term190 := real_gt (real_of_num (NUMERAL 0)).
Definition term146 (x0 : real) := @eq Prop ((exists y0 : real, ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))))) \/ (exists y0 : real, ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y0) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0)) (real_of_num (NUMERAL 0)))))).
Definition term145 (x0 : real) := @eq Prop ((exists y0 : real, (fun y1 : real => ((real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))))) y0) \/ (exists y0 : real, (fun y1 : real => ((real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))))) y0)).
Definition term144 := @eq Prop ((exists y0 : real, exists y1 : real, ((real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))))) \/ (exists y0 : real, exists y1 : real, ((real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y0) y1) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1)) (real_of_num (NUMERAL 0)))))).
Definition term143 := @eq Prop ((exists y0 : real, (fun y1 : real => exists y2 : real, ((real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0)))) /\ ((real_ge (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))))) y0) \/ (exists y0 : real, (fun y1 : real => exists y2 : real, ((real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) = (real_of_num (NUMERAL 0))) /\ ((real_gt (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y1) y2) (real_of_num (NUMERAL 0))) \/ (real_gt (real_add y1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) y2)) (real_of_num (NUMERAL 0))))) y0)).
