Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term17 (x0 : nat) (x1 : nat) (x2 : nat) := @IN nat x0 (dotdot x1 x2).
Definition term177 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (~ (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0))) \/ ((~ (int_le (int_of_num x0) (int_of_num x1))) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))).
Definition term23 (a0 : Type') := forall y0 : a0, forall y1 : a0 -> real, forall y2 : a0 -> Prop, (@FINITE a0 y2) -> (@sum a0 (@INSERT a0 y0 y2) y1) = (@COND real (@IN a0 y0 y2) (@sum a0 y2 y1) (real_add (y1 y0) (@sum a0 y2 y1))).
Definition term5 (x0 : nat) := fun y0 : nat => (Peano.le x0 y0) -> (dotdot x0 y0) = (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0)).
Definition term206 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (int_le (int_of_num (NUMERAL 0)) x1) /\ (~ ((~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))).
Definition term317 := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term399 := real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term253 (x0 : nat) := real_div (real_neg (real_of_num x0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term339 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x0)) (real_add (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term150 (x0 : nat) (x1 : nat -> real) := @eq Prop ((~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ (forall y0 : nat, (~ (Peano.le x0 y0)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))))).
Definition term149 (x0 : nat) (x1 : nat -> real) := @eq Prop ((~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ (forall y0 : nat, (fun y1 : nat => (~ (Peano.le x0 y1)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1)))) y0)).
Definition term265 := Nat.pow (BIT1 0) (NUMERAL (BIT0 (BIT1 0))).
Definition term140 (a0 : Type') (x0 : Prop) (x1 : a0 -> Prop) := x0 \/ (forall y0 : a0, x1 y0).
Definition term294 (x0 : int) := real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)).
Definition term345 (x0 : nat -> real) (x1 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1)).
Definition term121 (x0 : nat -> real) (x1 : nat) := ((~ (Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1)) \/ (forall y0 : nat, (Peano.le x1 y0) -> (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0)))) /\ ((Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1) \/ True).
Definition term328 (x0 : int) (x1 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1).
Definition term369 (x0 : nat) (x1 : nat) (x2 : nat -> real) := or (real_gt (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) (real_of_num (NUMERAL 0))).
Definition term214 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (int_le (int_of_num (NUMERAL 0)) x1) -> (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))).
Definition term301 (x0 : nat) (x1 : nat) := real_lt (real_of_num x0) (real_of_num x1).
Definition term326 (x0 : int) (x1 : int) := real_sub (real_of_int x0) (real_of_int x1).
Definition term277 (x0 : int) := real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0))))).
Definition term409 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (int_le (int_of_num (NUMERAL 0)) (int_of_num x1)) -> (~ (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0))) \/ ((~ (int_le (int_of_num x0) (int_of_num x1))) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))).
Definition term308 := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term70 (x0 : nat) := and (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0).
Definition term309 := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term338 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_add (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x0)) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term103 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @COND real False (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term89 (x0 : nat) (x1 : nat -> real) := fun y0 : nat => (Peano.le x0 y0) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)).
Definition term252 (x0 : nat) := real_neg (real_of_num x0).
Definition term67 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) (x4 : real) (x5 : real) := (fun y0 : real => ((@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) = x3) -> (x3 -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = x4) -> ((~ x3) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = y0) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real x3 x4 y0)) x5.
Definition term169 (x0 : nat) := int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0).
Definition term116 (x0 : nat) (x1 : nat -> real) := forall y0 : nat, (Peano.le x0 y0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)).
Definition term91 (x0 : nat) (x1 : nat -> real) := forall y0 : nat, (Peano.le x0 y0) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)).
Definition term90 (x0 : nat) (x1 : nat -> real) := forall y0 : nat, (Peano.le x0 y0) -> (@sum nat (dotdot x0 y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)).
Definition term7 (x0 : nat) := forall y0 : nat, (Peano.le x0 y0) -> (dotdot x0 y0) = (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0)).
Definition term219 := real_of_int (int_of_num (NUMERAL 0)).
Definition term245 (x0 : Prop) := ~ (~ x0).
Definition term220 := real_of_num (NUMERAL 0).
Definition term12 (x0 : nat) := (fun y0 : nat => forall y1 : nat, forall y2 : nat, (@IN nat y2 (dotdot y0 y1)) = ((Peano.le y0 y2) /\ (Peano.le y2 y1))) x0.
Definition term189 (x0 : int) := int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0.
Definition term371 (x0 : nat -> real) (x1 : nat) := (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1)) (real_of_num (NUMERAL 0))) \/ (real_gt (x0 x1) (real_of_num (NUMERAL 0))).
Definition term292 (x0 : int) := real_add (real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term100 (x0 : nat) := @COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0).
Definition term213 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := ~ ((int_le (int_of_num (NUMERAL 0)) x0) -> (int_le (int_of_num (NUMERAL 0)) x1) -> (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))).
Definition term66 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) (x4 : real) := forall y0 : real, ((@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) = x3) -> (x3 -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = x4) -> ((~ x3) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = y0) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real x3 x4 y0).
Definition term0 (x0 : nat) (x1 : nat) := @INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1).
Definition term200 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (~ (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0))) /\ (~ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))).
Definition term194 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (~ (~ (int_le x0 x1))) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))).
Definition term79 (x0 : nat) := ~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0).
Definition term217 := int_of_num (NUMERAL 0).
Definition term153 (x0 : nat) (x1 : nat -> real) := fun y0 : nat => (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ ((fun y1 : nat => (~ (Peano.le x0 y1)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1)))) y0).
Definition term115 (x0 : nat) (x1 : nat -> real) := fun y0 : nat => (Peano.le x0 y0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)).
Definition term88 (x0 : nat) (x1 : nat -> real) := fun y0 : nat => (Peano.le x0 y0) -> (@sum nat (dotdot x0 y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)).
Definition term168 (x0 : nat) := int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))).
Definition term406 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := ((~ (~ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x0)) /\ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x1)) /\ ((real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ ((real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))))))) -> False) -> ~ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x0)) /\ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x1)) /\ ((real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ ((real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))))).
Definition term307 := ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term311 := real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term4 (x0 : nat) := fun y0 : nat => (Peano.le x0 y0) -> (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0)) = (dotdot x0 y0).
Definition term275 (x0 : int) := real_ge (real_sub (real_of_int x0) (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL 0)).
Definition term329 (x0 : int) (x1 : int) := real_ge (real_sub (real_of_int x0) (real_of_int x1)).
Definition term132 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (~ (Peano.le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term108 (a0 : Type') (x0 : Prop) := forall y0 : a0, x0.
Definition term375 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ ((real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))) \/ (real_gt (x2 x3) (real_of_num (NUMERAL 0))))).
Definition term293 (x0 : int) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0).
Definition term395 := real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term120 (x0 : nat -> real) (x1 : nat) := ((((Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1) = False) -> (forall y0 : nat, (Peano.le x1 y0) -> (@COND real (Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0) (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0))) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0))) = True) /\ (((Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1) = True) -> (forall y0 : nat, (Peano.le x1 y0) -> (@COND real (Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0) (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0))) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0))) = (forall y0 : nat, (Peano.le x1 y0) -> (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0))))) -> (forall y0 : nat, (Peano.le x1 y0) -> (@COND real (Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0) (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0))) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0))) = (((~ (Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1)) \/ (forall y0 : nat, (Peano.le x1 y0) -> (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) y0) x0)))) /\ ((Peano.le (Nat.add x1 (NUMERAL (BIT1 0))) x1) \/ True)).
Definition term372 (x0 : int) (x1 : int) := and (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))).
Definition term77 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : real) := ((~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = x3) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) x3).
Definition term141 (a0 : Type') (x0 : Prop) (x1 : a0 -> Prop) := forall y0 : a0, x0 \/ (x1 y0).
Definition term144 (x0 : nat) (x1 : nat -> real) := (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ (forall y0 : nat, (fun y1 : nat => (~ (Peano.le x0 y1)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1)))) y0).
Definition term46 (x0 : nat) (x1 : nat) := @sum nat (dotdot x0 x1).
Definition term186 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := ~ (~ ((int_le (int_of_num (NUMERAL 0)) x0) -> (int_le (int_of_num (NUMERAL 0)) x1) -> (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))).
Definition term44 (x0 : nat -> real) (x1 : nat) (x2 : nat) (x3 : Prop) := ((Peano.le x1 x2) = (Peano.le x1 x2)) -> ((Peano.le x1 x2) -> ((@sum nat (dotdot x1 x2) x0) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) x2) x0))) = x3) -> ((Peano.le x1 x2) -> (@sum nat (dotdot x1 x2) x0) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) x2) x0))) = ((Peano.le x1 x2) -> x3).
Definition term182 := fun y0 : nat -> real => forall y1 : nat, forall y2 : nat, (~ (int_le (int_add (int_of_num y1) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num y1))) \/ ((~ (int_le (int_of_num y1) (int_of_num y2))) \/ ((@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)))).
Definition term158 := fun y0 : nat -> real => forall y1 : nat, forall y2 : nat, (~ (Peano.le (Nat.add y1 (NUMERAL (BIT1 0))) y1)) \/ ((~ (Peano.le y1 y2)) \/ ((@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)))).
Definition term97 := fun y0 : nat -> real => forall y1 : nat, forall y2 : nat, (Peano.le y1 y2) -> (@COND real (Peano.le (Nat.add y1 (NUMERAL (BIT1 0))) y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0))) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)).
Definition term96 := fun y0 : nat -> real => forall y1 : nat, forall y2 : nat, (Peano.le y1 y2) -> (@sum nat (dotdot y1 y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)).
Definition term260 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term282 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term33 (x0 : nat) (x1 : nat) := (fun y0 : nat => (Peano.le x0 y0) -> (dotdot x0 y0) = (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0))) x1.
Definition term296 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term228 (x0 : int) := real_of_int (int_add x0 (int_of_num (NUMERAL (BIT1 0)))).
Definition term341 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term274 (x0 : int) := real_ge (real_of_int x0) (real_of_num (NUMERAL 0)).
Definition term379 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0)))).
Definition term195 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (int_le x0 x1) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))).
Definition term148 (x0 : nat) (x1 : nat -> real) := forall y0 : nat, (fun y1 : nat => (~ (Peano.le x0 y1)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1)))) y0.
Definition term291 (x0 : int) := real_add (real_of_int x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term175 (x0 : nat) (x1 : nat) := or (~ (int_le (int_of_num x0) (int_of_num x1))).
Definition term56 (a0 : Type') (x0 : Prop) (x1 : a0) (x2 : a0) (x3 : Prop) (x4 : a0) := forall y0 : a0, (x0 = x3) -> (x3 -> x1 = x4) -> ((~ x3) -> x2 = y0) -> (@COND a0 x0 x1 x2) = (@COND a0 x3 x4 y0).
Definition term400 (x0 : nat) (x1 : nat) := real_le (real_of_num x0) (real_neg (real_of_num x1)).
Definition term173 (x0 : nat) (x1 : nat) := ~ (int_le (int_of_num x0) (int_of_num x1)).
Definition term368 (x0 : nat -> real) (x1 : nat) := real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1)) (real_of_num (NUMERAL 0)).
Definition term238 (x0 : int) (x1 : int) := and (real_le (real_of_int x0) (real_of_int x1)).
Definition term210 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))).
Definition term152 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ ((~ (Peano.le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))).
Definition term305 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term300 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term279 (x0 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term136 (x0 : nat -> real) := fun y0 : nat => (~ (Peano.le (Nat.add y0 (NUMERAL (BIT1 0))) y0)) \/ (forall y1 : nat, (~ (Peano.le y0 y1)) \/ ((@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)))).
Definition term128 (x0 : nat -> real) := fun y0 : nat => (~ (Peano.le (Nat.add y0 (NUMERAL (BIT1 0))) y0)) \/ (forall y1 : nat, (Peano.le y0 y1) -> (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0))).
Definition term251 := real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term223 (x0 : int) := real_le (real_of_num (NUMERAL 0)) (real_of_int x0).
Definition term183 := forall y0 : nat -> real, forall y1 : nat, forall y2 : nat, (~ (int_le (int_add (int_of_num y1) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num y1))) \/ ((~ (int_le (int_of_num y1) (int_of_num y2))) \/ ((@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)))).
Definition term159 := forall y0 : nat -> real, forall y1 : nat, forall y2 : nat, (~ (Peano.le (Nat.add y1 (NUMERAL (BIT1 0))) y1)) \/ ((~ (Peano.le y1 y2)) \/ ((@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)))).
Definition term99 := forall y0 : nat -> real, forall y1 : nat, forall y2 : nat, (Peano.le y1 y2) -> (@COND real (Peano.le (Nat.add y1 (NUMERAL (BIT1 0))) y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0))) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)).
Definition term98 := forall y0 : nat -> real, forall y1 : nat, forall y2 : nat, (Peano.le y1 y2) -> (@sum nat (dotdot y1 y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)).
Definition term327 (x0 : int) (x1 : int) := real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x1)).
Definition term273 (x0 : int) := real_ge (real_of_int x0).
Definition term135 (x0 : nat) (x1 : nat -> real) := (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ (forall y0 : nat, (~ (Peano.le x0 y0)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))).
Definition term125 (x0 : nat) (x1 : nat -> real) := (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ (forall y0 : nat, (Peano.le x0 y0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))).
Definition term382 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))).
Definition term1 (x0 : nat) (x1 : nat) := imp (Peano.le x0 x1).
Definition term199 (x0 : int) := and (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0).
Definition term286 := real_neg (real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)))).
Definition term359 (x0 : nat -> real) (x1 : nat) := real_mul (real_of_num (NUMERAL (BIT1 0))) (x0 x1).
Definition term201 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0) /\ ((int_le x0 x1) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))).
Definition term197 (x0 : int) (x1 : int) := ~ (int_le x0 x1).
Definition term255 := real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term76 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : real) := ((Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) -> ((~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = x3) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) x3).
Definition term381 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))))) \/ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0))))).
Definition term393 := real_le (real_of_num (NUMERAL 0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term212 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (int_le (int_of_num (NUMERAL 0)) x0) /\ ((int_le (int_of_num (NUMERAL 0)) x1) /\ ((int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0) /\ ((int_le x0 x1) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))))).
Definition term289 (x0 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)).
Definition term272 (x0 : int) := real_ge (real_sub (real_of_int x0) (real_of_num (NUMERAL 0))).
Definition term303 := Peano.lt (NUMERAL 0) (NUMERAL (BIT1 0)).
Definition term78 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term188 (x0 : int) := ~ (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)).
Definition term229 (x0 : int) := real_add (real_of_int x0) (real_of_int (int_of_num (NUMERAL (BIT1 0)))).
Definition term267 (x0 : nat) := real_mul (real_neg (real_of_num x0)) (real_of_num (NUMERAL 0)).
Definition term64 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) := forall y0 : real, forall y1 : real, ((@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) = x3) -> (x3 -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = y0) -> ((~ x3) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = y1) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real x3 y0 y1).
Definition term20 (x0 : nat) := forall y0 : nat, @FINITE nat (dotdot x0 y0).
Definition term394 := real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term376 (x0 : int) := and (real_ge (real_of_int x0) (real_of_num (NUMERAL 0))).
Definition term127 (x0 : nat) (x1 : nat -> real) := @eq Prop (forall y0 : nat, (Peano.le x0 y0) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))).
Definition term237 (x0 : int) := real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0).
Definition term40 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) := (fun y0 : Prop => forall y1 : Prop, ((Peano.le x0 x1) = y0) -> (y0 -> ((@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = y1) -> ((Peano.le x0 x1) -> (@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (y0 -> y1)) x3.
Definition term336 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x0)) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term337 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_add (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term351 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term259 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term398 := real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term276 (x0 : int) := real_sub (real_of_int x0) (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term142 (x0 : Prop) (x1 : nat -> Prop) := x0 \/ (forall y0 : nat, x1 y0).
Definition term391 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0))))).
Definition term390 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))))).
Definition term306 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term104 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @eq real (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term299 := real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term2 (x0 : nat) (x1 : nat) := (Peano.le x0 x1) -> (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) = (dotdot x0 x1).
Definition term362 (x0 : nat -> real) (x1 : nat) := real_gt (x0 x1).
Definition term73 (x0 : nat) (x1 : nat -> real) (x2 : nat) (x3 : real) (x4 : real) := ((@IN nat x2 (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0)) = (Peano.le (Nat.add x2 (NUMERAL (BIT1 0))) x2)) -> ((Peano.le (Nat.add x2 (NUMERAL (BIT1 0))) x2) -> (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0) x1) = x3) -> ((~ (Peano.le (Nat.add x2 (NUMERAL (BIT1 0))) x2)) -> (real_add (x1 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0) x1)) = x4) -> (@COND real (@IN nat x2 (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0)) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0) x1) (real_add (x1 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0) x1))) = (@COND real (Peano.le (Nat.add x2 (NUMERAL (BIT1 0))) x2) x3 x4).
Definition term271 (x0 : int) := real_add (real_of_int x0) (real_of_num (NUMERAL 0)).
Definition term14 (x0 : nat) (x1 : nat) := (fun y0 : nat => forall y1 : nat, (@IN nat y1 (dotdot x0 y0)) = ((Peano.le x0 y1) /\ (Peano.le y1 y0))) x1.
Definition term26 (a0 : Type') (x0 : a0) (x1 : a0 -> real) := (fun y0 : a0 -> real => forall y1 : a0 -> Prop, (@FINITE a0 y1) -> (@sum a0 (@INSERT a0 x0 y1) y0) = (@COND real (@IN a0 x0 y1) (@sum a0 y1 y0) (real_add (y0 x0) (@sum a0 y1 y0)))) x1.
Definition term85 (x0 : nat) (x1 : nat) (x2 : nat -> real) := ((Peano.le x0 x1) -> ((@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = ((@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))) -> ((Peano.le x0 x1) -> (@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = ((Peano.le x0 x1) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term49 (x0 : nat) (x1 : nat -> Prop) (x2 : nat -> real) := (@FINITE nat x1) -> (@sum nat (@INSERT nat x0 x1) x2) = (@COND real (@IN nat x0 x1) (@sum nat x1 x2) (real_add (x2 x0) (@sum nat x1 x2))).
Definition term29 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : a0 -> real) := (@FINITE a0 x1) -> (@sum a0 (@INSERT a0 x0 x1) x2) = (@COND real (@IN a0 x0 x1) (@sum a0 x1 x2) (real_add (x2 x0) (@sum a0 x1 x2))).
Definition term367 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_gt (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) (real_of_num (NUMERAL 0)).
Definition term21 (x0 : nat) (x1 : nat) := (fun y0 : nat => @FINITE nat (dotdot x0 y0)) x1.
Definition term325 (x0 : int) (x1 : int) := real_ge (real_sub (real_of_int x0) (real_of_int x1)) (real_of_num (NUMERAL 0)).
Definition term222 := real_le (real_of_num (NUMERAL 0)).
Definition term110 (x0 : nat) (x1 : nat -> real) := ((Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) = False) -> (forall y0 : nat, (Peano.le x0 y0) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = True.
Definition term226 (x0 : int) (x1 : int) := real_of_int (int_add x0 x1).
Definition term401 (x0 : nat) (x1 : nat) := (x0 = (NUMERAL 0)) /\ (x1 = (NUMERAL 0)).
Definition term31 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : a0 -> real) := @COND real (@IN a0 x0 x1) (@sum a0 x1 x2) (real_add (x2 x0) (@sum a0 x1 x2)).
Definition term62 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2.
Definition term333 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term233 (x0 : int) := real_add (real_of_int x0).
Definition term184 (x0 : nat) := (fun y0 : nat => int_le (int_of_num (NUMERAL 0)) (int_of_num y0)) x0.
Definition term246 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := ~ (~ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x0)) /\ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x1)) /\ ((real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ ((real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))))))).
Definition term83 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @eq real (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term34 (x0 : Prop) (x1 : Prop) (x2 : Prop) (x3 : Prop) := (x0 = x2) -> (x2 -> x1 = x3) -> (x0 -> x1) = (x2 -> x3).
Definition term403 := and ((NUMERAL 0) = (NUMERAL 0)).
Definition term123 (x0 : nat) (x1 : nat -> real) := and ((~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ (forall y0 : nat, (Peano.le x0 y0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))).
Definition term84 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (Peano.le x0 x1) -> ((@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = ((@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term172 (x0 : nat) (x1 : nat) := ~ (Peano.le x0 x1).
Definition term295 (x0 : int) := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0).
Definition term218 (x0 : nat) := real_of_int (int_of_num x0).
Definition term344 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_mul (real_of_num (NUMERAL 0)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term43 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) (x4 : Prop) := ((Peano.le x0 x1) = x3) -> (x3 -> ((@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = x4) -> ((Peano.le x0 x1) -> (@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (x3 -> x4).
Definition term346 (x0 : nat -> real) (x1 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1)) (real_of_num (NUMERAL 0)).
Definition term61 (x0 : nat) (x1 : nat) := @IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1).
Definition term314 := real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term6 (x0 : nat) := forall y0 : nat, (Peano.le x0 y0) -> (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0)) = (dotdot x0 y0).
Definition term310 (x0 : nat) := real_add (real_neg (real_of_num x0)) (real_of_num x0).
Definition term266 := Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)).
Definition term353 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term227 (x0 : int) (x1 : int) := real_add (real_of_int x0) (real_of_int x1).
Definition term138 := fun y0 : nat -> real => forall y1 : nat, (~ (Peano.le (Nat.add y1 (NUMERAL (BIT1 0))) y1)) \/ (forall y2 : nat, (~ (Peano.le y1 y2)) \/ ((@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)))).
Definition term130 := fun y0 : nat -> real => forall y1 : nat, (~ (Peano.le (Nat.add y1 (NUMERAL (BIT1 0))) y1)) \/ (forall y2 : nat, (Peano.le y1 y2) -> (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0))).
Definition term297 := real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term332 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (real_gt (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) (real_of_num (NUMERAL 0))) \/ (real_gt (real_neg (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))) (real_of_num (NUMERAL 0))).
Definition term258 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0)).
Definition term239 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))).
Definition term402 := ((NUMERAL 0) = (NUMERAL 0)) /\ ((NUMERAL (BIT1 0)) = (NUMERAL 0)).
Definition term287 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term65 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) (x4 : real) := (fun y0 : real => forall y1 : real, ((@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) = x3) -> (x3 -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = y0) -> ((~ x3) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = y1) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real x3 y0 y1)) x4.
Definition term87 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (Peano.le x0 x1) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term302 := real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term81 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term80 (x0 : nat) (x1 : nat) (x2 : nat -> real) := ((~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term63 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) := (fun y0 : Prop => forall y1 : real, forall y2 : real, ((@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) = y0) -> (y0 -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = y1) -> ((~ y0) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = y2) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real y0 y1 y2)) x3.
Definition term383 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0))).
Definition term111 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @COND real True (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term27 (a0 : Type') (x0 : a0) (x1 : a0 -> real) := forall y0 : a0 -> Prop, (@FINITE a0 y0) -> (@sum a0 (@INSERT a0 x0 y0) x1) = (@COND real (@IN a0 x0 y0) (@sum a0 y0 x1) (real_add (x1 x0) (@sum a0 y0 x1))).
Definition term147 (x0 : nat) (x1 : nat -> real) := fun y0 : nat => (fun y1 : nat => (~ (Peano.le x0 y1)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1)))) y0.
Definition term179 (x0 : nat) (x1 : nat -> real) := forall y0 : nat, (~ (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0))) \/ ((~ (int_le (int_of_num x0) (int_of_num y0))) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))).
Definition term155 (x0 : nat) (x1 : nat -> real) := forall y0 : nat, (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ ((~ (Peano.le x0 y0)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))).
Definition term134 (x0 : nat) (x1 : nat -> real) := forall y0 : nat, (~ (Peano.le x0 y0)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))).
Definition term181 (x0 : nat -> real) := forall y0 : nat, forall y1 : nat, (~ (int_le (int_add (int_of_num y0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num y0))) \/ ((~ (int_le (int_of_num y0) (int_of_num y1))) \/ ((@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)))).
Definition term157 (x0 : nat -> real) := forall y0 : nat, forall y1 : nat, (~ (Peano.le (Nat.add y0 (NUMERAL (BIT1 0))) y0)) \/ ((~ (Peano.le y0 y1)) \/ ((@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)))).
Definition term95 (x0 : nat -> real) := forall y0 : nat, forall y1 : nat, (Peano.le y0 y1) -> (@COND real (Peano.le (Nat.add y0 (NUMERAL (BIT1 0))) y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0))) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)).
Definition term94 (x0 : nat -> real) := forall y0 : nat, forall y1 : nat, (Peano.le y0 y1) -> (@sum nat (dotdot y0 y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)).
Definition term13 (x0 : nat) := forall y0 : nat, forall y1 : nat, (@IN nat y1 (dotdot x0 y0)) = ((Peano.le x0 y1) /\ (Peano.le y1 y0)).
Definition term11 := forall y0 : nat, forall y1 : nat, (Peano.le y0 y1) -> (dotdot y0 y1) = (@INSERT nat y0 (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1)).
Definition term10 := forall y0 : nat, forall y1 : nat, (Peano.le y0 y1) -> (@INSERT nat y0 (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1)) = (dotdot y0 y1).
Definition term319 (x0 : int) := real_add (real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0))).
Definition term236 (x0 : int) := real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term387 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0)))).
Definition term284 (x0 : nat) (x1 : nat) := real_mul (real_neg (real_of_num x0)) (real_of_num x1).
Definition term170 (x0 : nat) := ~ (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0)).
Definition term102 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @COND real False (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term340 (x0 : nat -> real) (x1 : nat) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1).
Definition term203 (x0 : int) := ~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0).
Definition term349 (x0 : nat -> real) (x1 : nat) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1)).
Definition term68 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) (x4 : real) (x5 : real) := ((@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) = x3) -> (x3 -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = x4) -> ((~ x3) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = x5) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real x3 x4 x5).
Definition term357 := real_mul (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term356 := real_div (real_of_num (NUMERAL (BIT1 0))).
Definition term335 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term107 := forall y0 : nat, True.
Definition term288 := real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term48 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @sum nat (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) x2.
Definition term364 (x0 : nat -> real) (x1 : nat) := real_gt (x0 x1) (real_of_num (NUMERAL 0)).
Definition term101 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term263 := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term323 := real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term53 (x0 : nat) := Nat.add x0 (NUMERAL (BIT1 0)).
Definition term322 (x0 : int) := real_ge (real_sub (real_of_int x0) (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0))))).
Definition term28 (a0 : Type') (x0 : a0) (x1 : a0 -> real) (x2 : a0 -> Prop) := (fun y0 : a0 -> Prop => (@FINITE a0 y0) -> (@sum a0 (@INSERT a0 x0 y0) x1) = (@COND real (@IN a0 x0 y0) (@sum a0 y0 x1) (real_add (x1 x0) (@sum a0 y0 x1)))) x2.
Definition term330 (x0 : int) (x1 : int) := real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)).
Definition term370 (x0 : nat -> real) (x1 : nat) := or (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1)) (real_of_num (NUMERAL 0))).
Definition term397 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term225 (x0 : int) := int_add x0 (int_of_num (NUMERAL (BIT1 0))).
Definition term304 := S (Nat.add 0 0).
Definition term113 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @eq real (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term256 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term106 := fun y0 : nat => True.
Definition term15 (x0 : nat) (x1 : nat) := forall y0 : nat, (@IN nat y0 (dotdot x0 x1)) = ((Peano.le x0 y0) /\ (Peano.le y0 x1)).
Definition term331 (x0 : int) (x1 : int) := real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0)).
Definition term254 := real_neg (real_of_num (NUMERAL (BIT1 0))).
Definition term366 (x0 : nat -> real) (x1 : nat) := real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1)).
Definition term389 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := ((real_ge (real_of_int x0) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))))))) \/ ((real_ge (real_of_int x0) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0))))))).
Definition term385 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := ((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0)))))) \/ ((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0)))))).
Definition term281 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term365 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_gt (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term41 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) := forall y0 : Prop, ((Peano.le x0 x1) = x3) -> (x3 -> ((@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = y0) -> ((Peano.le x0 x1) -> (@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (x3 -> y0).
Definition term35 (x0 : Prop) (x1 : Prop) (x2 : Prop) := forall y0 : Prop, (x0 = x2) -> (x2 -> x1 = y0) -> (x0 -> x1) = (x2 -> y0).
Definition term114 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (Peano.le x0 x1) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term86 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (Peano.le x0 x1) -> (@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term165 (x0 : nat) := int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0))).
Definition term373 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ ((real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))) \/ (real_gt (x2 x3) (real_of_num (NUMERAL 0)))).
Definition term240 (x0 : int) := and (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)).
Definition term312 := real_mul (real_of_num (NUMERAL 0)).
Definition term198 (x0 : int) := and (~ (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0))).
Definition term60 (x0 : nat) (x1 : nat) (x2 : nat -> real) := forall y0 : Prop, forall y1 : real, forall y2 : real, ((@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) = y0) -> (y0 -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = y1) -> ((~ y0) -> (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)) = y2) -> (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (@COND real y0 y1 y2).
Definition term59 (x0 : Prop) (x1 : real) (x2 : real) := forall y0 : Prop, forall y1 : real, forall y2 : real, (x0 = y0) -> (y0 -> x1 = y1) -> ((~ y0) -> x2 = y2) -> (@COND real x0 x1 x2) = (@COND real y0 y1 y2).
Definition term58 (a0 : Type') (x0 : Prop) (x1 : a0) (x2 : a0) := forall y0 : Prop, forall y1 : a0, forall y2 : a0, (x0 = y0) -> (y0 -> x1 = y1) -> ((~ y0) -> x2 = y2) -> (@COND a0 x0 x1 x2) = (@COND a0 y0 y1 y2).
Definition term37 (x0 : nat) (x1 : nat) (x2 : nat -> real) := forall y0 : Prop, forall y1 : Prop, ((Peano.le x0 x1) = y0) -> (y0 -> ((@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = y1) -> ((Peano.le x0 x1) -> (@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (y0 -> y1).
Definition term36 (x0 : Prop) (x1 : Prop) := forall y0 : Prop, forall y1 : Prop, (x0 = y0) -> (y0 -> x1 = y1) -> (x0 -> x1) = (y0 -> y1).
Definition term105 (x0 : nat) (x1 : nat) := (Peano.le x0 x1) -> True.
Definition term45 (x0 : nat -> real) (x1 : nat) (x2 : nat) (x3 : Prop) := ((Peano.le x1 x2) -> ((@sum nat (dotdot x1 x2) x0) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) x2) x0))) = x3) -> ((Peano.le x1 x2) -> (@sum nat (dotdot x1 x2) x0) = (real_add (x0 x1) (@sum nat (dotdot (Nat.add x1 (NUMERAL (BIT1 0))) x2) x0))) = ((Peano.le x1 x2) -> x3).
Definition term192 (x0 : int) (x1 : int) := and (~ (~ (int_le x0 x1))).
Definition term174 (x0 : nat) (x1 : nat) := or (~ (Peano.le x0 x1)).
Definition term118 (x0 : nat) (x1 : nat -> real) := (((Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) = False) -> (forall y0 : nat, (Peano.le x0 y0) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = True) /\ (((Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) = True) -> (forall y0 : nat, (Peano.le x0 y0) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (forall y0 : nat, (Peano.le x0 y0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))).
Definition term374 := and (real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))).
Definition term235 (x0 : int) := real_le (real_of_int (int_add x0 (int_of_num (NUMERAL (BIT1 0))))).
Definition term352 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term50 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (@FINITE nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) -> (@sum nat (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) x2) = (@COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term25 (a0 : Type') (x0 : a0) := forall y0 : a0 -> real, forall y1 : a0 -> Prop, (@FINITE a0 y1) -> (@sum a0 (@INSERT a0 x0 y1) y0) = (@COND real (@IN a0 x0 y1) (@sum a0 y1 y0) (real_add (y0 x0) (@sum a0 y1 y0))).
Definition term117 (x0 : nat) (x1 : nat -> real) := ((Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) = True) -> (forall y0 : nat, (Peano.le x0 y0) -> (@COND real (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))) = (forall y0 : nat, (Peano.le x0 y0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))).
Definition term47 (x0 : nat) (x1 : nat) := @sum nat (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)).
Definition term74 (x0 : nat) (x1 : nat -> real) (x2 : nat) (x3 : real) (x4 : real) := ((Peano.le (Nat.add x2 (NUMERAL (BIT1 0))) x2) -> (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0) x1) = x3) -> ((~ (Peano.le (Nat.add x2 (NUMERAL (BIT1 0))) x2)) -> (real_add (x1 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0) x1)) = x4) -> (@COND real (@IN nat x2 (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0)) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0) x1) (real_add (x1 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x0) x1))) = (@COND real (Peano.le (Nat.add x2 (NUMERAL (BIT1 0))) x2) x3 x4).
Definition term355 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term185 (x0 : nat) := int_le (int_of_num (NUMERAL 0)) (int_of_num x0).
Definition term261 (x0 : nat) (x1 : nat) := real_mul (real_of_num x0) (real_of_num x1).
Definition term146 (x0 : nat) (x1 : nat -> real) (x2 : nat) := (fun y0 : nat => (~ (Peano.le x0 y0)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))) x2.
Definition term358 := real_mul (real_of_num (NUMERAL (BIT1 0))).
Definition term316 := real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term42 (x0 : nat) (x1 : nat) (x2 : nat -> real) (x3 : Prop) (x4 : Prop) := (fun y0 : Prop => ((Peano.le x0 x1) = x3) -> (x3 -> ((@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = y0) -> ((Peano.le x0 x1) -> (@sum nat (dotdot x0 x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))) = (x3 -> y0)) x4.
Definition term22 (x0 : nat) (x1 : nat) := @FINITE nat (dotdot x0 x1).
Definition term280 := real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term126 (x0 : nat) := or (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)).
Definition term205 (x0 : int) := and (int_le (int_of_num (NUMERAL 0)) x0).
Definition term38 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @sum nat (dotdot x0 x1) x2.
Definition term139 := forall y0 : nat -> real, forall y1 : nat, (~ (Peano.le (Nat.add y1 (NUMERAL (BIT1 0))) y1)) \/ (forall y2 : nat, (~ (Peano.le y1 y2)) \/ ((@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0)))).
Definition term131 := forall y0 : nat -> real, forall y1 : nat, (~ (Peano.le (Nat.add y1 (NUMERAL (BIT1 0))) y1)) \/ (forall y2 : nat, (Peano.le y1 y2) -> (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0) = (real_add (y0 y1) (@sum nat (dotdot (Nat.add y1 (NUMERAL (BIT1 0))) y2) y0))).
Definition term119 (x0 : Prop) (x1 : Prop) (x2 : Prop) (x3 : Prop) := (((x2 = False) -> x0 = x3) /\ ((x2 = True) -> x0 = x1)) -> x0 = (((~ x2) \/ x1) /\ (x2 \/ x3)).
Definition term51 (x0 : nat) (x1 : nat) := dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1.
Definition term285 (x0 : nat) (x1 : nat) := real_neg (real_of_num (Nat.mul x0 x1)).
Definition term347 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_neg (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term3 (x0 : nat) (x1 : nat) := (Peano.le x0 x1) -> (dotdot x0 x1) = (@INSERT nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)).
Definition term248 (x0 : int) := real_sub (real_of_int x0) (real_of_num (NUMERAL 0)).
Definition term215 (x0 : int) (x1 : int) := real_le (real_of_int x0) (real_of_int x1).
Definition term32 (x0 : nat) := (fun y0 : nat => forall y1 : nat, (Peano.le y0 y1) -> (dotdot y0 y1) = (@INSERT nat y0 (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1))) x0.
Definition term193 (x0 : int) (x1 : int) := and (int_le x0 x1).
Definition term354 (x0 : nat) (x1 : nat) := real_mul (real_neg (real_of_num x0)) (real_neg (real_of_num x1)).
Definition term211 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (int_le (int_of_num (NUMERAL 0)) x0) /\ (~ ((int_le (int_of_num (NUMERAL 0)) x1) -> (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))).
Definition term18 (x0 : nat) (x1 : nat) (x2 : nat) := (Peano.le x0 x1) /\ (Peano.le x1 x2).
Definition term171 (x0 : nat) := or (~ (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0))).
Definition term343 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term348 (x0 : nat -> real) (x1 : nat) := real_neg (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x0 x1)).
Definition term16 (x0 : nat) (x1 : nat) (x2 : nat) := (fun y0 : nat => (@IN nat y0 (dotdot x0 x1)) = ((Peano.le x0 y0) /\ (Peano.le y0 x1))) x2.
Definition term268 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))).
Definition term244 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (real_le (real_of_num (NUMERAL 0)) (real_of_int x0)) /\ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x1)) /\ ((real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ ((real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))))).
Definition term249 (x0 : int) := real_add (real_of_int x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))).
Definition term57 (a0 : Type') (x0 : Prop) (x1 : a0) (x2 : a0) (x3 : Prop) := forall y0 : a0, forall y1 : a0, (x0 = x3) -> (x3 -> x1 = y0) -> ((~ x3) -> x2 = y1) -> (@COND a0 x0 x1 x2) = (@COND a0 x3 y0 y1).
Definition term151 (x0 : nat) (x1 : nat -> real) (x2 : nat) := (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ ((fun y0 : nat => (~ (Peano.le x0 y0)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))) x2).
Definition term264 := real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0))).
Definition term380 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ (((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0))))).
Definition term52 (x0 : nat) (x1 : nat) := @FINITE nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1).
Definition term270 (x0 : real) := real_div x0 (real_of_num (NUMERAL (BIT1 0))).
Definition term69 (x0 : nat) (x1 : nat) := (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) /\ (Peano.le x0 x1).
Definition term315 (x0 : nat) := real_mul (real_of_num (NUMERAL 0)) (real_of_num x0).
Definition term232 := real_of_num (NUMERAL (BIT1 0)).
Definition term72 (x0 : nat) := Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0.
Definition term407 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := ~ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x0)) /\ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x1)) /\ ((real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ ((real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))))).
Definition term202 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := ~ ((~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))).
Definition term216 (x0 : int) := real_le (real_of_int (int_of_num (NUMERAL 0))) (real_of_int x0).
Definition term408 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (int_le (int_of_num (NUMERAL 0)) (int_of_num x0)) -> (int_le (int_of_num (NUMERAL 0)) (int_of_num x1)) -> (~ (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0))) \/ ((~ (int_le (int_of_num x0) (int_of_num x1))) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))).
Definition term321 := real_add (real_of_num (NUMERAL 0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term143 (x0 : Prop) (x1 : nat -> Prop) := forall y0 : nat, x0 \/ (x1 y0).
Definition term71 (x0 : nat) := (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) /\ True.
Definition term242 (x0 : int) := and (real_le (real_of_num (NUMERAL 0)) (real_of_int x0)).
Definition term360 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @eq real (real_neg (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))).
Definition term187 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (int_le (int_of_num (NUMERAL 0)) x0) -> (int_le (int_of_num (NUMERAL 0)) x1) -> (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))).
Definition term363 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_gt (real_neg (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))) (real_of_num (NUMERAL 0)).
Definition term208 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := ~ ((int_le (int_of_num (NUMERAL 0)) x1) -> (~ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0)) \/ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))).
Definition term290 (x0 : int) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term19 (x0 : nat) := (fun y0 : nat => forall y1 : nat, @FINITE nat (dotdot y0 y1)) x0.
Definition term396 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term109 (x0 : Prop) := forall y0 : nat, x0.
Definition term361 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_gt (real_neg (real_sub (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)))).
Definition term82 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @eq real (@sum nat (dotdot x0 x1) x2).
Definition term388 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_of_int x0) (real_of_num (NUMERAL 0))) /\ (((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0)))))) \/ ((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0))))))).
Definition term384 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ (((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))))) \/ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0)))))).
Definition term191 (x0 : nat) (x1 : nat) (x2 : nat -> real) := ~ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term160 (x0 : nat) (x1 : nat) := int_le (int_of_num x0) (int_of_num x1).
Definition term231 := real_of_int (int_of_num (NUMERAL (BIT1 0))).
Definition term54 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @COND real (@IN nat x0 (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1)) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term124 (x0 : nat) (x1 : nat -> real) := ((~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ (forall y0 : nat, (Peano.le x0 y0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))) /\ True.
Definition term262 (x0 : nat) (x1 : nat) := real_of_num (Nat.mul x0 x1).
Definition term207 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (int_le (int_of_num (NUMERAL 0)) x1) /\ ((int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x0) /\ ((int_le x0 x1) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))).
Definition term334 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_add (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term75 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) -> (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term196 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := ~ ((~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))).
Definition term164 (x0 : nat) := int_of_num (Nat.add x0 (NUMERAL (BIT1 0))).
Definition term386 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0)))).
Definition term209 (x0 : int) := int_le (int_of_num (NUMERAL 0)) x0.
Definition term112 (x0 : nat) (x1 : nat) (x2 : nat -> real) := @COND real True (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term234 (x0 : int) := real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0))).
Definition term162 (x0 : nat) (x1 : nat) := int_of_num (Nat.add x0 x1).
Definition term204 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (~ (int_le x0 x1)) \/ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))).
Definition term154 (x0 : nat) (x1 : nat -> real) := fun y0 : nat => (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ ((~ (Peano.le x0 y0)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))).
Definition term318 (x0 : int) := real_mul (real_of_num (NUMERAL 0)) (real_of_int x0).
Definition term404 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_of_int x0) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (x2 x3) (real_of_num (NUMERAL 0)))))).
Definition term392 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_of_int x0) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ (real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0)))))).
Definition term378 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_of_int x0) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ ((real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))) \/ (real_gt (x2 x3) (real_of_num (NUMERAL 0))))))).
Definition term377 (x0 : int) (x1 : int) (x2 : nat -> real) (x3 : nat) := (real_ge (real_of_int x1) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) (real_of_int x1)) (real_of_num (NUMERAL 0))) /\ ((real_gt (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (x2 x3)) (real_of_num (NUMERAL 0))) \/ (real_gt (x2 x3) (real_of_num (NUMERAL 0)))))).
Definition term278 (x0 : int) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term241 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ ((real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4))))).
Definition term133 (x0 : nat) (x1 : nat -> real) := fun y0 : nat => (~ (Peano.le x0 y0)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1))).
Definition term342 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_add (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2)).
Definition term298 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term250 (x0 : nat) := real_div (real_of_num x0) (real_of_num (NUMERAL (BIT1 0))).
Definition term221 := real_le (real_of_int (int_of_num (NUMERAL 0))).
Definition term324 := real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0)).
Definition term257 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term269 := real_div (real_of_num (NUMERAL 0)).
Definition term178 (x0 : nat) (x1 : nat -> real) := fun y0 : nat => (~ (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0))) \/ ((~ (int_le (int_of_num x0) (int_of_num y0))) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y0) x1)))).
Definition term320 := real_add (real_of_num (NUMERAL 0)).
Definition term405 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (~ (~ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x0)) /\ ((real_le (real_of_num (NUMERAL 0)) (real_of_int x1)) /\ ((real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ ((real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))))))) -> False.
Definition term122 (x0 : nat) := (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0) \/ True.
Definition term176 (x0 : nat) (x1 : nat) (x2 : nat -> real) := (~ (int_le (int_of_num x0) (int_of_num x1))) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2) = (real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2))).
Definition term55 (a0 : Type') (x0 : Prop) (x1 : a0) (x2 : a0) (x3 : Prop) (x4 : a0) (x5 : a0) := (x0 = x3) -> (x3 -> x1 = x4) -> ((~ x3) -> x2 = x5) -> (@COND a0 x0 x1 x2) = (@COND a0 x3 x4 x5).
Definition term24 (a0 : Type') (x0 : a0) := (fun y0 : a0 => forall y1 : a0 -> real, forall y2 : a0 -> Prop, (@FINITE a0 y2) -> (@sum a0 (@INSERT a0 y0 y2) y1) = (@COND real (@IN a0 y0 y2) (@sum a0 y2 y1) (real_add (y1 y0) (@sum a0 y2 y1)))) x0.
Definition term313 := real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0))).
Definition term230 := int_of_num (NUMERAL (BIT1 0)).
Definition term39 (x0 : nat) (x1 : nat) (x2 : nat -> real) := real_add (x2 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) x1) x2).
Definition term30 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : a0 -> real) := @sum a0 (@INSERT a0 x0 x1) x2.
Definition term224 (x0 : int) := real_le (real_of_int (int_add x0 (int_of_num (NUMERAL (BIT1 0))))) (real_of_int x0).
Definition term167 (x0 : nat) := int_le (int_of_num (Nat.add x0 (NUMERAL (BIT1 0)))).
Definition term163 (x0 : nat) (x1 : nat) := int_add (int_of_num x0) (int_of_num x1).
Definition term190 (x0 : int) (x1 : int) := ~ (~ (int_le x0 x1)).
Definition term180 (x0 : nat -> real) := fun y0 : nat => forall y1 : nat, (~ (int_le (int_add (int_of_num y0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num y0))) \/ ((~ (int_le (int_of_num y0) (int_of_num y1))) \/ ((@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)))).
Definition term156 (x0 : nat -> real) := fun y0 : nat => forall y1 : nat, (~ (Peano.le (Nat.add y0 (NUMERAL (BIT1 0))) y0)) \/ ((~ (Peano.le y0 y1)) \/ ((@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)))).
Definition term93 (x0 : nat -> real) := fun y0 : nat => forall y1 : nat, (Peano.le y0 y1) -> (@COND real (Peano.le (Nat.add y0 (NUMERAL (BIT1 0))) y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0))) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)).
Definition term92 (x0 : nat -> real) := fun y0 : nat => forall y1 : nat, (Peano.le y0 y1) -> (@sum nat (dotdot y0 y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)).
Definition term9 := fun y0 : nat => forall y1 : nat, (Peano.le y0 y1) -> (dotdot y0 y1) = (@INSERT nat y0 (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1)).
Definition term8 := fun y0 : nat => forall y1 : nat, (Peano.le y0 y1) -> (@INSERT nat y0 (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1)) = (dotdot y0 y1).
Definition term166 := NUMERAL (BIT1 0).
Definition term145 (x0 : nat) (x1 : nat -> real) := forall y0 : nat, (~ (Peano.le (Nat.add x0 (NUMERAL (BIT1 0))) x0)) \/ ((fun y1 : nat => (~ (Peano.le x0 y1)) \/ ((@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1) = (real_add (x1 x0) (@sum nat (dotdot (Nat.add x0 (NUMERAL (BIT1 0))) y1) x1)))) y0).
Definition term283 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term350 (x0 : nat -> real) (x1 : nat) := real_mul (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))) (x0 x1).
Definition term137 (x0 : nat -> real) := forall y0 : nat, (~ (Peano.le (Nat.add y0 (NUMERAL (BIT1 0))) y0)) \/ (forall y1 : nat, (~ (Peano.le y0 y1)) \/ ((@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0)))).
Definition term129 (x0 : nat -> real) := forall y0 : nat, (~ (Peano.le (Nat.add y0 (NUMERAL (BIT1 0))) y0)) \/ (forall y1 : nat, (Peano.le y0 y1) -> (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0) = (real_add (x0 y0) (@sum nat (dotdot (Nat.add y0 (NUMERAL (BIT1 0))) y1) x0))).
Definition term161 (x0 : nat) := int_le (int_of_num (Nat.add x0 (NUMERAL (BIT1 0)))) (int_of_num x0).
Definition term243 (x0 : int) (x1 : int) (x2 : nat) (x3 : nat) (x4 : nat -> real) := (real_le (real_of_num (NUMERAL 0)) (real_of_int x1)) /\ ((real_le (real_add (real_of_int x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_int x0)) /\ ((real_le (real_of_int x0) (real_of_int x1)) /\ (~ ((@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4) = (real_add (x4 x2) (@sum nat (dotdot (Nat.add x2 (NUMERAL (BIT1 0))) x3) x4)))))).
Definition term247 (x0 : int) := real_ge (real_sub (real_of_int x0) (real_of_num (NUMERAL 0))) (real_of_num (NUMERAL 0)).
