Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term236 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1).
Definition term136 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : Prop) (x3 : nat) (x4 : nat) := (fun y0 : nat => ((@IN a0 x0 x1) = x2) -> (x2 -> (@CARD a0 x1) = x3) -> ((~ x2) -> (S (@CARD a0 x1)) = y0) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat x2 x3 y0)) x4.
Definition term14 (a0 : Type') := forall y0 : a0, forall y1 : a0 -> real, forall y2 : a0 -> Prop, (@FINITE a0 y2) -> (@sum a0 (@INSERT a0 y0 y2) y1) = (@COND real (@IN a0 y0 y2) (@sum a0 y2 y1) (real_add (y1 y0) (@sum a0 y2 y1))).
Definition term126 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := @COND real False (real_mul (real_of_num (@CARD a0 x0)) x1) (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)).
Definition term264 := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term71 (a0 : Type') (x0 : real) := fun y0 : a0 -> Prop => (@FINITE a0 y0) -> (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0).
Definition term275 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := or (real_gt (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))).
Definition term200 (x0 : real) := or (real_gt (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0)) (real_of_num (NUMERAL 0))).
Definition term169 (x0 : nat) := real_div (real_neg (real_of_num x0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term183 := Nat.pow (BIT1 0) (NUMERAL (BIT0 (BIT1 0))).
Definition term151 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1.
Definition term208 (x0 : nat) (x1 : nat) := real_lt (real_of_num x0) (real_of_num x1).
Definition term258 := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term157 (a0 : Type') (x0 : real) := fun y0 : a0 => forall y1 : a0 -> Prop, (((@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (real_add x0 (real_mul (real_of_num (@CARD a0 y1)) x0)) = (real_mul (real_add (real_of_num (@CARD a0 y1)) (real_of_num (NUMERAL (BIT1 0)))) x0).
Definition term60 (a0 : Type') (x0 : real) := fun y0 : a0 => forall y1 : a0 -> Prop, (((@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (@sum a0 (@INSERT a0 y0 y1) (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 y0 y1))) x0).
Definition term227 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_add (real_mul x0 (real_of_num (@CARD a0 x1))).
Definition term259 := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term67 (a0 : Type') (x0 : a0 -> Prop) := imp (@FINITE a0 x0).
Definition term232 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_sub (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1).
Definition term168 (x0 : nat) := real_neg (real_of_num x0).
Definition term108 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) (x4 : real) (x5 : real) := (fun y0 : real => ((@IN a0 x0 x1) = x3) -> (x3 -> (@sum a0 x1 (fun y1 : a0 => x2)) = x4) -> ((~ x3) -> (real_add ((fun y1 : a0 => x2) x0) (@sum a0 x1 (fun y1 : a0 => x2))) = y0) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y1 : a0 => x2)) (real_add ((fun y1 : a0 => x2) x0) (@sum a0 x1 (fun y1 : a0 => x2)))) = (@COND real x3 x4 y0)) x5.
Definition term135 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : Prop) (x3 : nat) := forall y0 : nat, ((@IN a0 x0 x1) = x2) -> (x2 -> (@CARD a0 x1) = x3) -> ((~ x2) -> (S (@CARD a0 x1)) = y0) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat x2 x3 y0).
Definition term243 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_add (real_mul x0 (real_of_num (@CARD a0 x1))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul x0 (real_of_num (@CARD a0 x1)))).
Definition term25 := real_of_num (NUMERAL 0).
Definition term139 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : nat) (x3 : nat) := (False -> (@CARD a0 x1) = x2) -> ((~ False) -> (S (@CARD a0 x1)) = x3) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat False x2 x3).
Definition term230 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_add x0 (real_mul x0 (real_of_num (@CARD a0 x1))).
Definition term42 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_mul (real_of_num (@CARD a0 x0)) x1.
Definition term107 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) (x4 : real) := forall y0 : real, ((@IN a0 x0 x1) = x3) -> (x3 -> (@sum a0 x1 (fun y1 : a0 => x2)) = x4) -> ((~ x3) -> (real_add ((fun y1 : a0 => x2) x0) (@sum a0 x1 (fun y1 : a0 => x2))) = y0) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y1 : a0 => x2)) (real_add ((fun y1 : a0 => x2) x0) (@sum a0 x1 (fun y1 : a0 => x2)))) = (@COND real x3 x4 y0).
Definition term142 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : nat) := ((~ False) -> (S (@CARD a0 x1)) = x2) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat False (@CARD a0 x1) x2).
Definition term132 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : Prop) := (fun y0 : Prop => forall y1 : nat, forall y2 : nat, ((@IN a0 x0 x1) = y0) -> (y0 -> (@CARD a0 x1) = y1) -> ((~ y0) -> (S (@CARD a0 x1)) = y2) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat y0 y1 y2)) x2.
Definition term6 (x0 : nat) := (fun y0 : nat => (real_of_num (S y0)) = (real_add (real_of_num y0) (real_of_num (NUMERAL (BIT1 0))))) x0.
Definition term79 (a0 : Type') := real_mul (real_of_num (@CARD a0 (@EMPTY a0))).
Definition term253 := ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term261 := real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term213 := real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term56 (a0 : Type') (x0 : a0) (x1 : real) := fun y0 : a0 -> Prop => (((@sum a0 y0 (fun y1 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 y0)) x1)) /\ ((~ (@IN a0 x0 y0)) /\ (@FINITE a0 y0))) -> (@sum a0 (@INSERT a0 x0 y0) (fun y1 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 y0))) x1).
Definition term34 (a0 : Type') (x0 : real) := fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0).
Definition term12 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := @CARD a0 (@INSERT a0 x0 x1).
Definition term177 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term235 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_add (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1)).
Definition term96 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := @COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y0 : a0 => x2)) (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2))).
Definition term246 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term53 (a0 : Type') (x0 : real) (x1 : a0) (x2 : a0 -> Prop) := (((fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) x2) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))) -> (fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) (@INSERT a0 x1 x2).
Definition term1 (x0 : nat) := real_of_num (S x0).
Definition term91 (a0 : Type') (x0 : real) (x1 : a0) (x2 : a0 -> Prop) (x3 : Prop) := ((((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))) = (((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2)))) -> ((((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))) -> ((@sum a0 (@INSERT a0 x1 x2) (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x1 x2))) x0)) = x3) -> ((((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))) -> (@sum a0 (@INSERT a0 x1 x2) (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x1 x2))) x0)) = ((((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))) -> x3).
Definition term229 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_mul x0 (real_of_num (@CARD a0 x1)).
Definition term120 (a0 : Type') (x0 : real) (x1 : a0) := @eq real ((fun y0 : a0 => (fun y1 : a0 => x0) y0) x1).
Definition term10 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := (fun y0 : a0 -> Prop => (@FINITE a0 y0) -> (@CARD a0 (@INSERT a0 x0 y0)) = (@COND nat (@IN a0 x0 y0) (@CARD a0 y0) (S (@CARD a0 y0)))) x1.
Definition term123 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1).
Definition term192 := real_neg (real_of_num (NUMERAL 0)).
Definition term98 (a0 : Type') (x0 : Prop) (x1 : a0) (x2 : a0) (x3 : Prop) (x4 : a0) := forall y0 : a0, (x0 = x3) -> (x3 -> x1 = x4) -> ((~ x3) -> x2 = y0) -> (@COND a0 x0 x1 x2) = (@COND a0 x3 x4 y0).
Definition term251 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term250 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term273 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_gt (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term167 := real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term11 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := (@FINITE a0 x1) -> (@CARD a0 (@INSERT a0 x0 x1)) = (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))).
Definition term5 := forall y0 : nat, (real_of_num (S y0)) = (real_add (real_of_num y0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term92 (a0 : Type') (x0 : real) (x1 : a0) (x2 : a0 -> Prop) (x3 : Prop) := ((((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))) -> ((@sum a0 (@INSERT a0 x1 x2) (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x1 x2))) x0)) = x3) -> ((((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))) -> (@sum a0 (@INSERT a0 x1 x2) (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x1 x2))) x0)) = ((((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))) -> x3).
Definition term52 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2.
Definition term59 (a0 : Type') (x0 : real) := fun y0 : a0 => forall y1 : a0 -> Prop, (((fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) y1) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) (@INSERT a0 y0 y1).
Definition term93 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := ~ (@IN a0 x0 x1).
Definition term239 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_add (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul x1 (real_of_num (@CARD a0 x0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term219 (x0 : real) := ((~ ((real_of_num (NUMERAL 0)) = (real_mul (real_of_num (NUMERAL 0)) x0))) -> False) -> (real_of_num (NUMERAL 0)) = (real_mul (real_of_num (NUMERAL 0)) x0).
Definition term165 := real_add (real_of_num (NUMERAL 0)) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))).
Definition term257 := real_neg (real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)))).
Definition term39 (a0 : Type') (x0 : real) := and ((@sum a0 (@EMPTY a0) (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@EMPTY a0))) x0)).
Definition term36 (a0 : Type') (x0 : real) := @sum a0 (@EMPTY a0) (fun y0 : a0 => x0).
Definition term171 := real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term144 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := ((~ False) -> (S (@CARD a0 x1)) = (S (@CARD a0 x1))) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat False (@CARD a0 x1) (S (@CARD a0 x1))).
Definition term113 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : real) := (False -> (@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) -> ((~ False) -> (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2))) = x3) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y0 : a0 => x2)) (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2)))) = (@COND real False (real_mul (real_of_num (@CARD a0 x1)) x2) x3).
Definition term118 (a0 : Type') (x0 : real) (x1 : a0) := (fun y0 : a0 => x0) x1.
Definition term8 (a0 : Type') (x0 : a0) := (fun y0 : a0 => forall y1 : a0 -> Prop, (@FINITE a0 y1) -> (@CARD a0 (@INSERT a0 y0 y1)) = (@COND nat (@IN a0 y0 y1) (@CARD a0 y1) (S (@CARD a0 y1)))) x0.
Definition term210 := Peano.lt (NUMERAL 0) (NUMERAL (BIT1 0)).
Definition term119 (a0 : Type') (x0 : real) := fun y0 : a0 => (fun y1 : a0 => x0) y0.
Definition term185 (x0 : nat) := real_mul (real_neg (real_of_num x0)) (real_of_num (NUMERAL 0)).
Definition term278 (a0 : Type') := forall y0 : real, forall y1 : a0 -> Prop, (@FINITE a0 y1) -> (@sum a0 y1 (fun y2 : a0 => y0)) = (real_mul (real_of_num (@CARD a0 y1)) y0).
Definition term105 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) := forall y0 : real, forall y1 : real, ((@IN a0 x0 x1) = x3) -> (x3 -> (@sum a0 x1 (fun y2 : a0 => x2)) = y0) -> ((~ x3) -> (real_add ((fun y2 : a0 => x2) x0) (@sum a0 x1 (fun y2 : a0 => x2))) = y1) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y2 : a0 => x2)) (real_add ((fun y2 : a0 => x2) x0) (@sum a0 x1 (fun y2 : a0 => x2)))) = (@COND real x3 y0 y1).
Definition term87 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) := (fun y0 : Prop => forall y1 : Prop, ((((@sum a0 x1 (fun y2 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) = y0) -> (y0 -> ((@sum a0 (@INSERT a0 x0 x1) (fun y2 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = y1) -> ((((@sum a0 x1 (fun y2 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (@sum a0 (@INSERT a0 x0 x1) (fun y2 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = (y0 -> y1)) x3.
Definition term176 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term46 (a0 : Type') (x0 : real) (x1 : a0) (x2 : a0 -> Prop) := ((fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) x2) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2)).
Definition term252 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term249 := real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term270 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := @eq real (real_neg (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1))).
Definition term73 (a0 : Type') (x0 : real) := forall y0 : a0 -> Prop, (@FINITE a0 y0) -> (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0).
Definition term17 (a0 : Type') (x0 : a0) (x1 : a0 -> real) := (fun y0 : a0 -> real => forall y1 : a0 -> Prop, (@FINITE a0 y1) -> (@sum a0 (@INSERT a0 x0 y1) y0) = (@COND real (@IN a0 x0 y1) (@sum a0 y1 y0) (real_add (y0 x0) (@sum a0 y1 y0)))) x1.
Definition term223 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_add (real_mul x1 (real_of_num (@CARD a0 x0))) (real_mul x1 (real_of_num (NUMERAL (BIT1 0)))).
Definition term20 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : a0 -> real) := (@FINITE a0 x1) -> (@sum a0 (@INSERT a0 x0 x1) x2) = (@COND real (@IN a0 x0 x1) (@sum a0 x1 x2) (real_add (x2 x0) (@sum a0 x1 x2))).
Definition term160 (x0 : real) := ~ ((real_of_num (NUMERAL 0)) = (real_mul (real_of_num (NUMERAL 0)) x0)).
Definition term22 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : a0 -> real) := @COND real (@IN a0 x0 x1) (@sum a0 x1 x2) (real_add (x2 x0) (@sum a0 x1 x2)).
Definition term153 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := ((((@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> ((@sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = ((real_add x2 (real_mul (real_of_num (@CARD a0 x1)) x2)) = (real_mul (real_add (real_of_num (@CARD a0 x1)) (real_of_num (NUMERAL (BIT1 0)))) x2))) -> ((((@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (@sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = ((((@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (real_add x2 (real_mul (real_of_num (@CARD a0 x1)) x2)) = (real_mul (real_add (real_of_num (@CARD a0 x1)) (real_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term0 (x0 : nat) := real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0))).
Definition term204 := real_lt (real_of_num (NUMERAL 0)).
Definition term199 (x0 : real) := real_gt (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0)) (real_of_num (NUMERAL 0)).
Definition term83 (x0 : Prop) (x1 : Prop) (x2 : Prop) (x3 : Prop) := (x0 = x2) -> (x2 -> x1 = x3) -> (x0 -> x1) = (x2 -> x3).
Definition term131 (a0 : Type') (x0 : a0 -> Prop) := S (@CARD a0 x0).
Definition term33 (a0 : Type') (x0 : real) := (((fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) (@EMPTY a0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, (((fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) y1) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) (@INSERT a0 y0 y1))) -> forall y0 : a0 -> Prop, (@FINITE a0 y0) -> (fun y1 : a0 -> Prop => (@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) y0.
Definition term51 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := @sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2).
Definition term35 (a0 : Type') (x0 : real) := (fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) (@EMPTY a0).
Definition term215 := real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term193 (x0 : real) := @eq real (real_neg (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0))).
Definition term260 (x0 : nat) := real_add (real_neg (real_of_num x0)) (real_of_num x0).
Definition term269 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_neg (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term184 := Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)).
Definition term274 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_gt (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0)).
Definition term202 := (real_gt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0))).
Definition term247 := real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term221 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := (real_gt (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_neg (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0))).
Definition term161 (x0 : real) := (real_gt (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0)) (real_of_num (NUMERAL 0))) \/ (real_gt (real_neg (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0))) (real_of_num (NUMERAL 0))).
Definition term138 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : nat) (x3 : nat) := ((@IN a0 x0 x1) = False) -> (False -> (@CARD a0 x1) = x2) -> ((~ False) -> (S (@CARD a0 x1)) = x3) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat False x2 x3).
Definition term110 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : real) (x4 : real) := ((@IN a0 x0 x1) = False) -> (False -> (@sum a0 x1 (fun y0 : a0 => x2)) = x3) -> ((~ False) -> (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2))) = x4) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y0 : a0 => x2)) (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2)))) = (@COND real False x3 x4).
Definition term217 := Peano.lt (NUMERAL 0) (NUMERAL 0).
Definition term175 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0)).
Definition term106 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) (x4 : real) := (fun y0 : real => forall y1 : real, ((@IN a0 x0 x1) = x3) -> (x3 -> (@sum a0 x1 (fun y2 : a0 => x2)) = y0) -> ((~ x3) -> (real_add ((fun y2 : a0 => x2) x0) (@sum a0 x1 (fun y2 : a0 => x2))) = y1) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y2 : a0 => x2)) (real_add ((fun y2 : a0 => x2) x0) (@sum a0 x1 (fun y2 : a0 => x2)))) = (@COND real x3 y0 y1)) x4.
Definition term162 := real_sub (real_of_num (NUMERAL 0)).
Definition term77 := @eq real (real_of_num (NUMERAL 0)).
Definition term209 := real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term121 (a0 : Type') (x0 : real) (x1 : a0) := @eq real ((fun y0 : a0 => x0) x1).
Definition term104 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) := (fun y0 : Prop => forall y1 : real, forall y2 : real, ((@IN a0 x0 x1) = y0) -> (y0 -> (@sum a0 x1 (fun y3 : a0 => x2)) = y1) -> ((~ y0) -> (real_add ((fun y3 : a0 => x2) x0) (@sum a0 x1 (fun y3 : a0 => x2))) = y2) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y3 : a0 => x2)) (real_add ((fun y3 : a0 => x2) x0) (@sum a0 x1 (fun y3 : a0 => x2)))) = (@COND real y0 y1 y2)) x3.
Definition term115 (a0 : Type') (a1 : Type') (x0 : a0 -> a1) (x1 : a0) := (fun y0 : a0 => x0 y0) x1.
Definition term134 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : Prop) (x3 : nat) := (fun y0 : nat => forall y1 : nat, ((@IN a0 x0 x1) = x2) -> (x2 -> (@CARD a0 x1) = y0) -> ((~ x2) -> (S (@CARD a0 x1)) = y1) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat x2 y0 y1)) x3.
Definition term74 (a0 : Type') (x0 : real) := (((@sum a0 (@EMPTY a0) (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@EMPTY a0))) x0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, (((@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (@sum a0 (@INSERT a0 y0 y1) (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 y0 y1))) x0))) -> forall y0 : a0 -> Prop, (@FINITE a0 y0) -> (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0).
Definition term90 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) (x4 : Prop) := ((((@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) = x3) -> (x3 -> ((@sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = x4) -> ((((@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (@sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = (x3 -> x4).
Definition term18 (a0 : Type') (x0 : a0) (x1 : a0 -> real) := forall y0 : a0 -> Prop, (@FINITE a0 y0) -> (@sum a0 (@INSERT a0 x0 y0) x1) = (@COND real (@IN a0 x0 y0) (@sum a0 y0 x1) (real_add (x1 x0) (@sum a0 y0 x1))).
Definition term9 (a0 : Type') (x0 : a0) := forall y0 : a0 -> Prop, (@FINITE a0 y0) -> (@CARD a0 (@INSERT a0 x0 y0)) = (@COND nat (@IN a0 x0 y0) (@CARD a0 y0) (S (@CARD a0 y0))).
Definition term94 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := (~ (@IN a0 x0 x1)) -> (@IN a0 x0 x1) = False.
Definition term44 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := and ((@sum a0 x0 (fun y0 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 x0)) x1)).
Definition term222 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_mul x0 (real_add (real_of_num (@CARD a0 x1)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term272 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_gt (real_neg (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1))) (real_of_num (NUMERAL 0)).
Definition term196 (x0 : real) := real_gt (real_neg (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0))) (real_of_num (NUMERAL 0)).
Definition term24 (a0 : Type') (x0 : a0 -> real) := (fun y0 : a0 -> real => (@sum a0 (@EMPTY a0) y0) = (real_of_num (NUMERAL 0))) x0.
Definition term197 := real_gt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0)).
Definition term206 := real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term48 (a0 : Type') (x0 : real) (x1 : a0) (x2 : a0 -> Prop) := imp (((fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) x2) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))).
Definition term133 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : Prop) := forall y0 : nat, forall y1 : nat, ((@IN a0 x0 x1) = x2) -> (x2 -> (@CARD a0 x1) = y0) -> ((~ x2) -> (S (@CARD a0 x1)) = y1) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat x2 y0 y1).
Definition term116 (a0 : Type') (x0 : a0 -> real) (x1 : a0) := (fun y0 : a0 => x0 y0) x1.
Definition term237 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul x1 (real_of_num (@CARD a0 x0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1).
Definition term226 (x0 : real) := real_mul (real_of_num (NUMERAL (BIT1 0))) x0.
Definition term159 (a0 : Type') (x0 : real) := ((real_of_num (NUMERAL 0)) = (real_mul (real_of_num (NUMERAL 0)) x0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, (((@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (real_add x0 (real_mul (real_of_num (@CARD a0 y1)) x0)) = (real_mul (real_add (real_of_num (@CARD a0 y1)) (real_of_num (NUMERAL (BIT1 0)))) x0)).
Definition term271 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_gt (real_neg (real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1))).
Definition term254 (x0 : nat) (x1 : nat) := real_mul (real_neg (real_of_num x0)) (real_of_num x1).
Definition term43 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := and ((fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) x1).
Definition term13 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := @COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1)).
Definition term95 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := (@FINITE a0 x1) -> (@sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2)) = (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y0 : a0 => x2)) (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2)))).
Definition term181 := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term19 (a0 : Type') (x0 : a0) (x1 : a0 -> real) (x2 : a0 -> Prop) := (fun y0 : a0 -> Prop => (@FINITE a0 y0) -> (@sum a0 (@INSERT a0 x0 y0) x1) = (@COND real (@IN a0 x0 y0) (@sum a0 y0 x1) (real_add (x1 x0) (@sum a0 y0 x1)))) x2.
Definition term212 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))))) = (real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))))).
Definition term148 (a0 : Type') (x0 : a0 -> Prop) := real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term211 := S (Nat.add 0 0).
Definition term28 (a0 : Type') (x0 : type686 a0) := ((x0 (@EMPTY a0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, ((x0 y1) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> x0 (@INSERT a0 y0 y1))) -> forall y0 : a0 -> Prop, (@FINITE a0 y0) -> x0 y0.
Definition term173 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term268 (x0 : real) := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) x0.
Definition term41 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := @sum a0 x0 (fun y0 : a0 => x1).
Definition term170 := real_neg (real_of_num (NUMERAL (BIT1 0))).
Definition term238 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_add (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1).
Definition term70 (a0 : Type') (x0 : real) := fun y0 : a0 -> Prop => (@FINITE a0 y0) -> (fun y1 : a0 -> Prop => (@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) y0.
Definition term256 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term220 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := ~ ((real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) = (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term88 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) := forall y0 : Prop, ((((@sum a0 x1 (fun y1 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) = x3) -> (x3 -> ((@sum a0 (@INSERT a0 x0 x1) (fun y1 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = y0) -> ((((@sum a0 x1 (fun y1 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (@sum a0 (@INSERT a0 x0 x1) (fun y1 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = (x3 -> y0).
Definition term84 (x0 : Prop) (x1 : Prop) (x2 : Prop) := forall y0 : Prop, (x0 = x2) -> (x2 -> x1 = y0) -> (x0 -> x1) = (x2 -> y0).
Definition term66 (a0 : Type') (x0 : real) := imp (((@sum a0 (@EMPTY a0) (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@EMPTY a0))) x0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, (((@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (@sum a0 (@INSERT a0 y0 y1) (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 y0 y1))) x0))).
Definition term49 (a0 : Type') (x0 : real) (x1 : a0) (x2 : a0 -> Prop) := imp (((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2))).
Definition term57 (a0 : Type') (x0 : real) (x1 : a0) := forall y0 : a0 -> Prop, (((fun y1 : a0 -> Prop => (@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) y0) /\ ((~ (@IN a0 x1 y0)) /\ (@FINITE a0 y0))) -> (fun y1 : a0 -> Prop => (@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) (@INSERT a0 x1 y0).
Definition term231 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)).
Definition term122 (a0 : Type') (x0 : real) (x1 : a0) := real_add ((fun y0 : a0 => x0) x1).
Definition term224 (a0 : Type') (x0 : a0 -> Prop) := real_of_num (@CARD a0 x0).
Definition term80 := real_mul (real_of_num (NUMERAL 0)).
Definition term198 (x0 : real) := real_gt (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0)).
Definition term130 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := forall y0 : Prop, forall y1 : nat, forall y2 : nat, ((@IN a0 x0 x1) = y0) -> (y0 -> (@CARD a0 x1) = y1) -> ((~ y0) -> (S (@CARD a0 x1)) = y2) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat y0 y1 y2).
Definition term129 (x0 : Prop) (x1 : nat) (x2 : nat) := forall y0 : Prop, forall y1 : nat, forall y2 : nat, (x0 = y0) -> (y0 -> x1 = y1) -> ((~ y0) -> x2 = y2) -> (@COND nat x0 x1 x2) = (@COND nat y0 y1 y2).
Definition term102 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := forall y0 : Prop, forall y1 : real, forall y2 : real, ((@IN a0 x0 x1) = y0) -> (y0 -> (@sum a0 x1 (fun y3 : a0 => x2)) = y1) -> ((~ y0) -> (real_add ((fun y3 : a0 => x2) x0) (@sum a0 x1 (fun y3 : a0 => x2))) = y2) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y3 : a0 => x2)) (real_add ((fun y3 : a0 => x2) x0) (@sum a0 x1 (fun y3 : a0 => x2)))) = (@COND real y0 y1 y2).
Definition term101 (x0 : Prop) (x1 : real) (x2 : real) := forall y0 : Prop, forall y1 : real, forall y2 : real, (x0 = y0) -> (y0 -> x1 = y1) -> ((~ y0) -> x2 = y2) -> (@COND real x0 x1 x2) = (@COND real y0 y1 y2).
Definition term100 (a0 : Type') (x0 : Prop) (x1 : a0) (x2 : a0) := forall y0 : Prop, forall y1 : a0, forall y2 : a0, (x0 = y0) -> (y0 -> x1 = y1) -> ((~ y0) -> x2 = y2) -> (@COND a0 x0 x1 x2) = (@COND a0 y0 y1 y2).
Definition term86 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := forall y0 : Prop, forall y1 : Prop, ((((@sum a0 x1 (fun y2 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) = y0) -> (y0 -> ((@sum a0 (@INSERT a0 x0 x1) (fun y2 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = y1) -> ((((@sum a0 x1 (fun y2 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (@sum a0 (@INSERT a0 x0 x1) (fun y2 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = (y0 -> y1).
Definition term85 (x0 : Prop) (x1 : Prop) := forall y0 : Prop, forall y1 : Prop, (x0 = y0) -> (y0 -> x1 = y1) -> (x0 -> x1) = (y0 -> y1).
Definition term203 := real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0)).
Definition term242 (x0 : real) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0.
Definition term26 (a0 : Type') := forall y0 : type686 a0, ((y0 (@EMPTY a0)) /\ (forall y1 : a0, forall y2 : a0 -> Prop, ((y0 y2) /\ ((~ (@IN a0 y1 y2)) /\ (@FINITE a0 y2))) -> y0 (@INSERT a0 y1 y2))) -> forall y1 : a0 -> Prop, (@FINITE a0 y1) -> y0 y1.
Definition term69 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := (@FINITE a0 x0) -> (@sum a0 x0 (fun y0 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 x0)) x1).
Definition term16 (a0 : Type') (x0 : a0) := forall y0 : a0 -> real, forall y1 : a0 -> Prop, (@FINITE a0 y1) -> (@sum a0 (@INSERT a0 x0 y1) y0) = (@COND real (@IN a0 x0 y1) (@sum a0 y1 y0) (real_add (y0 x0) (@sum a0 y1 y0))).
Definition term179 (x0 : nat) (x1 : nat) := real_mul (real_of_num x0) (real_of_num x1).
Definition term263 := real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term89 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) (x4 : Prop) := (fun y0 : Prop => ((((@sum a0 x1 (fun y1 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) = x3) -> (x3 -> ((@sum a0 (@INSERT a0 x0 x1) (fun y1 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = y0) -> ((((@sum a0 x1 (fun y1 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (@sum a0 (@INSERT a0 x0 x1) (fun y1 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = (x3 -> y0)) x4.
Definition term245 := real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term37 (a0 : Type') (x0 : real) := real_mul (real_of_num (@CARD a0 (@EMPTY a0))) x0.
Definition term117 (a0 : Type') (x0 : real) (x1 : a0) := (fun y0 : a0 => (fun y1 : a0 => x0) y0) x1.
Definition term76 (a0 : Type') (x0 : real) := @eq real (@sum a0 (@EMPTY a0) (fun y0 : a0 => x0)).
Definition term266 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_add (real_add (real_mul x0 (real_of_num (@CARD a0 x1))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul x0 (real_of_num (@CARD a0 x1))))).
Definition term47 (a0 : Type') (x0 : real) (x1 : a0) (x2 : a0 -> Prop) := ((@sum a0 x2 (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 x2)) x0)) /\ ((~ (@IN a0 x1 x2)) /\ (@FINITE a0 x2)).
Definition term150 (a0 : Type') (x0 : a0 -> Prop) := real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term82 (x0 : real) := and ((real_of_num (NUMERAL 0)) = (real_mul (real_of_num (NUMERAL 0)) x0)).
Definition term40 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := (fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) x1.
Definition term27 (a0 : Type') (x0 : type686 a0) := (fun y0 : type686 a0 => ((y0 (@EMPTY a0)) /\ (forall y1 : a0, forall y2 : a0 -> Prop, ((y0 y2) /\ ((~ (@IN a0 y1 y2)) /\ (@FINITE a0 y2))) -> y0 (@INSERT a0 y1 y2))) -> forall y1 : a0 -> Prop, (@FINITE a0 y1) -> y0 y1) x0.
Definition term255 (x0 : nat) (x1 : nat) := real_neg (real_of_num (Nat.mul x0 x1)).
Definition term4 := forall y0 : nat, (real_add (real_of_num y0) (real_of_num (NUMERAL (BIT1 0)))) = (real_of_num (S y0)).
Definition term23 (a0 : Type') := forall y0 : a0 -> real, (@sum a0 (@EMPTY a0) y0) = (real_of_num (NUMERAL 0)).
Definition term109 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : Prop) (x4 : real) (x5 : real) := ((@IN a0 x0 x1) = x3) -> (x3 -> (@sum a0 x1 (fun y0 : a0 => x2)) = x4) -> ((~ x3) -> (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2))) = x5) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y0 : a0 => x2)) (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2)))) = (@COND real x3 x4 x5).
Definition term241 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul x0 (real_of_num (@CARD a0 x1))).
Definition term55 (a0 : Type') (x0 : real) (x1 : a0) := fun y0 : a0 -> Prop => (((fun y1 : a0 -> Prop => (@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) y0) /\ ((~ (@IN a0 x1 y0)) /\ (@FINITE a0 y0))) -> (fun y1 : a0 -> Prop => (@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) (@INSERT a0 x1 y0).
Definition term143 (a0 : Type') (x0 : a0 -> Prop) := (~ False) -> (S (@CARD a0 x0)) = (S (@CARD a0 x0)).
Definition term147 (a0 : Type') (x0 : a0 -> Prop) := real_of_num (S (@CARD a0 x0)).
Definition term186 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0))).
Definition term30 (a0 : Type') (x0 : type686 a0) := forall y0 : a0 -> Prop, (@FINITE a0 y0) -> x0 y0.
Definition term99 (a0 : Type') (x0 : Prop) (x1 : a0) (x2 : a0) (x3 : Prop) := forall y0 : a0, forall y1 : a0, (x0 = x3) -> (x3 -> x1 = y0) -> ((~ x3) -> x2 = y1) -> (@COND a0 x0 x1 x2) = (@COND a0 x3 y0 y1).
Definition term140 (a0 : Type') (x0 : a0 -> Prop) := False -> (@CARD a0 x0) = (@CARD a0 x0).
Definition term141 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : nat) := (False -> (@CARD a0 x1) = (@CARD a0 x1)) -> ((~ False) -> (S (@CARD a0 x1)) = x2) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat False (@CARD a0 x1) x2).
Definition term182 := real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0))).
Definition term154 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := (((@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (real_add x2 (real_mul (real_of_num (@CARD a0 x1)) x2)) = (real_mul (real_add (real_of_num (@CARD a0 x1)) (real_of_num (NUMERAL (BIT1 0)))) x2).
Definition term240 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_add (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul x1 (real_of_num (@CARD a0 x0))))) (real_add x1 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x1)).
Definition term188 (x0 : real) := real_div x0 (real_of_num (NUMERAL (BIT1 0))).
Definition term214 (x0 : nat) := real_mul (real_of_num (NUMERAL 0)) (real_of_num x0).
Definition term178 := real_of_num (NUMERAL (BIT1 0)).
Definition term38 (a0 : Type') (x0 : real) := and ((fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) (@EMPTY a0)).
Definition term31 (a0 : Type') (x0 : type686 a0) := (forall y0 : type686 a0, ((y0 (@EMPTY a0)) /\ (forall y1 : a0, forall y2 : a0 -> Prop, ((y0 y2) /\ ((~ (@IN a0 y1 y2)) /\ (@FINITE a0 y2))) -> y0 (@INSERT a0 y1 y2))) -> forall y1 : a0 -> Prop, (@FINITE a0 y1) -> y0 y1) -> forall y0 : a0 -> Prop, (@FINITE a0 y0) -> x0 y0.
Definition term277 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := ((~ ((real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) = (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1))) -> False) -> (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) = (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1).
Definition term81 (x0 : real) := real_mul (real_of_num (NUMERAL 0)) x0.
Definition term265 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_mul (real_of_num (NUMERAL 0)) (real_mul x0 (real_of_num (@CARD a0 x1))).
Definition term234 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_sub (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1) (real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1).
Definition term207 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))))) = (real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))))).
Definition term225 (x0 : real) := real_mul x0 (real_of_num (NUMERAL (BIT1 0))).
Definition term191 (x0 : real) := real_neg (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0)).
Definition term163 (x0 : real) := real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0).
Definition term201 := or (real_gt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0))).
Definition term152 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := (((@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> ((@sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2)) = ((real_add x2 (real_mul (real_of_num (@CARD a0 x1)) x2)) = (real_mul (real_add (real_of_num (@CARD a0 x1)) (real_of_num (NUMERAL (BIT1 0)))) x2)).
Definition term149 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))).
Definition term180 (x0 : nat) (x1 : nat) := real_of_num (Nat.mul x0 x1).
Definition term125 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := ((~ False) -> (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2))) = (real_add x2 (real_mul (real_of_num (@CARD a0 x1)) x2))) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y0 : a0 => x2)) (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2)))) = (@COND real False (real_mul (real_of_num (@CARD a0 x1)) x2) (real_add x2 (real_mul (real_of_num (@CARD a0 x1)) x2))).
Definition term276 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := (~ ((real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) = (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1))) -> False.
Definition term218 (x0 : real) := (~ ((real_of_num (NUMERAL 0)) = (real_mul (real_of_num (NUMERAL 0)) x0))) -> False.
Definition term194 (x0 : real) := real_gt (real_neg (real_sub (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL 0)) x0))).
Definition term233 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_sub (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)) (real_mul (real_add (real_of_num (@CARD a0 x0)) (real_of_num (NUMERAL (BIT1 0)))) x1).
Definition term190 := real_add (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0)).
Definition term137 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : Prop) (x3 : nat) (x4 : nat) := ((@IN a0 x0 x1) = x2) -> (x2 -> (@CARD a0 x1) = x3) -> ((~ x2) -> (S (@CARD a0 x1)) = x4) -> (@COND nat (@IN a0 x0 x1) (@CARD a0 x1) (S (@CARD a0 x1))) = (@COND nat x2 x3 x4).
Definition term32 (a0 : Type') := (forall y0 : type686 a0, ((y0 (@EMPTY a0)) /\ (forall y1 : a0, forall y2 : a0 -> Prop, ((y0 y2) /\ ((~ (@IN a0 y1 y2)) /\ (@FINITE a0 y2))) -> y0 (@INSERT a0 y1 y2))) -> forall y1 : a0 -> Prop, (@FINITE a0 y1) -> y0 y1) -> forall y0 : type686 a0, ((y0 (@EMPTY a0)) /\ (forall y1 : a0, forall y2 : a0 -> Prop, ((y0 y2) /\ ((~ (@IN a0 y1 y2)) /\ (@FINITE a0 y2))) -> y0 (@INSERT a0 y1 y2))) -> forall y1 : a0 -> Prop, (@FINITE a0 y1) -> y0 y1.
Definition term112 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := False -> (@sum a0 x0 (fun y0 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 x0)) x1).
Definition term114 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : real) := ((~ False) -> (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2))) = x3) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y0 : a0 => x2)) (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2)))) = (@COND real False (real_mul (real_of_num (@CARD a0 x1)) x2) x3).
Definition term2 := fun y0 : nat => (real_add (real_of_num y0) (real_of_num (NUMERAL (BIT1 0)))) = (real_of_num (S y0)).
Definition term156 (a0 : Type') (x0 : a0) (x1 : real) := forall y0 : a0 -> Prop, (((@sum a0 y0 (fun y1 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 y0)) x1)) /\ ((~ (@IN a0 x0 y0)) /\ (@FINITE a0 y0))) -> (real_add x1 (real_mul (real_of_num (@CARD a0 y0)) x1)) = (real_mul (real_add (real_of_num (@CARD a0 y0)) (real_of_num (NUMERAL (BIT1 0)))) x1).
Definition term58 (a0 : Type') (x0 : a0) (x1 : real) := forall y0 : a0 -> Prop, (((@sum a0 y0 (fun y1 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 y0)) x1)) /\ ((~ (@IN a0 x0 y0)) /\ (@FINITE a0 y0))) -> (@sum a0 (@INSERT a0 x0 y0) (fun y1 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 y0))) x1).
Definition term145 (a0 : Type') (x0 : a0 -> Prop) := @COND nat False (@CARD a0 x0) (S (@CARD a0 x0)).
Definition term45 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := (~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1).
Definition term75 (a0 : Type') (x0 : real) := fun y0 : a0 => x0.
Definition term205 := real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term248 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term54 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := (((@sum a0 x1 (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 x1)) x2)) /\ ((~ (@IN a0 x0 x1)) /\ (@FINITE a0 x1))) -> (@sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 x0 x1))) x2).
Definition term166 (x0 : nat) := real_div (real_of_num x0) (real_of_num (NUMERAL (BIT1 0))).
Definition term50 (a0 : Type') (x0 : real) (x1 : a0) (x2 : a0 -> Prop) := (fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) (@INSERT a0 x1 x2).
Definition term127 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := @eq real (@sum a0 (@INSERT a0 x0 x1) (fun y0 : a0 => x2)).
Definition term244 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul x0 (real_of_num (@CARD a0 x1))).
Definition term174 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term64 (a0 : Type') (x0 : real) := ((@sum a0 (@EMPTY a0) (fun y0 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@EMPTY a0))) x0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, (((@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (@sum a0 (@INSERT a0 y0 y1) (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 y0 y1))) x0)).
Definition term187 := real_div (real_of_num (NUMERAL 0)).
Definition term29 (a0 : Type') (x0 : type686 a0) := (x0 (@EMPTY a0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, ((x0 y1) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> x0 (@INSERT a0 y0 y1)).
Definition term189 := real_add (real_of_num (NUMERAL 0)).
Definition term158 (a0 : Type') (x0 : real) := forall y0 : a0, forall y1 : a0 -> Prop, (((@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (real_add x0 (real_mul (real_of_num (@CARD a0 y1)) x0)) = (real_mul (real_add (real_of_num (@CARD a0 y1)) (real_of_num (NUMERAL (BIT1 0)))) x0).
Definition term62 (a0 : Type') (x0 : real) := forall y0 : a0, forall y1 : a0 -> Prop, (((@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (@sum a0 (@INSERT a0 y0 y1) (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 (@INSERT a0 y0 y1))) x0).
Definition term61 (a0 : Type') (x0 : real) := forall y0 : a0, forall y1 : a0 -> Prop, (((fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) y1) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) (@INSERT a0 y0 y1).
Definition term7 (a0 : Type') := forall y0 : a0, forall y1 : a0 -> Prop, (@FINITE a0 y1) -> (@CARD a0 (@INSERT a0 y0 y1)) = (@COND nat (@IN a0 y0 y1) (@CARD a0 y1) (S (@CARD a0 y1))).
Definition term65 (a0 : Type') (x0 : real) := imp (((fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) (@EMPTY a0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, (((fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) y1) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) (@INSERT a0 y0 y1))).
Definition term128 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := @eq real (real_add x1 (real_mul (real_of_num (@CARD a0 x0)) x1)).
Definition term97 (a0 : Type') (x0 : Prop) (x1 : a0) (x2 : a0) (x3 : Prop) (x4 : a0) (x5 : a0) := (x0 = x3) -> (x3 -> x1 = x4) -> ((~ x3) -> x2 = x5) -> (@COND a0 x0 x1 x2) = (@COND a0 x3 x4 x5).
Definition term15 (a0 : Type') (x0 : a0) := (fun y0 : a0 => forall y1 : a0 -> real, forall y2 : a0 -> Prop, (@FINITE a0 y2) -> (@sum a0 (@INSERT a0 y0 y2) y1) = (@COND real (@IN a0 y0 y2) (@sum a0 y2 y1) (real_add (y1 y0) (@sum a0 y2 y1)))) x0.
Definition term262 := real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0))).
Definition term111 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) (x3 : real) (x4 : real) := (False -> (@sum a0 x1 (fun y0 : a0 => x2)) = x3) -> ((~ False) -> (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2))) = x4) -> (@COND real (@IN a0 x0 x1) (@sum a0 x1 (fun y0 : a0 => x2)) (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2)))) = (@COND real False x3 x4).
Definition term72 (a0 : Type') (x0 : real) := forall y0 : a0 -> Prop, (@FINITE a0 y0) -> (fun y1 : a0 -> Prop => (@sum a0 y1 (fun y2 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y1)) x0)) y0.
Definition term146 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) := real_of_num (@CARD a0 (@INSERT a0 x0 x1)).
Definition term21 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : a0 -> real) := @sum a0 (@INSERT a0 x0 x1) x2.
Definition term3 := fun y0 : nat => (real_of_num (S y0)) = (real_add (real_of_num y0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term172 := NUMERAL (BIT1 0).
Definition term164 := real_sub (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL 0)).
Definition term267 (x0 : real) := real_add x0 (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) x0).
Definition term103 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2)).
Definition term228 (a0 : Type') (x0 : a0 -> Prop) (x1 : real) := real_add (real_mul x1 (real_of_num (@CARD a0 x0))) x1.
Definition term124 (a0 : Type') (x0 : a0) (x1 : a0 -> Prop) (x2 : real) := (~ False) -> (real_add ((fun y0 : a0 => x2) x0) (@sum a0 x1 (fun y0 : a0 => x2))) = (real_add x2 (real_mul (real_of_num (@CARD a0 x1)) x2)).
Definition term155 (a0 : Type') (x0 : a0) (x1 : real) := fun y0 : a0 -> Prop => (((@sum a0 y0 (fun y1 : a0 => x1)) = (real_mul (real_of_num (@CARD a0 y0)) x1)) /\ ((~ (@IN a0 x0 y0)) /\ (@FINITE a0 y0))) -> (real_add x1 (real_mul (real_of_num (@CARD a0 y0)) x1)) = (real_mul (real_add (real_of_num (@CARD a0 y0)) (real_of_num (NUMERAL (BIT1 0)))) x1).
Definition term78 (a0 : Type') := real_of_num (@CARD a0 (@EMPTY a0)).
Definition term216 := real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term63 (a0 : Type') (x0 : real) := ((fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) (@EMPTY a0)) /\ (forall y0 : a0, forall y1 : a0 -> Prop, (((fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) y1) /\ ((~ (@IN a0 y0 y1)) /\ (@FINITE a0 y1))) -> (fun y2 : a0 -> Prop => (@sum a0 y2 (fun y3 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y2)) x0)) (@INSERT a0 y0 y1)).
Definition term68 (a0 : Type') (x0 : real) (x1 : a0 -> Prop) := (@FINITE a0 x1) -> (fun y0 : a0 -> Prop => (@sum a0 y0 (fun y1 : a0 => x0)) = (real_mul (real_of_num (@CARD a0 y0)) x0)) x1.
Definition term195 := real_gt (real_of_num (NUMERAL 0)).
