Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term95 (x0 : nat) (x1 : nat) := (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) \/ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term157 := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term175 := real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term112 := real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term65 (x0 : nat) := real_div (real_neg (real_of_num x0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term76 := Nat.pow (BIT1 0) (NUMERAL (BIT0 (BIT1 0))).
Definition term114 (x0 : nat) (x1 : nat) := real_lt (real_of_num x0) (real_of_num x1).
Definition term150 := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term151 := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term64 (x0 : nat) := real_neg (real_of_num x0).
Definition term49 (x0 : Prop) := ~ (~ x0).
Definition term52 := real_of_num (NUMERAL 0).
Definition term209 (x0 : nat) := real_add (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term89 (x0 : nat) (x1 : nat) := real_ge (real_sub (real_of_num x0) (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term20 (x0 : int) (x1 : int) := (int_le (int_add x1 (int_of_num (NUMERAL (BIT1 0)))) x0) \/ (int_le (int_add x0 (int_of_num (NUMERAL (BIT1 0)))) x1).
Definition term149 := ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term153 := real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term56 (x0 : nat) (x1 : nat) := real_ge (real_sub (real_of_num x0) (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL 0)).
Definition term187 (x0 : nat) (x1 : nat) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))).
Definition term140 (x0 : nat) := real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)).
Definition term171 := real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term96 (x0 : nat) (x1 : nat) := and ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))).
Definition term186 (x0 : nat) (x1 : nat) := (fun y0 : real => (real_mul y0 (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)))) = (real_of_num (NUMERAL 0))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term70 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term50 (x0 : nat) (x1 : nat) := ~ (~ ((((real_of_num x0) = (real_of_num x1)) /\ ((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)))) \/ (((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) /\ ((real_of_num x0) = (real_of_num x1))))).
Definition term142 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term17 (x0 : nat) := @eq real (real_of_int (int_of_num x0)).
Definition term3 (x0 : nat) := @eq int (int_abs (int_of_num x0)).
Definition term126 (x0 : nat) (x1 : nat) := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term176 (x0 : nat) (x1 : nat) := real_le (real_of_num x0) (real_neg (real_of_num x1)).
Definition term147 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term146 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term163 (x0 : nat) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x0)).
Definition term109 := real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term59 (x0 : nat) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term14 (x0 : nat) (x1 : nat) := (~ ((int_of_num x0) = (int_of_num x1))) /\ ((int_of_num x0) = (int_of_num x1)).
Definition term88 (x0 : nat) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0).
Definition term205 (x0 : nat) (x1 : nat) := real_ge (real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x1)) (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term136 (x0 : nat) (x1 : nat) := real_ge (real_add (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term9 (x0 : nat) (x1 : nat) := ((int_of_num x0) = (int_of_num x1)) /\ (~ ((int_of_num x0) = (int_of_num x1))).
Definition term215 (x0 : nat) (x1 : nat) := ~ ((((real_of_num x0) = (real_of_num x1)) /\ ((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)))) \/ (((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) /\ ((real_of_num x0) = (real_of_num x1)))).
Definition term80 := real_neg (real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)))).
Definition term37 (x0 : nat) := real_le (real_of_int (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0))))).
Definition term183 (x0 : nat) (x1 : nat) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term125 (x0 : nat) (x1 : nat) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term66 := real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term133 (x0 : nat) (x1 : nat) := @eq real (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)))).
Definition term168 := real_le (real_of_num (NUMERAL 0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term87 (x0 : nat) (x1 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term115 := Peano.lt (NUMERAL 0) (NUMERAL (BIT1 0)).
Definition term21 (x0 : nat) (x1 : nat) := (int_le (int_add (int_of_num x1) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x0)) \/ (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x1)).
Definition term170 := real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term191 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term18 (x0 : nat) := @eq real (real_of_num x0).
Definition term174 := real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term148 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> ((real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0)))) = (real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))))) -> (real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term145 := real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term53 (x0 : nat) (x1 : nat) := real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)).
Definition term214 (x0 : nat) (x1 : nat) := ((~ (~ ((((real_of_num x0) = (real_of_num x1)) /\ ((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)))) \/ (((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) /\ ((real_of_num x0) = (real_of_num x1)))))) -> False) -> ~ ((((real_of_num x0) = (real_of_num x1)) /\ ((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)))) \/ (((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) /\ ((real_of_num x0) = (real_of_num x1)))).
Definition term169 := real_le (real_of_num (NUMERAL 0)).
Definition term131 (x0 : nat) (x1 : nat) := (fun y0 : real => (real_mul y0 (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)))) = (real_of_num (NUMERAL 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term48 (x0 : nat) (x1 : nat) := (((real_of_num x0) = (real_of_num x1)) /\ ((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)))) \/ (((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) /\ ((real_of_num x0) = (real_of_num x1))).
Definition term26 (x0 : int) (x1 : int) := real_of_int (int_add x0 x1).
Definition term177 (x0 : nat) (x1 : nat) := (x0 = (NUMERAL 0)) /\ (x1 = (NUMERAL 0)).
Definition term51 (x0 : nat) (x1 : nat) := real_sub (real_of_num x0) (real_of_num x1).
Definition term54 (x0 : nat) (x1 : nat) := @eq real (real_sub (real_of_num x0) (real_of_num x1)).
Definition term208 (x0 : nat) := real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term86 (x0 : nat) (x1 : nat) := real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term36 (x0 : nat) := real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0))).
Definition term39 (x0 : nat) (x1 : nat) := real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1).
Definition term7 (x0 : nat) (x1 : nat) := and ((int_of_num x0) = (int_of_num x1)).
Definition term110 := real_lt (real_of_num (NUMERAL 0)).
Definition term189 (x0 : nat) := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)).
Definition term15 (x0 : nat) (x1 : nat) := (((int_of_num x0) = (int_of_num x1)) /\ (~ ((int_of_num x0) = (int_of_num x1)))) \/ ((~ ((int_of_num x0) = (int_of_num x1))) /\ ((int_of_num x0) = (int_of_num x1))).
Definition term102 (x0 : nat) (x1 : nat) := ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0)))).
Definition term58 (x0 : nat) (x1 : nat) := real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0))))).
Definition term181 (x0 : nat) (x1 : nat) := (real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term122 (x0 : nat) (x1 : nat) := (real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term91 (x0 : nat) (x1 : nat) := real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)).
Definition term206 (x0 : nat) (x1 : nat) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x1)) (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term179 := and ((NUMERAL 0) = (NUMERAL 0)).
Definition term202 (x0 : nat) (x1 : nat) := @eq real (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x1)).
Definition term45 (x0 : nat) (x1 : nat) := and ((real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) \/ (real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))).
Definition term212 (x0 : nat) (x1 : nat) := (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))).
Definition term211 (x0 : nat) (x1 : nat) := (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))).
Definition term16 (x0 : nat) := real_of_int (int_of_num x0).
Definition term0 (x0 : nat) (x1 : nat) := ~ (((int_of_num x0) = (int_of_num x1)) = ((int_abs (int_of_num x0)) = (int_abs (int_of_num x1)))).
Definition term92 (x0 : nat) (x1 : nat) := real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term120 := real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term200 (x0 : nat) (x1 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x1).
Definition term152 (x0 : nat) := real_add (real_neg (real_of_num x0)) (real_of_num x0).
Definition term77 := Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0)).
Definition term193 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term38 (x0 : nat) := real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))).
Definition term190 (x0 : nat) := real_mul (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))) (real_of_num x0).
Definition term27 (x0 : int) (x1 : int) := real_add (real_of_int x0) (real_of_int x1).
Definition term143 := real_add (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term178 := ((NUMERAL 0) = (NUMERAL 0)) /\ ((NUMERAL (BIT1 0)) = (NUMERAL 0)).
Definition term81 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term60 (x0 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term129 (x0 : nat) (x1 : nat) := ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) -> forall y0 : real, (real_mul y0 (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)))) = (real_of_num (NUMERAL 0)).
Definition term162 (x0 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x0).
Definition term108 := real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0))).
Definition term8 (x0 : nat) (x1 : nat) := ((int_of_num x0) = (int_of_num x1)) /\ (~ ((int_abs (int_of_num x0)) = (int_abs (int_of_num x1)))).
Definition term132 (x0 : nat) (x1 : nat) := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))).
Definition term207 (x0 : nat) (x1 : nat) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x0)) (real_add (real_of_num x1) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term139 (x0 : nat) := real_add (real_of_num x0) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term46 (x0 : nat) (x1 : nat) := ((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) /\ ((real_of_num x0) = (real_of_num x1)).
Definition term138 (x0 : nat) (x1 : nat) := real_add (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term137 (x0 : nat) (x1 : nat) := real_add (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term43 (x0 : nat) (x1 : nat) := and ((real_of_num x0) = (real_of_num x1)).
Definition term78 (x0 : nat) (x1 : nat) := real_mul (real_neg (real_of_num x0)) (real_of_num x1).
Definition term1 (x0 : nat) (x1 : nat) := (((int_of_num x0) = (int_of_num x1)) /\ (~ ((int_abs (int_of_num x0)) = (int_abs (int_of_num x1))))) \/ ((~ ((int_of_num x0) = (int_of_num x1))) /\ ((int_abs (int_of_num x0)) = (int_abs (int_of_num x1)))).
Definition term165 (x0 : nat) (x1 : nat) := real_ge (real_add (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0))))))).
Definition term197 := real_mul (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term44 (x0 : nat) (x1 : nat) := ((real_of_num x1) = (real_of_num x0)) /\ ((real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) \/ (real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))).
Definition term196 := real_div (real_of_num (NUMERAL (BIT1 0))).
Definition term134 (x0 : real) (x1 : real) := ((x0 = (real_of_num (NUMERAL 0))) /\ (real_ge x1 (real_of_num (NUMERAL 0)))) -> real_ge (real_add x0 x1) (real_of_num (NUMERAL 0)).
Definition term123 (x0 : real) (x1 : real) := ((real_gt x0 (real_of_num (NUMERAL 0))) /\ (real_ge x1 (real_of_num (NUMERAL 0)))) -> real_ge (real_mul x0 x1) (real_of_num (NUMERAL 0)).
Definition term82 := real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term23 (x0 : nat) (x1 : nat) := int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x1).
Definition term74 := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term166 := real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term160 (x0 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x0) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term117 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term173 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term2 (x0 : nat) := int_abs (int_of_num x0).
Definition term116 := S (Nat.add 0 0).
Definition term67 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term216 (x0 : nat) (x1 : nat) := ~ (~ (((int_of_num x0) = (int_of_num x1)) = ((int_abs (int_of_num x0)) = (int_abs (int_of_num x1))))).
Definition term61 := real_neg (real_of_num (NUMERAL (BIT1 0))).
Definition term69 := real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term85 (x0 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term57 (x0 : nat) (x1 : nat) := real_sub (real_of_num x0) (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))).
Definition term104 (x0 : nat) (x1 : nat) := or ((((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))))).
Definition term41 (x0 : nat) (x1 : nat) := or (real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)).
Definition term25 (x0 : nat) := int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0))).
Definition term127 (x0 : nat) (x1 : nat) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0))))))).
Definition term154 := real_mul (real_of_num (NUMERAL 0)).
Definition term4 (x0 : nat) := @eq int (int_of_num x0).
Definition term97 (x0 : nat) (x1 : nat) := ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) \/ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))).
Definition term55 (x0 : nat) (x1 : nat) := @eq real (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))).
Definition term192 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term195 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_neg (real_of_num (NUMERAL (BIT1 0))))).
Definition term31 (x0 : nat) := real_add (real_of_int (int_of_num x0)).
Definition term24 (x0 : nat) (x1 : nat) := real_le (real_of_int (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0))))) (real_of_int (int_of_num x1)).
Definition term72 (x0 : nat) (x1 : nat) := real_mul (real_of_num x0) (real_of_num x1).
Definition term158 (x0 : nat) := real_add (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))).
Definition term198 := real_mul (real_of_num (NUMERAL (BIT1 0))).
Definition term156 := real_mul (real_of_num (NUMERAL 0)) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term19 (x0 : int) (x1 : int) := ~ (x0 = x1).
Definition term63 := real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))).
Definition term161 (x0 : nat) := real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term204 (x0 : nat) (x1 : nat) := (((real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x1)) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) -> real_ge (real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x1)) (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term182 (x0 : nat) (x1 : nat) := ((real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) -> real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term135 (x0 : nat) (x1 : nat) := (((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) -> real_ge (real_add (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term124 (x0 : nat) (x1 : nat) := ((real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) -> real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0))))))) (real_of_num (NUMERAL 0)).
Definition term203 (x0 : nat) (x1 : nat) := ((real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x1)) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term180 (x0 : nat) (x1 : nat) := ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term106 (x0 : nat) (x1 : nat) := ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term98 (x0 : nat) (x1 : nat) := and ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) \/ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))).
Definition term185 (x0 : nat) (x1 : nat) := real_ge (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))).
Definition term79 (x0 : nat) (x1 : nat) := real_neg (real_of_num (Nat.mul x0 x1)).
Definition term210 (x0 : nat) (x1 : nat) := real_ge (real_add (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_of_num x1)) (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0))))))).
Definition term22 (x0 : int) (x1 : int) := real_le (real_of_int x0) (real_of_int x1).
Definition term194 (x0 : nat) (x1 : nat) := real_mul (real_neg (real_of_num x0)) (real_neg (real_of_num x1)).
Definition term90 (x0 : nat) (x1 : nat) := real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term201 (x0 : nat) (x1 : nat) := @eq real (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)))).
Definition term32 (x0 : nat) := real_add (real_of_num x0).
Definition term141 (x0 : nat) := real_mul (real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0).
Definition term199 (x0 : nat) := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num x0).
Definition term188 (x0 : nat) (x1 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))).
Definition term99 (x0 : nat) (x1 : nat) := ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) \/ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) /\ ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))).
Definition term84 (x0 : nat) := real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)).
Definition term5 (x0 : nat) (x1 : nat) := ~ ((int_abs (int_of_num x0)) = (int_abs (int_of_num x1))).
Definition term12 (x0 : nat) (x1 : nat) := and (~ ((int_of_num x0) = (int_of_num x1))).
Definition term75 := real_of_num (Nat.mul (NUMERAL (BIT1 0)) (NUMERAL (BIT1 0))).
Definition term100 (x0 : nat) (x1 : nat) := or (((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) \/ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))))).
Definition term83 (x0 : real) := real_div x0 (real_of_num (NUMERAL (BIT1 0))).
Definition term119 (x0 : nat) := real_mul (real_of_num (NUMERAL 0)) (real_of_num x0).
Definition term34 := real_of_num (NUMERAL (BIT1 0)).
Definition term118 := real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term164 := real_add (real_of_num (NUMERAL 0)) (real_neg (real_of_num (NUMERAL (BIT1 0)))).
Definition term29 (x0 : nat) := real_add (real_of_int (int_of_num x0)) (real_of_int (int_of_num (NUMERAL (BIT1 0)))).
Definition term28 (x0 : nat) := real_of_int (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))).
Definition term130 (x0 : nat) (x1 : nat) := forall y0 : real, (real_mul y0 (real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)))) = (real_of_num (NUMERAL 0)).
Definition term172 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_le (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))) = (real_le (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term113 := (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) -> (real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_div (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) = (real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))).
Definition term103 (x0 : nat) (x1 : nat) := (((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))).
Definition term42 (x0 : nat) (x1 : nat) := (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) \/ (real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)).
Definition term11 (x0 : nat) (x1 : nat) := or (((int_of_num x0) = (int_of_num x1)) /\ (~ ((int_of_num x0) = (int_of_num x1)))).
Definition term33 := real_of_int (int_of_num (NUMERAL (BIT1 0))).
Definition term73 (x0 : nat) (x1 : nat) := real_of_num (Nat.mul x0 x1).
Definition term10 (x0 : nat) (x1 : nat) := or (((int_of_num x0) = (int_of_num x1)) /\ (~ ((int_abs (int_of_num x0)) = (int_abs (int_of_num x1))))).
Definition term128 (x0 : real) := (x0 = (real_of_num (NUMERAL 0))) -> forall y0 : real, (real_mul y0 x0) = (real_of_num (NUMERAL 0)).
Definition term93 (x0 : nat) (x1 : nat) := real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)).
Definition term94 (x0 : nat) (x1 : nat) := or (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))).
Definition term6 (x0 : nat) (x1 : nat) := ~ ((int_of_num x0) = (int_of_num x1)).
Definition term111 := real_lt (real_div (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
Definition term144 := real_add (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0))).
Definition term40 (x0 : nat) (x1 : nat) := or (int_le (int_add (int_of_num x0) (int_of_num (NUMERAL (BIT1 0)))) (int_of_num x1)).
Definition term62 (x0 : nat) := real_div (real_of_num x0) (real_of_num (NUMERAL (BIT1 0))).
Definition term167 := real_ge (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL 0)).
Definition term68 := real_mul (real_div (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term105 (x0 : nat) (x1 : nat) := ((((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) \/ (((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))))) \/ (((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0)))) \/ ((real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) /\ ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))))).
Definition term159 := real_add (real_of_num (NUMERAL 0)).
Definition term213 (x0 : nat) (x1 : nat) := (~ (~ ((((real_of_num x0) = (real_of_num x1)) /\ ((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)))) \/ (((real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) \/ (real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0))) /\ ((real_of_num x0) = (real_of_num x1)))))) -> False.
Definition term47 (x0 : nat) (x1 : nat) := or (((real_of_num x1) = (real_of_num x0)) /\ ((real_le (real_add (real_of_num x1) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) \/ (real_le (real_add (real_of_num x0) (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)))).
Definition term101 (x0 : nat) (x1 : nat) := (((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0))) /\ ((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) \/ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))))) \/ (((real_ge (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x0)) (real_add (real_of_num x1) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0))) \/ (real_ge (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))) (real_of_num (NUMERAL 0)))) /\ ((real_add (real_of_num x0) (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1))) = (real_of_num (NUMERAL 0)))).
Definition term155 := real_mul (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0))))) (real_of_num (NUMERAL (BIT1 0))).
Definition term30 := int_of_num (NUMERAL (BIT1 0)).
Definition term35 := NUMERAL (BIT1 0).
Definition term184 (x0 : nat) (x1 : nat) := real_mul (real_of_num (NUMERAL (BIT1 0))) (real_add (real_of_num x0) (real_add (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num x1)) (real_neg (real_of_num (NUMERAL (BIT1 0)))))).
Definition term107 := real_gt (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL 0)).
Definition term13 (x0 : nat) (x1 : nat) := (~ ((int_of_num x0) = (int_of_num x1))) /\ ((int_abs (int_of_num x0)) = (int_abs (int_of_num x1))).
Definition term71 := real_div (real_mul (real_neg (real_of_num (NUMERAL (BIT1 0)))) (real_of_num (NUMERAL (BIT1 0)))) (real_mul (real_of_num (NUMERAL (BIT1 0))) (real_of_num (NUMERAL (BIT1 0)))).
Definition term121 := real_lt (real_mul (real_of_num (NUMERAL 0)) (real_of_num (NUMERAL (BIT1 0)))).
