Require Import coq.
Require Import theory_hol.
Require Import hol_types.
Require Import hol_type_abbrevs.
Require Import hol_terms.
Definition term38 (x0 : nat) (x1 : nat) := @eq nat (Nat.add (Nat.add x0 x0) (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1))).
Definition term15 (x0 : nat) (x1 : nat) := Nat.add (Nat.mul x0 (Nat.add x1 x1)) (Nat.mul x0 (Nat.add x1 x1)).
Definition term72 (x0 : nat) (x1 : nat) := Nat.add (Nat.add x0 x0) (Nat.add (Nat.add x1 x1) (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))).
Definition term18 (x0 : nat) (x1 : nat) := Nat.mul x0 (Nat.add x1 x1).
Definition term26 (x0 : nat) (x1 : nat) := @eq nat (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)).
Definition term4 (a0 : Type') (x0 : Prop) := forall y0 : a0, x0.
Definition term11 := and (forall y0 : nat, 0 = 0).
Definition term79 := (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))))).
Definition term66 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add x0 (Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)) (Nat.add x1 x1))).
Definition term34 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add x0 (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1))).
Definition term23 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.add x0 x1) x2.
Definition term86 := (0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))))))))))).
Definition term52 (x0 : nat) (x1 : nat) := Nat.add x1 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))).
Definition term65 (x0 : nat) (x1 : nat) := Nat.add (Nat.add x0 x0) (Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)) (Nat.add x1 x1)).
Definition term58 (x0 : nat) (x1 : nat) := Nat.add x1 (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))).
Definition term76 (x0 : nat) := forall y0 : nat, (Nat.add (Nat.add (Nat.add x0 x0) (Nat.mul (Nat.add x0 x0) (Nat.add y0 y0))) (Nat.add y0 y0)) = (Nat.add (Nat.add x0 x0) (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)) (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0))))).
Definition term60 (x0 : nat) := forall y0 : nat, (Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add y0 y0)) (Nat.add y0 y0)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)) (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)))).
Definition term44 (x0 : nat) := forall y0 : nat, (Nat.add (Nat.add x0 x0) (Nat.mul (Nat.add x0 x0) (Nat.add y0 y0))) = (Nat.add (Nat.add x0 x0) (Nat.add (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)) (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)))).
Definition term29 (x0 : nat) := forall y0 : nat, (Nat.mul (Nat.add x0 x0) (Nat.add y0 y0)) = (Nat.add (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)) (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0))).
Definition term21 (x0 : nat) (x1 : nat) := Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)).
Definition term6 := fun y0 : nat => forall y1 : nat, (Nat.mul y0 y1) = (Nat.mul y0 y1).
Definition term81 := (forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))))))).
Definition term25 (x0 : nat) (x1 : nat) := Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))).
Definition term22 (x0 : nat) (x1 : nat) := Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)).
Definition term75 (x0 : nat) := fun y0 : nat => (Nat.add (Nat.add (Nat.add x0 x0) (Nat.mul (Nat.add x0 x0) (Nat.add y0 y0))) (Nat.add y0 y0)) = (Nat.add (Nat.add x0 x0) (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)) (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0))))).
Definition term35 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)).
Definition term36 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))).
Definition term80 := (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))))).
Definition term51 (x0 : nat) (x1 : nat) := Nat.add x1 (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)).
Definition term68 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add x1 (Nat.add x1 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))))).
Definition term2 (x0 : nat) := forall y0 : nat, (Nat.mul x0 y0) = (Nat.mul x0 y0).
Definition term17 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.mul x1 x0) (Nat.mul x1 x2).
Definition term14 (x0 : nat) (x1 : nat) := Nat.mul (Nat.add x0 x0) (Nat.add x1 x1).
Definition term78 := forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))).
Definition term62 := forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))).
Definition term46 := forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))).
Definition term31 := forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))).
Definition term7 := forall y0 : nat, forall y1 : nat, (Nat.mul y0 y1) = (Nat.mul y0 y1).
Definition term69 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add x0 (Nat.add x1 (Nat.add x1 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))))))).
Definition term3 := forall y0 : nat, True.
Definition term12 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.mul (Nat.add x0 x1) x2.
Definition term13 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add (Nat.mul x0 x2) (Nat.mul x1 x2).
Definition term1 := fun y0 : nat => True.
Definition term9 := and (0 = 0).
Definition term48 (x0 : nat) (x1 : nat) := Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)) (Nat.add x1 x1).
Definition term74 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add (Nat.add x1 x1) (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))).
Definition term0 (x0 : nat) := fun y0 : nat => (Nat.mul x0 y0) = (Nat.mul x0 y0).
Definition term56 (x0 : nat) (x1 : nat) := Nat.add (Nat.add x1 x1) (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))).
Definition term43 (x0 : nat) := fun y0 : nat => (Nat.add (Nat.add x0 x0) (Nat.mul (Nat.add x0 x0) (Nat.add y0 y0))) = (Nat.add (Nat.add x0 x0) (Nat.add (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)) (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)))).
Definition term70 (x0 : nat) (x1 : nat) := @eq nat (Nat.add (Nat.add (Nat.add x0 x0) (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1))) (Nat.add x1 x1)).
Definition term24 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.add x0 (Nat.add x1 x2).
Definition term59 (x0 : nat) := fun y0 : nat => (Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add y0 y0)) (Nat.add y0 y0)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)) (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)))).
Definition term50 (x0 : nat) (x1 : nat) := Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)) x1.
Definition term67 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)) (Nat.add x1 x1)).
Definition term63 := and (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))).
Definition term47 := and (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))).
Definition term32 := and (forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))).
Definition term8 := and (forall y0 : nat, forall y1 : nat, (Nat.mul y0 y1) = (Nat.mul y0 y1)).
Definition term55 (x0 : nat) (x1 : nat) := @eq nat (Nat.add x1 (Nat.add x1 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))))).
Definition term33 (x0 : nat) (x1 : nat) := Nat.add (Nat.add x0 x0) (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)).
Definition term73 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add x0 (Nat.add (Nat.add x1 x1) (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))))).
Definition term41 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add x0 (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))).
Definition term37 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add x0 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))))).
Definition term54 (x0 : nat) (x1 : nat) := @eq nat (Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)) (Nat.add x1 x1)).
Definition term19 (x0 : nat) (x1 : nat) := Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1).
Definition term49 (x0 : nat) (x1 : nat) := Nat.add x1 (Nat.add (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1)) x1).
Definition term28 (x0 : nat) := fun y0 : nat => (Nat.mul (Nat.add x0 x0) (Nat.add y0 y0)) = (Nat.add (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0)) (Nat.add (Nat.mul x0 y0) (Nat.mul x0 y0))).
Definition term27 (x0 : nat) (x1 : nat) := @eq nat (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))).
Definition term5 (x0 : Prop) := forall y0 : nat, x0.
Definition term16 (x0 : nat) (x1 : nat) (x2 : nat) := Nat.mul x0 (Nat.add x1 x2).
Definition term85 := (forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))))))))))).
Definition term84 := (forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))))))))).
Definition term83 := (forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))))))))).
Definition term87 := (forall y0 : nat, forall y1 : nat, (Nat.mul y0 y1) = (Nat.mul y0 y1)) /\ ((0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))))))))))))).
Definition term42 (x0 : nat) (x1 : nat) := Nat.add x0 (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))).
Definition term57 (x0 : nat) (x1 : nat) := Nat.add x1 (Nat.add x1 (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))).
Definition term53 (x0 : nat) (x1 : nat) := Nat.add x1 (Nat.add x1 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))))).
Definition term64 (x0 : nat) (x1 : nat) := Nat.add (Nat.add (Nat.add x0 x0) (Nat.mul (Nat.add x0 x0) (Nat.add x1 x1))) (Nat.add x1 x1).
Definition term71 (x0 : nat) (x1 : nat) := @eq nat (Nat.add x0 (Nat.add x0 (Nat.add x1 (Nat.add x1 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))))))).
Definition term39 (x0 : nat) (x1 : nat) := @eq nat (Nat.add x0 (Nat.add x0 (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)))))).
Definition term82 := (forall y0 : nat, 0 = 0) /\ ((forall y0 : nat, forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ ((forall y0 : nat, forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))) /\ (forall y0 : nat, forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))))))).
Definition term77 := fun y0 : nat => forall y1 : nat, (Nat.add (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) (Nat.add y1 y1)) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))))).
Definition term61 := fun y0 : nat => forall y1 : nat, (Nat.add (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) (Nat.add y1 y1)) = (Nat.add (Nat.add y1 y1) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))).
Definition term45 := fun y0 : nat => forall y1 : nat, (Nat.add (Nat.add y0 y0) (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1))) = (Nat.add (Nat.add y0 y0) (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)))).
Definition term30 := fun y0 : nat => forall y1 : nat, (Nat.mul (Nat.add y0 y0) (Nat.add y1 y1)) = (Nat.add (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1)) (Nat.add (Nat.mul y0 y1) (Nat.mul y0 y1))).
Definition term40 (x0 : nat) (x1 : nat) := Nat.add (Nat.add x0 x0) (Nat.add (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1)) (Nat.add (Nat.mul x0 x1) (Nat.mul x0 x1))).
Definition term20 (x0 : nat) (x1 : nat) := Nat.add (Nat.mul x0 (Nat.add x1 x1)).
Definition term10 := forall y0 : nat, 0 = 0.
